import type { GameDexEntry, GameDex } from "../game-dex";

const d = (
  pokemonId: number,
  name: string,
  versions: string[],
  method?: string
): GameDexEntry => ({ pokemonId, name, versions, method });

/* ======================================================
 *  Pokemon Crystal — Obtainable Pokemon (~251)
 *  Version tag: "C"
 * ====================================================== */
export const CRYSTAL_DEX: GameDex = {
  slug: "crystal",
  versionTags: ["C"],
  pokemon: [
    // --- Gen I Pokemon obtainable in Crystal ---

    // Starters (Kanto — not directly obtainable, trade only)
    d(1, "Bulbasaur", ["C"], "Trade"),
    d(2, "Ivysaur", ["C"], "Evolve Bulbasaur"),
    d(3, "Venusaur", ["C"], "Evolve Ivysaur"),
    d(4, "Charmander", ["C"], "Trade"),
    d(5, "Charmeleon", ["C"], "Evolve Charmander"),
    d(6, "Charizard", ["C"], "Evolve Charmeleon"),
    d(7, "Squirtle", ["C"], "Trade"),
    d(8, "Wartortle", ["C"], "Evolve Squirtle"),
    d(9, "Blastoise", ["C"], "Evolve Wartortle"),

    // Route/common Pokemon
    d(10, "Caterpie", ["C"], "Routes 2, 24, 25, 26, 30, 31, Ilex Forest, National Park, Bug-Catching Contest"),
    d(11, "Metapod", ["C"], "Routes 2, 24, 25, 26, National Park, Bug-Catching Contest, evolve Caterpie"),
    d(12, "Butterfree", ["C"], "National Park, Bug-Catching Contest, evolve Metapod"),
    d(13, "Weedle", ["C"], "Routes 2, 30, 31, Ilex Forest, National Park, Bug-Catching Contest"),
    d(14, "Kakuna", ["C"], "Routes 2, 26, National Park, Bug-Catching Contest, evolve Weedle"),
    d(15, "Beedrill", ["C"], "National Park, Bug-Catching Contest, evolve Kakuna"),
    d(16, "Pidgey", ["C"], "Routes 1, 2, 5, 6, 25, 29, 30, 31, 35, 36, 37"),
    d(17, "Pidgeotto", ["C"], "Routes 8, 14, 15, 37, 43, evolve Pidgey"),
    d(18, "Pidgeot", ["C"], "Evolve Pidgeotto"),
    d(19, "Rattata", ["C"], "Routes 1, 3, 4, 7, 9, 29, 32, 33, 38, 39, Sprout Tower, Burned Tower, Union Cave"),
    d(20, "Raticate", ["C"], "Routes 7, 9, 10, 26, 27, 38, 39, 42, 43, Burned Tower, evolve Rattata"),
    d(21, "Spearow", ["C"], "Routes 3, 4, 9, 22, 33, 42, 46"),
    d(22, "Fearow", ["C"], "Routes 9, 10, 16, 17, 18, 22, 26, 27, 42, evolve Spearow"),
    d(23, "Ekans", ["C"], "Routes 3, 4, 32, 33, 42, Goldenrod Game Corner"),
    d(24, "Arbok", ["C"], "Routes 3, 4, 26, 27, evolve Ekans"),
    d(25, "Pikachu", ["C"], "Route 2 (headbutt trees)"),
    d(26, "Raichu", ["C"], "Evolve Pikachu (Thunder Stone)"),
    d(27, "Sandshrew", ["C"], "Routes 3, 4, Union Cave, Mt. Moon"),
    d(28, "Sandslash", ["C"], "Routes 26, 27, Mt. Moon, evolve Sandshrew"),
    d(29, "Nidoran\u2640", ["C"], "Routes 35, 36"),
    d(30, "Nidorina", ["C"], "Routes 13, 14, 15, evolve Nidoran\u2640"),
    d(31, "Nidoqueen", ["C"], "Evolve Nidorina (Moon Stone)"),
    d(32, "Nidoran\u2642", ["C"], "Routes 35, 36"),
    d(33, "Nidorino", ["C"], "Routes 13, 14, 15, evolve Nidoran\u2642"),
    d(34, "Nidoking", ["C"], "Evolve Nidorino (Moon Stone)"),
    d(35, "Clefairy", ["C"], "Mt. Moon"),
    d(36, "Clefable", ["C"], "Evolve Clefairy (Moon Stone)"),
    d(37, "Vulpix", ["C"], "Routes 7, 8, 36, 37"),
    d(38, "Ninetales", ["C"], "Evolve Vulpix (Fire Stone)"),
    d(39, "Jigglypuff", ["C"], "Routes 3, 4, 34, 46"),
    d(40, "Wigglytuff", ["C"], "Evolve Jigglypuff (Moon Stone)"),
    d(41, "Zubat", ["C"], "Dark Cave, Union Cave, Burned Tower, Slowpoke Well, Ice Path, most caves"),
    d(42, "Golbat", ["C"], "Dark Cave, Ice Path, Victory Road, Mt. Silver, evolve Zubat"),
    d(43, "Oddish", ["C"], "Routes 5, 6, 24, 25, Ilex Forest"),
    d(44, "Gloom", ["C"], "Routes 5, 6, 24, 25, evolve Oddish"),
    d(45, "Vileplume", ["C"], "Evolve Gloom (Leaf Stone)"),
    d(46, "Paras", ["C"], "Ilex Forest, Mt. Moon, National Park"),
    d(47, "Parasect", ["C"], "Evolve Paras"),
    d(48, "Venonat", ["C"], "Routes 24, 25, 43, National Park"),
    d(49, "Venomoth", ["C"], "Routes 24, 25, evolve Venonat"),
    d(50, "Diglett", ["C"], "Diglett's Cave"),
    d(51, "Dugtrio", ["C"], "Diglett's Cave, evolve Diglett"),
    d(52, "Meowth", ["C"], "Routes 5, 8, 39"),
    d(53, "Persian", ["C"], "Evolve Meowth"),
    d(54, "Psyduck", ["C"], "Routes 6, 35, Ilex Forest (Surf)"),
    d(55, "Golduck", ["C"], "Routes 6, 35, Ilex Forest (Surf), Mt. Silver, evolve Psyduck"),
    d(56, "Mankey", ["C"], "Route 42"),
    d(57, "Primeape", ["C"], "Route 9, evolve Mankey"),
    d(58, "Growlithe", ["C"], "Routes 7, 8, 36, 37"),
    d(59, "Arcanine", ["C"], "Evolve Growlithe (Fire Stone)"),
    d(60, "Poliwag", ["C"], "Routes 30, 31, 44, Ecruteak City, Violet City (Fishing/Surf)"),
    d(61, "Poliwhirl", ["C"], "Routes 30, 31, 44 (Surf), evolve Poliwag"),
    d(62, "Poliwrath", ["C"], "Evolve Poliwhirl (Water Stone)"),
    d(63, "Abra", ["C"], "Routes 5, 8, 24, 25, 34, 35, Goldenrod Game Corner"),
    d(64, "Kadabra", ["C"], "Route 8, evolve Abra"),
    d(65, "Alakazam", ["C"], "Trade evolve Kadabra"),
    d(66, "Machop", ["C"], "Mt. Mortar, Rock Tunnel, Goldenrod Department Store (trade for Drowzee)"),
    d(67, "Machoke", ["C"], "Mt. Mortar, Rock Tunnel, evolve Machop"),
    d(68, "Machamp", ["C"], "Trade evolve Machoke"),
    d(69, "Bellsprout", ["C"], "Routes 5, 6, 24, 25, 31, 32, 44"),
    d(70, "Weepinbell", ["C"], "Routes 24, 25, 44, evolve Bellsprout"),
    d(71, "Victreebel", ["C"], "Evolve Weepinbell (Leaf Stone)"),
    d(72, "Tentacool", ["C"], "Routes 12, 13, 19, 20, 21, 26, 27, 32, 34, 40, 41 (Surf)"),
    d(73, "Tentacruel", ["C"], "Routes 12, 13, 19, 20, 21, 26, 27, 41 (Surf), evolve Tentacool"),
    d(74, "Geodude", ["C"], "Union Cave, Dark Cave, Route 46, Rock Tunnel, Mt. Mortar"),
    d(75, "Graveler", ["C"], "Dark Cave, Victory Road, Mt. Silver, evolve Geodude"),
    d(76, "Golem", ["C"], "Trade evolve Graveler"),
    d(77, "Ponyta", ["C"], "Routes 26, 27, Mt. Silver"),
    d(78, "Rapidash", ["C"], "Routes 26, 27, Mt. Silver, evolve Ponyta"),
    d(79, "Slowpoke", ["C"], "Slowpoke Well, Tohjo Falls (Surf/Fishing)"),
    d(80, "Slowbro", ["C"], "Evolve Slowpoke"),
    d(81, "Magnemite", ["C"], "Routes 6, 11, 38, 39"),
    d(82, "Magneton", ["C"], "Evolve Magnemite"),
    d(83, "Farfetch'd", ["C"], "Routes 38, 39, Ilex Forest (event)"),
    d(84, "Doduo", ["C"], "Routes 22, 26, 27, 28"),
    d(85, "Dodrio", ["C"], "Routes 26, 27, 28, evolve Doduo"),
    d(86, "Seel", ["C"], "Whirl Islands"),
    d(87, "Dewgong", ["C"], "Whirl Islands, evolve Seel"),
    d(88, "Grimer", ["C"], "Routes 16, 17, 18, Celadon City"),
    d(89, "Muk", ["C"], "Routes 16, 17, 18, Celadon City, evolve Grimer"),
    d(90, "Shellder", ["C"], "Olivine City, Route 20 (Fishing)"),
    d(91, "Cloyster", ["C"], "Evolve Shellder (Water Stone)"),
    d(92, "Gastly", ["C"], "Sprout Tower, Burned Tower, Tin Tower"),
    d(93, "Haunter", ["C"], "Route 8, Tin Tower, evolve Gastly"),
    d(94, "Gengar", ["C"], "Trade evolve Haunter"),
    d(95, "Onix", ["C"], "Union Cave, Rock Tunnel, Victory Road, trade Bellsprout in Violet City"),
    d(96, "Drowzee", ["C"], "Routes 11, 34, 35"),
    d(97, "Hypno", ["C"], "Route 11, evolve Drowzee"),
    d(98, "Krabby", ["C"], "Olivine City, Routes 19, 34, 40 (Fishing)"),
    d(99, "Kingler", ["C"], "Evolve Krabby"),
    d(100, "Voltorb", ["C"], "Route 10, Mahogany Rocket Hideout"),
    d(101, "Electrode", ["C"], "Route 10, Mahogany Rocket Hideout, evolve Voltorb"),
    d(102, "Exeggcute", ["C"], "Routes 26, 27 (Headbutt trees)"),
    d(103, "Exeggutor", ["C"], "Evolve Exeggcute (Leaf Stone)"),
    d(104, "Cubone", ["C"], "Rock Tunnel"),
    d(105, "Marowak", ["C"], "Rock Tunnel, evolve Cubone"),
    d(106, "Hitmonlee", ["C"], "Evolve Tyrogue (Attack > Defense at Lv20)"),
    d(107, "Hitmonchan", ["C"], "Evolve Tyrogue (Defense > Attack at Lv20)"),
    d(108, "Lickitung", ["C"], "Route 44"),
    d(109, "Koffing", ["C"], "Burned Tower, Mahogany Rocket Hideout"),
    d(110, "Weezing", ["C"], "Evolve Koffing"),
    d(111, "Rhyhorn", ["C"], "Victory Road"),
    d(112, "Rhydon", ["C"], "Evolve Rhyhorn"),
    d(113, "Chansey", ["C"], "Routes 13, 14, 15 (rare)"),
    d(114, "Tangela", ["C"], "Routes 21, 28, 44"),
    d(115, "Kangaskhan", ["C"], "Rock Tunnel (rare)"),
    d(116, "Horsea", ["C"], "Whirl Islands (Fishing)"),
    d(117, "Seadra", ["C"], "Whirl Islands (Fishing), evolve Horsea"),
    d(118, "Goldeen", ["C"], "Routes 42, 43, 44, Mt. Mortar (Fishing)"),
    d(119, "Seaking", ["C"], "Routes 42, 43, 44 (Fishing), evolve Goldeen"),
    d(120, "Staryu", ["C"], "Cherrygrove City, Olivine City (Fishing at night)"),
    d(121, "Starmie", ["C"], "Evolve Staryu (Water Stone)"),
    d(122, "Mr. Mime", ["C"], "Route 21, Kanto (rare)"),
    d(123, "Scyther", ["C"], "National Park, Bug-Catching Contest"),
    d(124, "Jynx", ["C"], "Ice Path"),
    d(125, "Electabuzz", ["C"], "Route 10"),
    d(126, "Magmar", ["C"], "Burned Tower"),
    d(127, "Pinsir", ["C"], "National Park, Bug-Catching Contest"),
    d(128, "Tauros", ["C"], "Routes 38, 39"),
    d(129, "Magikarp", ["C"], "Fishing (everywhere), gift from Route 32 Pokemon Center"),
    d(130, "Gyarados", ["C"], "Lake of Rage (Red Gyarados Lv30), evolve Magikarp"),
    d(131, "Lapras", ["C"], "Union Cave B2F (Fridays only, Surf)"),
    d(132, "Ditto", ["C"], "Routes 34, 35"),
    d(133, "Eevee", ["C"], "Gift from Bill in Goldenrod City"),
    d(134, "Vaporeon", ["C"], "Evolve Eevee (Water Stone)"),
    d(135, "Jolteon", ["C"], "Evolve Eevee (Thunder Stone)"),
    d(136, "Flareon", ["C"], "Evolve Eevee (Fire Stone)"),
    d(137, "Porygon", ["C"], "Celadon Game Corner prize"),
    d(138, "Omanyte", ["C"], "Trade"),
    d(139, "Omastar", ["C"], "Evolve Omanyte"),
    d(140, "Kabuto", ["C"], "Trade"),
    d(141, "Kabutops", ["C"], "Evolve Kabuto"),
    d(142, "Aerodactyl", ["C"], "Trade"),
    d(143, "Snorlax", ["C"], "Route 11 (use Poke Flute from Kanto Radio Tower)"),
    d(144, "Articuno", ["C"], "Trade"),
    d(145, "Zapdos", ["C"], "Trade"),
    d(146, "Moltres", ["C"], "Trade"),
    d(147, "Dratini", ["C"], "Dragon's Den (Surf/Fishing), Goldenrod Game Corner prize"),
    d(148, "Dragonair", ["C"], "Dragon's Den (Fishing), evolve Dratini"),
    d(149, "Dragonite", ["C"], "Evolve Dragonair"),
    d(150, "Mewtwo", ["C"], "Trade"),
    d(151, "Mew", ["C"], "Event only"),

    // --- Gen II Pokemon ---

    // Johto starters
    d(152, "Chikorita", ["C"], "Starter from Prof. Elm"),
    d(153, "Bayleef", ["C"], "Evolve Chikorita"),
    d(154, "Meganium", ["C"], "Evolve Bayleef"),
    d(155, "Cyndaquil", ["C"], "Starter from Prof. Elm"),
    d(156, "Quilava", ["C"], "Evolve Cyndaquil"),
    d(157, "Typhlosion", ["C"], "Evolve Quilava"),
    d(158, "Totodile", ["C"], "Starter from Prof. Elm"),
    d(159, "Croconaw", ["C"], "Evolve Totodile"),
    d(160, "Feraligatr", ["C"], "Evolve Croconaw"),

    // Early Johto Pokemon
    d(161, "Sentret", ["C"], "Routes 1, 29"),
    d(162, "Furret", ["C"], "Route 1, evolve Sentret"),
    d(163, "Hoothoot", ["C"], "Routes 1, 2, 29, 30, 31, 35, 36, 37 (night)"),
    d(164, "Noctowl", ["C"], "Routes 8, 13, 14, 15, 37, 43, evolve Hoothoot"),
    d(165, "Ledyba", ["C"], "Routes 2, 30, 31, 37 (morning)"),
    d(166, "Ledian", ["C"], "Route 2, evolve Ledyba"),
    d(167, "Spinarak", ["C"], "Routes 2, 30, 31, 37 (night)"),
    d(168, "Ariados", ["C"], "Route 2, evolve Spinarak"),
    d(169, "Crobat", ["C"], "Evolve Golbat (friendship)"),
    d(170, "Chinchou", ["C"], "Routes 20, 21, 26, 27, New Bark Town (Fishing)"),
    d(171, "Lanturn", ["C"], "Evolve Chinchou"),
    d(172, "Pichu", ["C"], "Breed Pikachu"),
    d(173, "Cleffa", ["C"], "Breed Clefairy"),
    d(174, "Igglybuff", ["C"], "Breed Jigglypuff"),
    d(175, "Togepi", ["C"], "Gift Egg from Elm's aide (Route 32 Pokemon Center)"),
    d(176, "Togetic", ["C"], "Evolve Togepi (friendship)"),
    d(177, "Natu", ["C"], "Ruins of Alph"),
    d(178, "Xatu", ["C"], "Evolve Natu"),
    d(179, "Mareep", ["C"], "Routes 32, 42, 43"),
    d(180, "Flaaffy", ["C"], "Routes 42, 43, evolve Mareep"),
    d(181, "Ampharos", ["C"], "Evolve Flaaffy"),
    d(182, "Bellossom", ["C"], "Evolve Gloom (Sun Stone)"),
    d(183, "Marill", ["C"], "Mt. Mortar (Surf)"),
    d(184, "Azumarill", ["C"], "Evolve Marill"),
    d(185, "Sudowoodo", ["C"], "Route 36 (use SquirtBottle, one only)"),
    d(186, "Politoed", ["C"], "Evolve Poliwhirl (trade holding King's Rock)"),
    d(187, "Hoppip", ["C"], "Routes 13, 14, 32, 33"),
    d(188, "Skiploom", ["C"], "Routes 14, 15, evolve Hoppip"),
    d(189, "Jumpluff", ["C"], "Evolve Skiploom"),
    d(190, "Aipom", ["C"], "Routes 29, 30, 33, 42, 44, 46 (Headbutt trees)"),
    d(191, "Sunkern", ["C"], "Routes 24, 25, National Park"),
    d(192, "Sunflora", ["C"], "Evolve Sunkern (Sun Stone)"),
    d(193, "Yanma", ["C"], "Route 35"),
    d(194, "Wooper", ["C"], "Routes 32, 33 (night), Ruins of Alph"),
    d(195, "Quagsire", ["C"], "Routes 10, 12, 26, 27, 32 (Surf), evolve Wooper"),
    d(196, "Espeon", ["C"], "Evolve Eevee (friendship, daytime)"),
    d(197, "Umbreon", ["C"], "Evolve Eevee (friendship, nighttime)"),
    d(198, "Murkrow", ["C"], "Routes 7, 16 (night)"),
    d(199, "Slowking", ["C"], "Evolve Slowpoke (trade holding King's Rock)"),
    d(200, "Misdreavus", ["C"], "Mt. Silver, Silver Cave"),
    d(201, "Unown", ["C"], "Ruins of Alph (26 forms)"),
    d(202, "Wobbuffet", ["C"], "Dark Cave (Surf)"),
    d(203, "Girafarig", ["C"], "Routes 43"),
    d(204, "Pineco", ["C"], "Routes 26, 27, 34, 35, 36, 37, 38, 39 (Headbutt trees)"),
    d(205, "Forretress", ["C"], "Evolve Pineco"),
    d(206, "Dunsparce", ["C"], "Dark Cave"),
    d(207, "Gligar", ["C"], "Routes 45, 46"),
    d(208, "Steelix", ["C"], "Evolve Onix (trade holding Metal Coat)"),
    d(209, "Snubbull", ["C"], "Routes 38, 39"),
    d(210, "Granbull", ["C"], "Route 38, evolve Snubbull"),
    d(211, "Qwilfish", ["C"], "Routes 12, 13, 32 (Fishing)"),
    d(212, "Scizor", ["C"], "Evolve Scyther (trade holding Metal Coat)"),
    d(213, "Shuckle", ["C"], "Gift from man in Cianwood City"),
    d(214, "Heracross", ["C"], "Routes 29, 30, 31, 32, 33, 42, 43, 44, 46 (Headbutt trees)"),
    d(215, "Sneasel", ["C"], "Ice Path, Mt. Silver"),
    d(216, "Teddiursa", ["C"], "Routes 45, 46 (morning)"),
    d(217, "Ursaring", ["C"], "Routes 28, Victory Road, Mt. Silver, evolve Teddiursa"),
    d(218, "Slugma", ["C"], "Routes 16, 17, 18, Burned Tower"),
    d(219, "Magcargo", ["C"], "Evolve Slugma"),
    d(220, "Swinub", ["C"], "Ice Path"),
    d(221, "Piloswine", ["C"], "Evolve Swinub"),
    d(222, "Corsola", ["C"], "Cherrygrove City, Olivine City, Cianwood City (Fishing)"),
    d(223, "Remoraid", ["C"], "Route 44 (Fishing)"),
    d(224, "Octillery", ["C"], "Evolve Remoraid"),
    d(225, "Delibird", ["C"], "Ice Path"),
    d(226, "Mantine", ["C"], "Routes 40, 41 (Surf)"),
    d(227, "Skarmory", ["C"], "Route 45"),
    d(228, "Houndour", ["C"], "Routes 7, 8 (night)"),
    d(229, "Houndoom", ["C"], "Evolve Houndour"),
    d(230, "Kingdra", ["C"], "Evolve Seadra (trade holding Dragon Scale)"),
    d(231, "Phanpy", ["C"], "Routes 45, 46 (morning)"),
    d(232, "Donphan", ["C"], "Routes 26, 27, 28, Victory Road, Mt. Silver, evolve Phanpy"),
    d(233, "Porygon2", ["C"], "Evolve Porygon (trade holding Up-Grade)"),
    d(234, "Stantler", ["C"], "Routes 36, 37"),
    d(235, "Smeargle", ["C"], "Ruins of Alph"),
    d(236, "Tyrogue", ["C"], "Gift from Karate King in Mt. Mortar"),
    d(237, "Hitmontop", ["C"], "Evolve Tyrogue (Attack = Defense at Lv20)"),
    d(238, "Smoochum", ["C"], "Breed Jynx"),
    d(239, "Elekid", ["C"], "Breed Electabuzz"),
    d(240, "Magby", ["C"], "Breed Magmar, Odd Egg"),
    d(241, "Miltank", ["C"], "Routes 38, 39"),
    d(242, "Blissey", ["C"], "Evolve Chansey (friendship)"),
    d(243, "Raikou", ["C"], "Roaming Johto after Burned Tower event (Lv40)"),
    d(244, "Entei", ["C"], "Roaming Johto after Burned Tower event (Lv40)"),
    d(245, "Suicune", ["C"], "Tin Tower fixed encounter (Lv40, Crystal exclusive)"),
    d(246, "Larvitar", ["C"], "Mt. Silver"),
    d(247, "Pupitar", ["C"], "Mt. Silver, evolve Larvitar"),
    d(248, "Tyranitar", ["C"], "Evolve Pupitar"),
    d(249, "Lugia", ["C"], "Whirl Islands (Lv60, requires Silver Wing)"),
    d(250, "Ho-Oh", ["C"], "Tin Tower (Lv60, requires Rainbow Wing and Clear Bell)"),
    d(251, "Celebi", ["C"], "GS Ball event at Ilex Forest shrine"),
  ],
};
