import type { GameDex, GameDexEntry } from "../game-dex";

/* ── Helper ─────────────────────────────────────── */
const d = (
  pokemonId: number,
  name: string,
  versions: string[],
  method?: string
): GameDexEntry => ({ pokemonId, name, versions, method });

/* ══════════════════════════════════════════════════
 *  HeartGold & SoulSilver -- Johto + Kanto Pokedex
 *  All ~256 obtainable Pokemon (excluding event-only)
 * ══════════════════════════════════════════════════ */
export const HEARTGOLD_SOULSILVER_DEX: GameDex = {
  slug: "heartgold-soulsilver",
  versionTags: ["HG", "SS"],
  pokemon: [
    // ── Gen I: Kanto Pokemon ──────────────────────────────
    d(1, "Bulbasaur", ["HG", "SS"], "Gift from Steven Stone after defeating Red"),
    d(2, "Ivysaur", ["HG", "SS"], "Evolve Bulbasaur"),
    d(3, "Venusaur", ["HG", "SS"], "Evolve Ivysaur"),
    d(4, "Charmander", ["HG", "SS"], "Gift from Steven Stone after defeating Red"),
    d(5, "Charmeleon", ["HG", "SS"], "Evolve Charmander"),
    d(6, "Charizard", ["HG", "SS"], "Evolve Charmeleon"),
    d(7, "Squirtle", ["HG", "SS"], "Gift from Steven Stone after defeating Red"),
    d(8, "Wartortle", ["HG", "SS"], "Evolve Squirtle"),
    d(9, "Blastoise", ["HG", "SS"], "Evolve Wartortle"),
    d(10, "Caterpie", ["HG", "SS"], "Routes 30, 31, Ilex Forest, National Park, Bug-Catching Contest"),
    d(11, "Metapod", ["HG", "SS"], "Ilex Forest, National Park, Bug-Catching Contest, evolve Caterpie"),
    d(12, "Butterfree", ["HG", "SS"], "Bug-Catching Contest, evolve Metapod"),
    d(13, "Weedle", ["HG", "SS"], "Routes 30, 31, Ilex Forest, National Park, Bug-Catching Contest"),
    d(14, "Kakuna", ["HG", "SS"], "Ilex Forest, National Park, Bug-Catching Contest, evolve Weedle"),
    d(15, "Beedrill", ["HG", "SS"], "Bug-Catching Contest, evolve Kakuna"),
    d(16, "Pidgey", ["HG", "SS"], "Routes 1, 2, 5, 6, 29, 30, 31, 35, 36, 37"),
    d(17, "Pidgeotto", ["HG", "SS"], "Routes 37, 43, evolve Pidgey"),
    d(18, "Pidgeot", ["HG", "SS"], "Evolve Pidgeotto"),
    d(19, "Rattata", ["HG", "SS"], "Routes 1, 3, 4, 7, 9, 29, 32, 33, Union Cave, Sprout Tower"),
    d(20, "Raticate", ["HG", "SS"], "Routes 26, 27, 38, 39, 42, 47, evolve Rattata"),
    d(21, "Spearow", ["HG", "SS"], "Routes 3, 4, 9, 22, 42, 46"),
    d(22, "Fearow", ["HG", "SS"], "Routes 9, 10, 16, 17, 18, 22, evolve Spearow"),
    d(23, "Ekans", ["HG"], "Routes 3, 4, 32, 33, 42, Safari Zone"),
    d(24, "Arbok", ["HG"], "Routes 26, 27, Safari Zone, evolve Ekans"),
    d(25, "Pikachu", ["HG", "SS"], "Viridian Forest"),
    d(26, "Raichu", ["HG", "SS"], "Evolve Pikachu (Thunder Stone)"),
    d(27, "Sandshrew", ["HG", "SS"], "Union Cave, Mt. Moon, Route 3"),
    d(28, "Sandslash", ["HG", "SS"], "Routes 26, 27, evolve Sandshrew"),
    d(29, "Nidoran F", ["HG", "SS"], "Routes 35, 36, Safari Zone"),
    d(30, "Nidorina", ["HG", "SS"], "Routes 13, 14, 15, Safari Zone, evolve Nidoran F"),
    d(31, "Nidoqueen", ["HG", "SS"], "Evolve Nidorina (Moon Stone)"),
    d(32, "Nidoran M", ["HG", "SS"], "Routes 35, 36, Safari Zone"),
    d(33, "Nidorino", ["HG", "SS"], "Routes 13, 14, 15, Safari Zone, evolve Nidoran M"),
    d(34, "Nidoking", ["HG", "SS"], "Evolve Nidorino (Moon Stone)"),
    d(35, "Clefairy", ["HG", "SS"], "Mt. Moon"),
    d(36, "Clefable", ["HG", "SS"], "Evolve Clefairy (Moon Stone)"),
    d(37, "Vulpix", ["SS"], "Routes 7, 8, 36, 37, 48"),
    d(38, "Ninetales", ["SS"], "Evolve Vulpix (Fire Stone)"),
    d(39, "Jigglypuff", ["HG", "SS"], "Routes 3, 4, Safari Zone"),
    d(40, "Wigglytuff", ["HG", "SS"], "Evolve Jigglypuff (Moon Stone)"),
    d(41, "Zubat", ["HG", "SS"], "Dark Cave, Union Cave, Mt. Mortar, Whirl Islands, many caves"),
    d(42, "Golbat", ["HG", "SS"], "Victory Road, Ice Path, many caves, evolve Zubat"),
    d(43, "Oddish", ["HG", "SS"], "Ilex Forest, Routes 5, 6, 24, 25, Safari Zone"),
    d(44, "Gloom", ["HG", "SS"], "Routes 5, 24, 25, Safari Zone, evolve Oddish"),
    d(45, "Vileplume", ["HG", "SS"], "Evolve Gloom (Leaf Stone)"),
    d(46, "Paras", ["HG", "SS"], "Ilex Forest, Mt. Moon, Safari Zone, Bug-Catching Contest"),
    d(47, "Parasect", ["HG", "SS"], "Safari Zone, evolve Paras"),
    d(48, "Venonat", ["HG", "SS"], "Routes 24, 25, 43, National Park (Night)"),
    d(49, "Venomoth", ["HG", "SS"], "Routes 24, 25, Safari Zone, evolve Venonat"),
    d(50, "Diglett", ["HG", "SS"], "Diglett's Cave"),
    d(51, "Dugtrio", ["HG", "SS"], "Diglett's Cave, evolve Diglett"),
    d(52, "Meowth", ["SS"], "Routes 5, 6, 7, 8, 38, 39"),
    d(53, "Persian", ["SS"], "Evolve Meowth"),
    d(54, "Psyduck", ["HG", "SS"], "Routes 6, 35, Ilex Forest (Surf), Safari Zone"),
    d(55, "Golduck", ["HG", "SS"], "Safari Zone, Seafoam Islands, evolve Psyduck"),
    d(56, "Mankey", ["HG"], "Routes 9, 42, Safari Zone"),
    d(57, "Primeape", ["HG"], "Route 9, Safari Zone, evolve Mankey"),
    d(58, "Growlithe", ["HG"], "Routes 7, 8, 36, 37, 48"),
    d(59, "Arcanine", ["HG"], "Evolve Growlithe (Fire Stone)"),
    d(60, "Poliwag", ["HG", "SS"], "Routes 6, 22, 28, 30, 31, 44, Violet City (Fishing)"),
    d(61, "Poliwhirl", ["HG", "SS"], "Routes 30, 31, evolve Poliwag"),
    d(62, "Poliwrath", ["HG", "SS"], "Evolve Poliwhirl (Water Stone)"),
    d(63, "Abra", ["HG", "SS"], "Routes 5, 6, 34, 35, Goldenrod Game Corner"),
    d(64, "Kadabra", ["HG", "SS"], "Route 8, Cerulean Cave, evolve Abra"),
    d(65, "Alakazam", ["HG", "SS"], "Trade evolve Kadabra"),
    d(66, "Machop", ["HG", "SS"], "Mt. Mortar, Rock Tunnel, Cliff Cave"),
    d(67, "Machoke", ["HG", "SS"], "Mt. Mortar, Cliff Cave, evolve Machop"),
    d(68, "Machamp", ["HG", "SS"], "Trade evolve Machoke"),
    d(69, "Bellsprout", ["HG", "SS"], "Routes 5, 6, 24, 25, 31, 32, 44, Sprout Tower"),
    d(70, "Weepinbell", ["HG", "SS"], "Routes 24, 25, 44, evolve Bellsprout"),
    d(71, "Victreebel", ["HG", "SS"], "Evolve Weepinbell (Leaf Stone)"),
    d(72, "Tentacool", ["HG", "SS"], "Surfing (Routes 12, 13, 19, 20, 21, 26, 27, 32, 34, 40, 41)"),
    d(73, "Tentacruel", ["HG", "SS"], "Surfing (Routes 19, 20, 40, 41), evolve Tentacool"),
    d(74, "Geodude", ["HG", "SS"], "Dark Cave, Union Cave, Rock Tunnel, Mt. Mortar, Mt. Moon"),
    d(75, "Graveler", ["HG", "SS"], "Victory Road, Mt. Silver, Cerulean Cave, evolve Geodude"),
    d(76, "Golem", ["HG", "SS"], "Trade evolve Graveler"),
    d(77, "Ponyta", ["HG", "SS"], "Routes 22, 26, 27, 28, Mt. Silver"),
    d(78, "Rapidash", ["HG", "SS"], "Mt. Silver, evolve Ponyta"),
    d(79, "Slowpoke", ["HG", "SS"], "Slowpoke Well, Tohjo Falls, Seafoam Islands"),
    d(80, "Slowbro", ["HG", "SS"], "Seafoam Islands, evolve Slowpoke"),
    d(81, "Magnemite", ["HG", "SS"], "Routes 6, 11, 38, 39"),
    d(82, "Magneton", ["HG", "SS"], "Evolve Magnemite"),
    d(83, "Farfetch'd", ["HG", "SS"], "Routes 38, 39, Ilex Forest (event)"),
    d(84, "Doduo", ["HG", "SS"], "Routes 22, 26, 27, 28, Safari Zone"),
    d(85, "Dodrio", ["HG", "SS"], "Routes 26, 27, 28, evolve Doduo"),
    d(86, "Seel", ["HG", "SS"], "Whirl Islands, Seafoam Islands"),
    d(87, "Dewgong", ["HG", "SS"], "Seafoam Islands, evolve Seel"),
    d(88, "Grimer", ["HG", "SS"], "Routes 16, 17, 18, Celadon City"),
    d(89, "Muk", ["HG", "SS"], "Routes 16, 17, 18, Celadon City, evolve Grimer"),
    d(90, "Shellder", ["HG", "SS"], "Olivine City, Vermilion City, Route 20 (Fishing)"),
    d(91, "Cloyster", ["HG", "SS"], "Evolve Shellder (Water Stone)"),
    d(92, "Gastly", ["HG", "SS"], "Sprout Tower, Burned Tower, Route 31 (Night)"),
    d(93, "Haunter", ["HG", "SS"], "Safari Zone, evolve Gastly"),
    d(94, "Gengar", ["HG", "SS"], "Trade evolve Haunter"),
    d(95, "Onix", ["HG", "SS"], "Union Cave, Rock Tunnel, Victory Road, Mt. Silver"),
    d(96, "Drowzee", ["HG", "SS"], "Routes 11, 34, 35"),
    d(97, "Hypno", ["HG", "SS"], "Route 11, evolve Drowzee"),
    d(98, "Krabby", ["HG", "SS"], "Olivine City, Cherrygrove City, Route 19 (Fishing)"),
    d(99, "Kingler", ["HG", "SS"], "Seafoam Islands, evolve Krabby"),
    d(100, "Voltorb", ["HG", "SS"], "Route 10, Team Rocket HQ"),
    d(101, "Electrode", ["HG", "SS"], "Team Rocket HQ, evolve Voltorb"),
    d(102, "Exeggcute", ["HG", "SS"], "Headbutt trees (Viridian Forest, Ilex Forest)"),
    d(103, "Exeggutor", ["HG", "SS"], "Evolve Exeggcute (Leaf Stone)"),
    d(104, "Cubone", ["HG", "SS"], "Rock Tunnel, Safari Zone"),
    d(105, "Marowak", ["HG", "SS"], "Safari Zone, evolve Cubone"),
    d(106, "Hitmonlee", ["HG", "SS"], "Evolve Tyrogue (Atk > Def at Lv. 20)"),
    d(107, "Hitmonchan", ["HG", "SS"], "Evolve Tyrogue (Def > Atk at Lv. 20)"),
    d(108, "Lickitung", ["HG", "SS"], "Route 44, Safari Zone"),
    d(109, "Koffing", ["HG", "SS"], "Burned Tower, Team Rocket HQ"),
    d(110, "Weezing", ["HG", "SS"], "Evolve Koffing"),
    d(111, "Rhyhorn", ["HG", "SS"], "Victory Road, Safari Zone"),
    d(112, "Rhydon", ["HG", "SS"], "Evolve Rhyhorn"),
    d(113, "Chansey", ["HG", "SS"], "Routes 13, 14, 15, Safari Zone (rare)"),
    d(114, "Tangela", ["HG", "SS"], "Route 44, Mt. Silver, Safari Zone"),
    d(115, "Kangaskhan", ["HG", "SS"], "Safari Zone (rare, Rock + Peak blocks)"),
    d(116, "Horsea", ["HG", "SS"], "Whirl Islands (Fishing)"),
    d(117, "Seadra", ["HG", "SS"], "Whirl Islands (Fishing), evolve Horsea"),
    d(118, "Goldeen", ["HG", "SS"], "Many locations (Fishing)"),
    d(119, "Seaking", ["HG", "SS"], "Evolve Goldeen"),
    d(120, "Staryu", ["HG", "SS"], "Cherrygrove City, Olivine City, Cianwood City (Fishing, Night)"),
    d(121, "Starmie", ["HG", "SS"], "Evolve Staryu (Water Stone)"),
    d(122, "Mr. Mime", ["HG", "SS"], "Route 21, Safari Zone"),
    d(123, "Scyther", ["HG", "SS"], "Bug-Catching Contest, Safari Zone"),
    d(124, "Jynx", ["HG", "SS"], "Ice Path, Seafoam Islands"),
    d(125, "Electabuzz", ["HG", "SS"], "Route 10, Safari Zone"),
    d(126, "Magmar", ["HG"], "Burned Tower, Safari Zone"),
    d(127, "Pinsir", ["HG", "SS"], "Bug-Catching Contest, Safari Zone"),
    d(128, "Tauros", ["HG", "SS"], "Routes 38, 39, Safari Zone"),
    d(129, "Magikarp", ["HG", "SS"], "Fishing (everywhere), Lake of Rage"),
    d(130, "Gyarados", ["HG", "SS"], "Lake of Rage (Red Gyarados Lv. 30), evolve Magikarp"),
    d(131, "Lapras", ["HG", "SS"], "Union Cave B2F (Fridays only)"),
    d(132, "Ditto", ["HG", "SS"], "Routes 34, 35, 47"),
    d(133, "Eevee", ["HG", "SS"], "Gift from Bill in Goldenrod City"),
    d(134, "Vaporeon", ["HG", "SS"], "Evolve Eevee (Water Stone)"),
    d(135, "Jolteon", ["HG", "SS"], "Evolve Eevee (Thunder Stone)"),
    d(136, "Flareon", ["HG", "SS"], "Evolve Eevee (Fire Stone)"),
    d(137, "Porygon", ["HG", "SS"], "Goldenrod Game Corner prize (9999 coins)"),
    d(138, "Omanyte", ["HG", "SS"], "Revive Helix Fossil (Ruins of Alph)"),
    d(139, "Omastar", ["HG", "SS"], "Evolve Omanyte"),
    d(140, "Kabuto", ["HG", "SS"], "Revive Dome Fossil (Ruins of Alph)"),
    d(141, "Kabutops", ["HG", "SS"], "Evolve Kabuto"),
    d(142, "Aerodactyl", ["HG", "SS"], "Revive Old Amber (Ruins of Alph)"),
    d(143, "Snorlax", ["HG", "SS"], "Route 11 (use Poke Flute Channel on Pokegear, Lv. 50)"),
    d(144, "Articuno", ["HG", "SS"], "Seafoam Islands (Lv. 50, post-game)"),
    d(145, "Zapdos", ["HG", "SS"], "Route 10 outside Power Plant (Lv. 50, post-game)"),
    d(146, "Moltres", ["HG", "SS"], "Mt. Silver exterior (Lv. 50, post-game)"),
    d(147, "Dratini", ["HG", "SS"], "Dragon's Den (Fishing, Surfing), Gift from Dragon Master"),
    d(148, "Dragonair", ["HG", "SS"], "Dragon's Den (Super Rod), evolve Dratini"),
    d(149, "Dragonite", ["HG", "SS"], "Evolve Dragonair"),
    d(150, "Mewtwo", ["HG", "SS"], "Cerulean Cave (Lv. 70, post-game, all 16 badges)"),
    d(151, "Mew", ["HG", "SS"], "Event only (Wi-Fi event)"),

    // ── Gen II: Johto Pokemon ──────────────────────────────
    d(152, "Chikorita", ["HG", "SS"], "Starter from Professor Elm"),
    d(153, "Bayleef", ["HG", "SS"], "Evolve Chikorita"),
    d(154, "Meganium", ["HG", "SS"], "Evolve Bayleef"),
    d(155, "Cyndaquil", ["HG", "SS"], "Starter from Professor Elm"),
    d(156, "Quilava", ["HG", "SS"], "Evolve Cyndaquil"),
    d(157, "Typhlosion", ["HG", "SS"], "Evolve Quilava"),
    d(158, "Totodile", ["HG", "SS"], "Starter from Professor Elm"),
    d(159, "Croconaw", ["HG", "SS"], "Evolve Totodile"),
    d(160, "Feraligatr", ["HG", "SS"], "Evolve Croconaw"),
    d(161, "Sentret", ["HG", "SS"], "Routes 1, 29"),
    d(162, "Furret", ["HG", "SS"], "Routes 1, 43, evolve Sentret"),
    d(163, "Hoothoot", ["HG", "SS"], "Routes 1, 2, 29, 30, 31, 35, 36, 37, National Park (Night)"),
    d(164, "Noctowl", ["HG", "SS"], "Routes 8, 13, 43, evolve Hoothoot"),
    d(165, "Ledyba", ["SS"], "Routes 2, 30, 31, 37, National Park (Morning)"),
    d(166, "Ledian", ["SS"], "Route 2, evolve Ledyba"),
    d(167, "Spinarak", ["HG"], "Routes 2, 30, 31, 37, National Park (Night)"),
    d(168, "Ariados", ["HG"], "Route 2, evolve Spinarak"),
    d(169, "Crobat", ["HG", "SS"], "Evolve Golbat (friendship)"),
    d(170, "Chinchou", ["HG", "SS"], "Routes 20, 21, 27, 41 (Fishing)"),
    d(171, "Lanturn", ["HG", "SS"], "Evolve Chinchou"),
    d(172, "Pichu", ["HG", "SS"], "Breed Pikachu/Raichu"),
    d(173, "Cleffa", ["HG", "SS"], "Breed Clefairy/Clefable"),
    d(174, "Igglybuff", ["HG", "SS"], "Breed Jigglypuff/Wigglytuff"),
    d(175, "Togepi", ["HG", "SS"], "Hatch from Mystery Egg from Professor Elm"),
    d(176, "Togetic", ["HG", "SS"], "Evolve Togepi (friendship)"),
    d(177, "Natu", ["HG", "SS"], "Ruins of Alph, Safari Zone"),
    d(178, "Xatu", ["HG", "SS"], "Safari Zone, evolve Natu"),
    d(179, "Mareep", ["HG", "SS"], "Routes 32, 42, 43, Safari Zone"),
    d(180, "Flaaffy", ["HG", "SS"], "Routes 42, 43, evolve Mareep"),
    d(181, "Ampharos", ["HG", "SS"], "Evolve Flaaffy"),
    d(182, "Bellossom", ["HG", "SS"], "Evolve Gloom (Sun Stone)"),
    d(183, "Marill", ["HG", "SS"], "Mt. Mortar, Safari Zone"),
    d(184, "Azumarill", ["HG", "SS"], "Evolve Marill"),
    d(185, "Sudowoodo", ["HG", "SS"], "Route 36 (use SquirtBottle, Lv. 20)"),
    d(186, "Politoed", ["HG", "SS"], "Trade evolve Poliwhirl (hold King's Rock)"),
    d(187, "Hoppip", ["HG", "SS"], "Routes 32, 33, 48"),
    d(188, "Skiploom", ["HG", "SS"], "Route 14, evolve Hoppip"),
    d(189, "Jumpluff", ["HG", "SS"], "Evolve Skiploom"),
    d(190, "Aipom", ["HG", "SS"], "Headbutt trees (Routes 33, 42, 44, Azalea Town)"),
    d(191, "Sunkern", ["HG", "SS"], "Routes 24, National Park (Morning)"),
    d(192, "Sunflora", ["HG", "SS"], "Evolve Sunkern (Sun Stone)"),
    d(193, "Yanma", ["HG", "SS"], "Route 35, Safari Zone"),
    d(194, "Wooper", ["HG", "SS"], "Routes 32, Ruins of Alph, Union Cave (Night)"),
    d(195, "Quagsire", ["HG", "SS"], "Routes 10, 12, 13, 26, 27, Ruins of Alph, evolve Wooper"),
    d(196, "Espeon", ["HG", "SS"], "Evolve Eevee (friendship, Day)"),
    d(197, "Umbreon", ["HG", "SS"], "Evolve Eevee (friendship, Night)"),
    d(198, "Murkrow", ["HG", "SS"], "Safari Zone, Routes 7, 16 (Night)"),
    d(199, "Slowking", ["HG", "SS"], "Trade evolve Slowpoke (hold King's Rock)"),
    d(200, "Misdreavus", ["HG", "SS"], "Safari Zone, Mt. Silver (Night)"),
    d(201, "Unown", ["HG", "SS"], "Ruins of Alph (26 forms + ! and ?)"),
    d(202, "Wobbuffet", ["HG", "SS"], "Dark Cave, Cerulean Cave, Safari Zone"),
    d(203, "Girafarig", ["HG", "SS"], "Route 43, Safari Zone"),
    d(204, "Pineco", ["HG", "SS"], "Headbutt trees (Ilex Forest, Route 3, many locations)"),
    d(205, "Forretress", ["HG", "SS"], "Evolve Pineco"),
    d(206, "Dunsparce", ["HG", "SS"], "Dark Cave"),
    d(207, "Gligar", ["HG"], "Route 45, Safari Zone"),
    d(208, "Steelix", ["HG", "SS"], "Trade evolve Onix (hold Metal Coat), Cliff Edge Gate"),
    d(209, "Snubbull", ["HG", "SS"], "Routes 38, 39, Safari Zone"),
    d(210, "Granbull", ["HG", "SS"], "Route 48, Safari Zone, evolve Snubbull"),
    d(211, "Qwilfish", ["HG", "SS"], "Routes 12, 13, 32 (Fishing)"),
    d(212, "Scizor", ["HG", "SS"], "Trade evolve Scyther (hold Metal Coat)"),
    d(213, "Shuckle", ["HG", "SS"], "Gift from man in Cianwood City, Safari Zone"),
    d(214, "Heracross", ["HG", "SS"], "Headbutt trees (Routes 33, 42, 44, Azalea Town)"),
    d(215, "Sneasel", ["HG", "SS"], "Route 28, Mt. Silver, Ice Path (Night)"),
    d(216, "Teddiursa", ["SS"], "Routes 45, 46, Mt. Silver"),
    d(217, "Ursaring", ["SS"], "Routes 28, Mt. Silver, evolve Teddiursa"),
    d(218, "Slugma", ["HG", "SS"], "Kanto Route 16, 17, 18, Safari Zone"),
    d(219, "Magcargo", ["HG", "SS"], "Safari Zone, evolve Slugma"),
    d(220, "Swinub", ["HG", "SS"], "Ice Path"),
    d(221, "Piloswine", ["HG", "SS"], "Evolve Swinub"),
    d(222, "Corsola", ["HG", "SS"], "Cianwood City, Cherrygrove City, Olivine City (Fishing)"),
    d(223, "Remoraid", ["HG", "SS"], "Routes 44, Route 41 (Fishing)"),
    d(224, "Octillery", ["HG", "SS"], "Evolve Remoraid"),
    d(225, "Delibird", ["SS"], "Ice Path"),
    d(226, "Mantine", ["HG"], "Routes 40, 41 (Surfing)"),
    d(227, "Skarmory", ["SS"], "Route 45, Safari Zone"),
    d(228, "Houndour", ["HG", "SS"], "Route 7 (Night), Safari Zone"),
    d(229, "Houndoom", ["HG", "SS"], "Safari Zone, evolve Houndour"),
    d(230, "Kingdra", ["HG", "SS"], "Trade evolve Seadra (hold Dragon Scale)"),
    d(231, "Phanpy", ["HG", "SS"], "Route 45, Safari Zone"),
    d(232, "Donphan", ["HG", "SS"], "Routes 28, Victory Road, Mt. Silver, evolve Phanpy"),
    d(233, "Porygon2", ["HG", "SS"], "Trade evolve Porygon (hold Up-Grade)"),
    d(234, "Stantler", ["HG", "SS"], "Routes 36, 37, Safari Zone"),
    d(235, "Smeargle", ["HG", "SS"], "Ruins of Alph, Safari Zone"),
    d(236, "Tyrogue", ["HG", "SS"], "Gift from Karate King in Mt. Mortar"),
    d(237, "Hitmontop", ["HG", "SS"], "Evolve Tyrogue (Atk = Def at Lv. 20)"),
    d(238, "Smoochum", ["HG", "SS"], "Breed Jynx"),
    d(239, "Elekid", ["HG", "SS"], "Breed Electabuzz"),
    d(240, "Magby", ["HG", "SS"], "Breed Magmar"),
    d(241, "Miltank", ["HG", "SS"], "Routes 38, 39, Safari Zone"),
    d(242, "Blissey", ["HG", "SS"], "Evolve Chansey (friendship)"),
    d(243, "Raikou", ["HG", "SS"], "Roaming Johto after Burned Tower event (Lv. 40)"),
    d(244, "Entei", ["HG", "SS"], "Roaming Johto after Burned Tower event (Lv. 40)"),
    d(245, "Suicune", ["HG", "SS"], "Route 25 (HG) / Bell Tower (SS) after Burned Tower event (Lv. 40)"),
    d(246, "Larvitar", ["HG", "SS"], "Mt. Silver, Safari Zone"),
    d(247, "Pupitar", ["HG", "SS"], "Mt. Silver, evolve Larvitar"),
    d(248, "Tyranitar", ["HG", "SS"], "Evolve Pupitar"),
    d(249, "Lugia", ["HG", "SS"], "Whirl Islands -- Lv. 45 story (SS) / Lv. 70 post-game (HG)"),
    d(250, "Ho-Oh", ["HG", "SS"], "Bell Tower -- Lv. 45 story (HG) / Lv. 70 post-game (SS)"),
    d(251, "Celebi", ["HG", "SS"], "Event only (Fateful Encounter)"),

    // ── Gen III Pokemon obtainable in HGSS ──────────────────
    d(261, "Poochyena", ["HG", "SS"], "Safari Zone (Swamp)"),
    d(262, "Mightyena", ["HG", "SS"], "Evolve Poochyena"),
    d(263, "Zigzagoon", ["HG", "SS"], "Safari Zone (Meadow)"),
    d(264, "Linoone", ["HG", "SS"], "Evolve Zigzagoon"),
    d(270, "Lotad", ["HG", "SS"], "Safari Zone (Wetland)"),
    d(271, "Lombre", ["HG", "SS"], "Evolve Lotad"),
    d(272, "Ludicolo", ["HG", "SS"], "Evolve Lombre (Water Stone)"),
    d(278, "Wingull", ["HG", "SS"], "Vermilion City (Surf)"),
    d(279, "Pelipper", ["HG", "SS"], "Evolve Wingull"),
    d(280, "Ralts", ["HG", "SS"], "Safari Zone (Forest)"),
    d(281, "Kirlia", ["HG", "SS"], "Evolve Ralts"),
    d(282, "Gardevoir", ["HG", "SS"], "Evolve Kirlia"),
    d(283, "Surskit", ["HG", "SS"], "Safari Zone (Wetland)"),
    d(284, "Masquerain", ["HG", "SS"], "Evolve Surskit"),
    d(285, "Shroomish", ["HG", "SS"], "Safari Zone (Forest)"),
    d(286, "Breloom", ["HG", "SS"], "Evolve Shroomish"),
    d(293, "Whismur", ["HG", "SS"], "Safari Zone (Forest)"),
    d(294, "Loudred", ["HG", "SS"], "Evolve Whismur"),
    d(295, "Exploud", ["HG", "SS"], "Evolve Loudred"),
    d(298, "Azurill", ["HG", "SS"], "Breed Marill/Azumarill (hold Sea Incense)"),
    d(299, "Nosepass", ["HG", "SS"], "Safari Zone (Rocky Beach)"),
    d(302, "Sableye", ["HG", "SS"], "Safari Zone (Forest, Night blocks)"),
    d(304, "Aron", ["HG", "SS"], "Safari Zone (Mountain)"),
    d(305, "Lairon", ["HG", "SS"], "Evolve Aron"),
    d(306, "Aggron", ["HG", "SS"], "Evolve Lairon"),
    d(307, "Meditite", ["HG", "SS"], "Safari Zone (Wasteland)"),
    d(308, "Medicham", ["HG", "SS"], "Evolve Meditite"),
    d(309, "Electrike", ["HG", "SS"], "Safari Zone (Plains)"),
    d(310, "Manectric", ["HG", "SS"], "Evolve Electrike"),
    d(311, "Plusle", ["HG", "SS"], "Safari Zone (Plains)"),
    d(312, "Minun", ["HG", "SS"], "Safari Zone (Plains)"),
    d(314, "Illumise", ["HG", "SS"], "Safari Zone (Forest)"),
    d(315, "Roselia", ["HG", "SS"], "Safari Zone (Plains)"),
    d(316, "Gulpin", ["HG", "SS"], "Safari Zone (Wetland)"),
    d(317, "Swalot", ["HG", "SS"], "Evolve Gulpin"),
    d(318, "Carvanha", ["HG", "SS"], "Safari Zone (Wetland, Fishing)"),
    d(319, "Sharpedo", ["HG", "SS"], "Evolve Carvanha"),
    d(322, "Numel", ["HG", "SS"], "Safari Zone (Rocky Beach)"),
    d(323, "Camerupt", ["HG", "SS"], "Evolve Numel"),
    d(324, "Torkoal", ["HG", "SS"], "Safari Zone (Wasteland)"),
    d(325, "Spoink", ["HG", "SS"], "Safari Zone (Meadow)"),
    d(326, "Grumpig", ["HG", "SS"], "Evolve Spoink"),
    d(327, "Spinda", ["HG", "SS"], "Safari Zone (Meadow)"),
    d(328, "Trapinch", ["HG", "SS"], "Safari Zone (Desert)"),
    d(329, "Vibrava", ["HG", "SS"], "Evolve Trapinch"),
    d(330, "Flygon", ["HG", "SS"], "Evolve Vibrava"),
    d(331, "Cacnea", ["HG", "SS"], "Safari Zone (Desert)"),
    d(332, "Cacturne", ["HG", "SS"], "Evolve Cacnea"),
    d(339, "Barboach", ["HG", "SS"], "Safari Zone (Wetland, Fishing)"),
    d(340, "Whiscash", ["HG", "SS"], "Evolve Barboach"),
    d(341, "Corphish", ["HG", "SS"], "Safari Zone (Wetland, Fishing)"),
    d(342, "Crawdaunt", ["HG", "SS"], "Evolve Corphish"),
    d(349, "Feebas", ["HG", "SS"], "Safari Zone (Wetland, Fishing, 10+ Water blocks)"),
    d(350, "Milotic", ["HG", "SS"], "Evolve Feebas (max Beauty or trade with Prism Scale)"),
    d(351, "Castform", ["HG", "SS"], "Safari Zone (Forest)"),
    d(352, "Kecleon", ["HG", "SS"], "Safari Zone (Forest)"),
    d(353, "Shuppet", ["HG", "SS"], "Safari Zone (Forest, Night blocks)"),
    d(354, "Banette", ["HG", "SS"], "Evolve Shuppet"),
    d(355, "Duskull", ["HG", "SS"], "Safari Zone (Forest, Night blocks)"),
    d(356, "Dusclops", ["HG", "SS"], "Evolve Duskull"),
    d(357, "Tropius", ["HG", "SS"], "Safari Zone (Plains)"),
    d(359, "Absol", ["HG", "SS"], "Safari Zone (Mountain)"),
    d(361, "Snorunt", ["HG", "SS"], "Safari Zone (Mountain, Ice blocks)"),
    d(362, "Glalie", ["HG", "SS"], "Evolve Snorunt"),
    d(363, "Spheal", ["HG", "SS"], "Safari Zone (Rocky Beach)"),
    d(364, "Sealeo", ["HG", "SS"], "Evolve Spheal"),
    d(365, "Walrein", ["HG", "SS"], "Evolve Sealeo"),
    d(369, "Relicanth", ["HG", "SS"], "Safari Zone (Wetland, Fishing)"),
    d(370, "Luvdisc", ["HG", "SS"], "Route 27 (Fishing)"),
    d(371, "Bagon", ["HG", "SS"], "Safari Zone (Wetland, 21+ blocks)"),
    d(372, "Shelgon", ["HG", "SS"], "Evolve Bagon"),
    d(373, "Salamence", ["HG", "SS"], "Evolve Shelgon"),
    d(374, "Beldum", ["HG", "SS"], "Safari Zone (Mountain, 21+ blocks)"),
    d(375, "Metang", ["HG", "SS"], "Evolve Beldum"),
    d(376, "Metagross", ["HG", "SS"], "Evolve Metang"),

    // ── Gen III Legendaries obtainable in HGSS ──────────────
    d(380, "Latias", ["HG"], "Roaming Kanto after National Dex (Lv. 35)"),
    d(381, "Latios", ["SS"], "Roaming Kanto after National Dex (Lv. 35)"),
    d(382, "Kyogre", ["HG"], "Embedded Tower (after obtaining Blue Orb from Mr. Pokemon, Lv. 50)"),
    d(383, "Groudon", ["SS"], "Embedded Tower (after obtaining Red Orb from Mr. Pokemon, Lv. 50)"),
    d(384, "Rayquaza", ["HG", "SS"], "Embedded Tower (need both Kyogre and Groudon, Lv. 50)"),

    // ── Gen IV Pokemon obtainable in HGSS ──────────────────
    d(387, "Turtwig", ["HG", "SS"], "Gift from Steven Stone after defeating Red"),
    d(388, "Grotle", ["HG", "SS"], "Evolve Turtwig"),
    d(389, "Torterra", ["HG", "SS"], "Evolve Grotle"),
    d(390, "Chimchar", ["HG", "SS"], "Gift from Steven Stone after defeating Red"),
    d(391, "Monferno", ["HG", "SS"], "Evolve Chimchar"),
    d(392, "Infernape", ["HG", "SS"], "Evolve Monferno"),
    d(393, "Piplup", ["HG", "SS"], "Gift from Steven Stone after defeating Red"),
    d(394, "Prinplup", ["HG", "SS"], "Evolve Piplup"),
    d(395, "Empoleon", ["HG", "SS"], "Evolve Prinplup"),
    d(399, "Bidoof", ["HG", "SS"], "Safari Zone (Wetland)"),
    d(400, "Bibarel", ["HG", "SS"], "Evolve Bidoof"),
    d(403, "Shinx", ["HG", "SS"], "Safari Zone (Plains)"),
    d(404, "Luxio", ["HG", "SS"], "Evolve Shinx"),
    d(405, "Luxray", ["HG", "SS"], "Evolve Luxio"),
    d(406, "Budew", ["HG", "SS"], "Breed Roselia (hold Rose Incense)"),
    d(407, "Roserade", ["HG", "SS"], "Evolve Roselia (Shiny Stone)"),
    d(412, "Burmy", ["HG", "SS"], "Headbutt trees (National Park, various)"),
    d(413, "Wormadam", ["HG", "SS"], "Evolve female Burmy"),
    d(414, "Mothim", ["HG", "SS"], "Evolve male Burmy"),
    d(418, "Buizel", ["HG", "SS"], "Safari Zone (Wetland)"),
    d(419, "Floatzel", ["HG", "SS"], "Evolve Buizel"),
    d(427, "Buneary", ["HG", "SS"], "Safari Zone (Plains)"),
    d(428, "Lopunny", ["HG", "SS"], "Evolve Buneary (friendship)"),
    d(430, "Honchkrow", ["HG", "SS"], "Evolve Murkrow (Dusk Stone)"),
    d(431, "Glameow", ["HG", "SS"], "Safari Zone (Plains)"),
    d(432, "Purugly", ["HG", "SS"], "Evolve Glameow"),
    d(434, "Stunky", ["HG", "SS"], "Safari Zone (Forest)"),
    d(435, "Skuntank", ["HG", "SS"], "Evolve Stunky"),
    d(436, "Bronzor", ["HG", "SS"], "Safari Zone (Wasteland)"),
    d(437, "Bronzong", ["HG", "SS"], "Evolve Bronzor"),
    d(438, "Bonsly", ["HG", "SS"], "Breed Sudowoodo (hold Rock Incense)"),
    d(439, "Mime Jr.", ["HG", "SS"], "Breed Mr. Mime (hold Odd Incense)"),
    d(440, "Happiny", ["HG", "SS"], "Breed Chansey/Blissey (hold Luck Incense)"),
    d(446, "Munchlax", ["HG", "SS"], "Headbutt special trees (rare), breed Snorlax (hold Full Incense)"),
    d(447, "Riolu", ["HG", "SS"], "Safari Zone (Meadow)"),
    d(448, "Lucario", ["HG", "SS"], "Evolve Riolu (friendship, Day)"),
    d(451, "Skorupi", ["HG", "SS"], "Safari Zone (Wasteland)"),
    d(452, "Drapion", ["HG", "SS"], "Evolve Skorupi"),
    d(453, "Croagunk", ["HG", "SS"], "Safari Zone (Wetland)"),
    d(454, "Toxicroak", ["HG", "SS"], "Evolve Croagunk"),
    d(456, "Finneon", ["HG", "SS"], "Safari Zone (Wetland, Fishing)"),
    d(457, "Lumineon", ["HG", "SS"], "Evolve Finneon"),
    d(459, "Snover", ["HG", "SS"], "Safari Zone (Mountain, Ice blocks)"),
    d(460, "Abomasnow", ["HG", "SS"], "Evolve Snover"),
    d(461, "Weavile", ["HG", "SS"], "Evolve Sneasel (hold Razor Claw, Night)"),
    d(462, "Magnezone", ["HG", "SS"], "Evolve Magneton (level up at Mt. Coronet in DPPt, or trade)"),
    d(463, "Lickilicky", ["HG", "SS"], "Evolve Lickitung (learn Rollout)"),
    d(464, "Rhyperior", ["HG", "SS"], "Trade evolve Rhydon (hold Protector)"),
    d(465, "Tangrowth", ["HG", "SS"], "Evolve Tangela (learn AncientPower)"),
    d(466, "Electivire", ["HG", "SS"], "Trade evolve Electabuzz (hold Electirizer)"),
    d(467, "Magmortar", ["HG", "SS"], "Trade evolve Magmar (hold Magmarizer)"),
    d(468, "Togekiss", ["HG", "SS"], "Evolve Togetic (Shiny Stone)"),
    d(469, "Yanmega", ["HG", "SS"], "Evolve Yanma (learn AncientPower)"),
    d(470, "Leafeon", ["HG", "SS"], "Evolve Eevee (level up near Moss Rock in Eterna Forest in DPPt, or trade)"),
    d(471, "Glaceon", ["HG", "SS"], "Evolve Eevee (level up near Ice Rock in Route 217 in DPPt, or trade)"),
    d(472, "Gliscor", ["HG", "SS"], "Evolve Gligar (hold Razor Fang, Night)"),
    d(473, "Mamoswine", ["HG", "SS"], "Evolve Piloswine (learn AncientPower)"),
    d(474, "Porygon-Z", ["HG", "SS"], "Trade evolve Porygon2 (hold Dubious Disc)"),
    d(475, "Gallade", ["HG", "SS"], "Evolve male Kirlia (Dawn Stone)"),
    d(476, "Probopass", ["HG", "SS"], "Evolve Nosepass (level up at Mt. Coronet in DPPt, or trade)"),
    d(477, "Dusknoir", ["HG", "SS"], "Trade evolve Dusclops (hold Reaper Cloth)"),
    d(478, "Froslass", ["HG", "SS"], "Evolve female Snorunt (Dawn Stone)"),
  ],
};
