import type { GameDex, GameDexEntry } from "../game-dex";

const d = (
  pokemonId: number,
  name: string,
  versions: string[],
  method?: string
): GameDexEntry => ({ pokemonId, name, versions, method });

/* ==============================================================
 *  Pokemon Scarlet & Violet -- Paldea Pokedex (~400 Pokemon)
 *  Version tags: Sc = Scarlet, Vi = Violet
 *  Includes all obtainable Pokemon in the base game Paldea dex.
 * ============================================================== */
export const SCARLET_VIOLET_DEX: GameDex = {
  slug: "scarlet-violet",
  versionTags: ["Sc", "Vi"],
  pokemon: [
    // ── Starters & Evolutions ──────────────────────────────────
    d(906, "Sprigatito", ["Sc", "Vi"], "Starter from Director Clavell"),
    d(907, "Floragato", ["Sc", "Vi"], "Evolve Sprigatito"),
    d(908, "Meowscarada", ["Sc", "Vi"], "Evolve Floragato"),
    d(909, "Fuecoco", ["Sc", "Vi"], "Starter from Director Clavell"),
    d(910, "Crocalor", ["Sc", "Vi"], "Evolve Fuecoco"),
    d(911, "Skeledirge", ["Sc", "Vi"], "Evolve Crocalor"),
    d(912, "Quaxly", ["Sc", "Vi"], "Starter from Director Clavell"),
    d(913, "Quaxwell", ["Sc", "Vi"], "Evolve Quaxly"),
    d(914, "Quaquaval", ["Sc", "Vi"], "Evolve Quaxwell"),

    // ── Early-route Pokemon ────────────────────────────────────
    d(915, "Lechonk", ["Sc", "Vi"], "South Province (Areas One-Five), Los Platos"),
    d(916, "Oinkologne", ["Sc", "Vi"], "Evolve Lechonk"),
    d(917, "Tarountula", ["Sc", "Vi"], "South Province (Area One), Cabo Poco"),
    d(918, "Spidops", ["Sc", "Vi"], "Evolve Tarountula"),
    d(919, "Nymble", ["Sc", "Vi"], "South Province (Areas One-Three)"),
    d(920, "Lokix", ["Sc", "Vi"], "Evolve Nymble"),
    d(921, "Pawmi", ["Sc", "Vi"], "South Province (Areas One-Two), Cabo Poco"),
    d(922, "Pawmo", ["Sc", "Vi"], "Evolve Pawmi"),
    d(923, "Pawmot", ["Sc", "Vi"], "Evolve Pawmo (walk 1000 steps in Let's Go)"),
    d(924, "Tandemaus", ["Sc", "Vi"], "South Province (Area Two), Porto Marinada"),
    d(925, "Maushold", ["Sc", "Vi"], "Evolve Tandemaus (level up in battle)"),
    d(926, "Fidough", ["Sc", "Vi"], "South Province (Areas One-Two), Mesagoza"),
    d(927, "Dachsbun", ["Sc", "Vi"], "Evolve Fidough"),
    d(928, "Smoliv", ["Sc", "Vi"], "South Province (Areas One-Three), Cortondo"),
    d(929, "Dolliv", ["Sc", "Vi"], "Evolve Smoliv"),
    d(930, "Arboliva", ["Sc", "Vi"], "Evolve Dolliv"),
    d(931, "Squawkabilly", ["Sc", "Vi"], "Mesagoza, Levincia, various cities"),
    d(932, "Nacli", ["Sc", "Vi"], "South Province (Area Three), East Province"),
    d(933, "Naclstack", ["Sc", "Vi"], "Evolve Nacli"),
    d(934, "Garganacl", ["Sc", "Vi"], "Evolve Naclstack"),
    d(935, "Charcadet", ["Sc", "Vi"], "South Province (Area Five), West Province"),
    d(936, "Armarouge", ["Sc"], "Evolve Charcadet (Auspicious Armor from Zapapico NPC)"),
    d(937, "Ceruledge", ["Vi"], "Evolve Charcadet (Malicious Armor from Zapapico NPC)"),
    d(938, "Tadbulb", ["Sc", "Vi"], "South Province (Area Two-Four), near water"),
    d(939, "Bellibolt", ["Sc", "Vi"], "Evolve Tadbulb (Thunder Stone)"),
    d(940, "Wattrel", ["Sc", "Vi"], "South Province coastal areas, West Province (Area Two)"),
    d(941, "Kilowattrel", ["Sc", "Vi"], "Evolve Wattrel"),
    d(942, "Maschiff", ["Sc", "Vi"], "South Province (Areas Three-Five)"),
    d(943, "Mabosstiff", ["Sc", "Vi"], "Evolve Maschiff"),
    d(944, "Shroodle", ["Sc", "Vi"], "South Province (Areas Two-Five), trees"),
    d(945, "Grafaiai", ["Sc", "Vi"], "Evolve Shroodle"),
    d(946, "Bramblin", ["Sc", "Vi"], "Asado Desert, South Province (Area Five)"),
    d(947, "Brambleghast", ["Sc", "Vi"], "Evolve Bramblin (walk 1000 steps in Let's Go)"),
    d(948, "Toedscool", ["Sc", "Vi"], "South Province (Area Three), Casseroya Lake"),
    d(949, "Toedscruel", ["Sc", "Vi"], "Evolve Toedscool"),
    d(950, "Klawf", ["Sc", "Vi"], "South Province (Area Three), East Province"),
    d(951, "Capsakid", ["Sc", "Vi"], "South Province (Area Three-Five), West Province"),
    d(952, "Scovillain", ["Sc", "Vi"], "Evolve Capsakid (Fire Stone)"),
    d(953, "Rellor", ["Sc", "Vi"], "Asado Desert, South Province (Area Five)"),
    d(954, "Rabsca", ["Sc", "Vi"], "Evolve Rellor (walk 1000 steps in Let's Go)"),
    d(955, "Flittle", ["Sc", "Vi"], "South Province (Area Four-Five), Asado Desert"),
    d(956, "Espathra", ["Sc", "Vi"], "Evolve Flittle"),
    d(957, "Tinkatink", ["Sc", "Vi"], "South Province, ruins and rocky areas"),
    d(958, "Tinkatuff", ["Sc", "Vi"], "Evolve Tinkatink"),
    d(959, "Tinkaton", ["Sc", "Vi"], "Evolve Tinkatuff"),
    d(960, "Wiglett", ["Sc", "Vi"], "South Province (Area Five) beach, coastal areas"),
    d(961, "Wugtrio", ["Sc", "Vi"], "Evolve Wiglett"),
    d(962, "Bombirdier", ["Sc", "Vi"], "West Province (Area Two) cliffs, Glaseado Mountain"),
    d(963, "Finizen", ["Sc", "Vi"], "Ocean (Surfing), South Province coasts"),
    d(964, "Palafin", ["Sc", "Vi"], "Evolve Finizen (level up in Union Circle co-op)"),
    d(965, "Varoom", ["Sc", "Vi"], "East Province (Area Two), near Team Star bases"),
    d(966, "Revavroom", ["Sc", "Vi"], "Evolve Varoom"),
    d(967, "Cyclizar", ["Sc", "Vi"], "East Province, West Province, many areas"),
    d(968, "Orthworm", ["Sc", "Vi"], "East Province (Area Three), Glaseado Mountain"),
    d(969, "Glimmet", ["Sc", "Vi"], "Caves, South Province (Area Six), Alfornada Cavern"),
    d(970, "Glimmora", ["Sc", "Vi"], "Evolve Glimmet"),
    d(971, "Greavard", ["Sc", "Vi"], "South Province, Glaseado Mountain (nighttime)"),
    d(972, "Houndstone", ["Sc", "Vi"], "Evolve Greavard (level up at night)"),
    d(973, "Flamigo", ["Sc", "Vi"], "South Province (Area Five), lakes and marshes"),
    d(974, "Cetoddle", ["Sc", "Vi"], "Glaseado Mountain"),
    d(975, "Cetitan", ["Sc", "Vi"], "Evolve Cetoddle (Ice Stone)"),
    d(976, "Veluza", ["Sc", "Vi"], "Casseroya Lake, ocean"),
    d(977, "Dondozo", ["Sc", "Vi"], "Casseroya Lake"),
    d(978, "Tatsugiri", ["Sc", "Vi"], "Casseroya Lake (rare, in water)"),
    d(979, "Annihilape", ["Sc", "Vi"], "Evolve Primeape (use Rage Fist 20 times)"),
    d(980, "Clodsire", ["Sc", "Vi"], "Evolve Paldean Wooper"),
    d(981, "Farigiraf", ["Sc", "Vi"], "Evolve Girafarig (learn Twin Beam)"),
    d(982, "Dudunsparce", ["Sc", "Vi"], "Evolve Dunsparce (learn Hyper Drill)"),
    d(983, "Kingambit", ["Sc", "Vi"], "Evolve Bisharp (defeat 3 Bisharp leading Pawniard)"),
    d(998, "Baxcalibur", ["Sc", "Vi"], "Evolve Arctibax"),
    d(999, "Gholdengo", ["Sc", "Vi"], "Evolve Gimmighoul (collect 999 Gimmighoul Coins)"),

    // ── Paldean Regional Forms ─────────────────────────────────
    d(194, "Wooper", ["Sc", "Vi"], "South Province (Area One-Two) -- Paldean Form (Poison/Ground)"),
    d(128, "Tauros", ["Sc", "Vi"], "East Province, West Province -- Paldean Form (Fighting)"),

    // ── Returning Gen 1 Pokemon ────────────────────────────────
    d(25, "Pikachu", ["Sc", "Vi"], "South Province (Area Two), Porto Marinada (auction)"),
    d(26, "Raichu", ["Sc", "Vi"], "Evolve Pikachu (Thunder Stone)"),
    d(35, "Clefairy", ["Sc", "Vi"], "South Province (Area Six) at night (rare)"),
    d(36, "Clefable", ["Sc", "Vi"], "Evolve Clefairy (Moon Stone)"),
    d(39, "Jigglypuff", ["Sc", "Vi"], "South Province (Area Two-Four)"),
    d(40, "Wigglytuff", ["Sc", "Vi"], "Evolve Jigglypuff (Moon Stone)"),
    d(48, "Venonat", ["Sc", "Vi"], "South Province (Area Three), Tagtree Thicket"),
    d(49, "Venomoth", ["Sc", "Vi"], "Evolve Venonat"),
    d(50, "Diglett", ["Sc", "Vi"], "South Province, caves"),
    d(51, "Dugtrio", ["Sc", "Vi"], "Asado Desert, evolve Diglett"),
    d(52, "Meowth", ["Sc", "Vi"], "South Province (Area Two-Four), West Province"),
    d(53, "Persian", ["Sc", "Vi"], "Evolve Meowth"),
    d(54, "Psyduck", ["Sc", "Vi"], "South Province, rivers and lakes"),
    d(55, "Golduck", ["Sc", "Vi"], "Evolve Psyduck"),
    d(56, "Mankey", ["Sc", "Vi"], "South Province (Area Five), West Province"),
    d(57, "Primeape", ["Sc", "Vi"], "Evolve Mankey"),
    d(58, "Growlithe", ["Sc", "Vi"], "South Province (Area Three-Five), East Province"),
    d(59, "Arcanine", ["Sc", "Vi"], "Evolve Growlithe (Fire Stone)"),
    d(79, "Slowpoke", ["Sc", "Vi"], "South Province (Area Five), rivers"),
    d(80, "Slowbro", ["Sc", "Vi"], "Evolve Slowpoke"),
    d(88, "Grimer", ["Sc", "Vi"], "South Province (Area Three) near industrial areas"),
    d(89, "Muk", ["Sc", "Vi"], "Evolve Grimer"),
    d(92, "Gastly", ["Sc", "Vi"], "South Province, most areas at night"),
    d(93, "Haunter", ["Sc", "Vi"], "Evolve Gastly"),
    d(94, "Gengar", ["Sc", "Vi"], "Trade evolve Haunter"),
    d(96, "Drowzee", ["Sc", "Vi"], "South Province (Area Two-Four)"),
    d(97, "Hypno", ["Sc", "Vi"], "Evolve Drowzee"),
    d(100, "Voltorb", ["Sc", "Vi"], "Levincia, near power facilities"),
    d(101, "Electrode", ["Sc", "Vi"], "Evolve Voltorb"),
    d(113, "Chansey", ["Sc", "Vi"], "South Province (Area Two-Five), rare"),
    d(123, "Scyther", ["Sc", "Vi"], "South Province (Area Five), Casseroya Lake"),
    d(128, "Tauros", ["Sc", "Vi"], "East Province, West Province -- Paldean Form"),
    d(129, "Magikarp", ["Sc", "Vi"], "Most rivers and lakes (fishing/surfing)"),
    d(130, "Gyarados", ["Sc", "Vi"], "Evolve Magikarp"),
    d(132, "Ditto", ["Sc", "Vi"], "West Province (Area Two-Three), disguised as other Pokemon"),
    d(133, "Eevee", ["Sc", "Vi"], "South Province (Area Two), Cortondo, various"),
    d(134, "Vaporeon", ["Sc", "Vi"], "Evolve Eevee (Water Stone)"),
    d(135, "Jolteon", ["Sc", "Vi"], "Evolve Eevee (Thunder Stone)"),
    d(136, "Flareon", ["Sc", "Vi"], "Evolve Eevee (Fire Stone)"),
    d(143, "Snorlax", ["Sc", "Vi"], "Overworld (rare), Casseroya Lake area"),

    // ── Returning Gen 2 Pokemon ────────────────────────────────
    d(167, "Spinarak", ["Sc", "Vi"], "South Province at night"),
    d(168, "Ariados", ["Sc", "Vi"], "Evolve Spinarak"),
    d(172, "Pichu", ["Sc", "Vi"], "South Province (Area Two) -- breed Pikachu"),
    d(173, "Cleffa", ["Sc", "Vi"], "Breed Clefairy"),
    d(174, "Igglybuff", ["Sc", "Vi"], "Breed Jigglypuff"),
    d(179, "Mareep", ["Sc", "Vi"], "South Province (Area One-Two)"),
    d(180, "Flaaffy", ["Sc", "Vi"], "Evolve Mareep"),
    d(181, "Ampharos", ["Sc", "Vi"], "Evolve Flaaffy"),
    d(183, "Marill", ["Sc", "Vi"], "South Province, rivers and lakesides"),
    d(184, "Azumarill", ["Sc", "Vi"], "Evolve Marill"),
    d(185, "Sudowoodo", ["Sc", "Vi"], "South Province (Area Two-Five), East Province"),
    d(187, "Hoppip", ["Sc", "Vi"], "South Province (Area One), Cabo Poco"),
    d(188, "Skiploom", ["Sc", "Vi"], "Evolve Hoppip"),
    d(189, "Jumpluff", ["Sc", "Vi"], "Evolve Skiploom"),
    d(190, "Aipom", ["Sc", "Vi"], "South Province, West Province (trees)"),
    d(196, "Espeon", ["Sc", "Vi"], "Evolve Eevee (high friendship, daytime)"),
    d(197, "Umbreon", ["Sc", "Vi"], "Evolve Eevee (high friendship, nighttime)"),
    d(198, "Murkrow", ["Sc", "Vi"], "South Province at night, Glaseado Mountain"),
    d(199, "Slowking", ["Sc", "Vi"], "Evolve Slowpoke (King's Rock trade)"),
    d(200, "Misdreavus", ["Sc"], "South Province (Area One-Four) at night"),
    d(204, "Pineco", ["Sc", "Vi"], "South Province (Area Three-Five), trees"),
    d(205, "Forretress", ["Sc", "Vi"], "Evolve Pineco"),
    d(206, "Dunsparce", ["Sc", "Vi"], "South Province (Area One), East Province"),
    d(211, "Qwilfish", ["Sc", "Vi"], "East Province (Area Two) ocean"),
    d(212, "Scizor", ["Sc", "Vi"], "Trade evolve Scyther (Metal Coat)"),
    d(214, "Heracross", ["Sc", "Vi"], "South Province (Area Five), West Province (trees)"),
    d(215, "Sneasel", ["Sc", "Vi"], "Glaseado Mountain, North Province"),
    d(216, "Teddiursa", ["Sc", "Vi"], "South Province (Area Five), Glaseado Mountain"),
    d(217, "Ursaring", ["Sc", "Vi"], "Evolve Teddiursa"),
    d(225, "Delibird", ["Sc", "Vi"], "Glaseado Mountain"),
    d(228, "Houndour", ["Sc", "Vi"], "South Province (Area Three-Five)"),
    d(229, "Houndoom", ["Sc", "Vi"], "Evolve Houndour"),
    d(231, "Phanpy", ["Sc", "Vi"], "South Province (Area Two), Asado Desert"),
    d(232, "Donphan", ["Sc", "Vi"], "Evolve Phanpy"),
    d(234, "Stantler", ["Sc", "Vi"], "South Province (Area Five), forests"),
    d(242, "Blissey", ["Sc", "Vi"], "Evolve Chansey (high friendship)"),
    d(246, "Larvitar", ["Sc"], "South Province (Area Five), Alfornada Cavern"),
    d(247, "Pupitar", ["Sc"], "Evolve Larvitar"),
    d(248, "Tyranitar", ["Sc"], "Evolve Pupitar"),

    // ── Returning Gen 3 Pokemon ────────────────────────────────
    d(263, "Zigzagoon", ["Sc", "Vi"], "South Province (Area Two), West Province"),
    d(264, "Linoone", ["Sc", "Vi"], "Evolve Zigzagoon"),
    d(265, "Wurmple", ["Sc", "Vi"], "South Province (Area One)"),
    d(266, "Silcoon", ["Sc", "Vi"], "Evolve Wurmple (random)"),
    d(267, "Beautifly", ["Sc", "Vi"], "Evolve Silcoon"),
    d(268, "Cascoon", ["Sc", "Vi"], "Evolve Wurmple (random)"),
    d(269, "Dustox", ["Sc", "Vi"], "Evolve Cascoon"),
    d(280, "Ralts", ["Sc", "Vi"], "South Province (Area Two), South Province (Area Four)"),
    d(281, "Kirlia", ["Sc", "Vi"], "Evolve Ralts"),
    d(282, "Gardevoir", ["Sc", "Vi"], "Evolve Kirlia (female or male)"),
    d(283, "Surskit", ["Sc", "Vi"], "South Province, near water"),
    d(284, "Masquerain", ["Sc", "Vi"], "Evolve Surskit"),
    d(285, "Shroomish", ["Sc", "Vi"], "South Province (Area Four-Five), forests"),
    d(286, "Breloom", ["Sc", "Vi"], "Evolve Shroomish"),
    d(296, "Makuhita", ["Sc", "Vi"], "South Province (Area Three), East Province"),
    d(297, "Hariyama", ["Sc", "Vi"], "Evolve Makuhita"),
    d(302, "Sableye", ["Sc", "Vi"], "Alfornada Cavern, caves at night"),
    d(316, "Gulpin", ["Vi"], "South Province (Area One-Three)"),
    d(317, "Swalot", ["Vi"], "Evolve Gulpin"),
    d(322, "Numel", ["Sc", "Vi"], "East Province (Area Three), near volcanic areas"),
    d(323, "Camerupt", ["Sc", "Vi"], "Evolve Numel"),
    d(324, "Torkoal", ["Sc", "Vi"], "East Province (Area Three), South Province"),
    d(325, "Spoink", ["Sc", "Vi"], "South Province (Area Four), East Province"),
    d(326, "Grumpig", ["Sc", "Vi"], "Evolve Spoink"),
    d(331, "Cacnea", ["Sc", "Vi"], "Asado Desert"),
    d(332, "Cacturne", ["Sc", "Vi"], "Evolve Cacnea"),
    d(333, "Swablu", ["Sc", "Vi"], "South Province (Area Five), Glaseado Mountain"),
    d(334, "Altaria", ["Sc", "Vi"], "Evolve Swablu"),
    d(335, "Zangoose", ["Sc", "Vi"], "South Province (Area Five), rare"),
    d(336, "Seviper", ["Sc", "Vi"], "South Province (Area Five), Tagtree Thicket"),
    d(339, "Barboach", ["Sc", "Vi"], "South Province rivers, East Province rivers"),
    d(340, "Whiscash", ["Sc", "Vi"], "Evolve Barboach"),
    d(353, "Shuppet", ["Sc", "Vi"], "South Province at night, Glaseado Mountain"),
    d(354, "Banette", ["Sc", "Vi"], "Evolve Shuppet"),
    d(357, "Tropius", ["Sc", "Vi"], "South Province (Area Five), tropical areas"),
    d(361, "Snorunt", ["Sc", "Vi"], "Glaseado Mountain"),
    d(362, "Glalie", ["Sc", "Vi"], "Evolve Snorunt"),
    d(371, "Bagon", ["Vi"], "South Province (Area Six), caves"),
    d(372, "Shelgon", ["Vi"], "Evolve Bagon"),
    d(373, "Salamence", ["Vi"], "Evolve Shelgon"),

    // ── Returning Gen 4 Pokemon ────────────────────────────────
    d(396, "Starly", ["Sc", "Vi"], "South Province (Area One-Two), many areas"),
    d(397, "Staravia", ["Sc", "Vi"], "Evolve Starly"),
    d(398, "Staraptor", ["Sc", "Vi"], "Evolve Staravia"),
    d(399, "Bidoof", ["Sc", "Vi"], "South Province (Area One), rivers"),
    d(400, "Bibarel", ["Sc", "Vi"], "Evolve Bidoof"),
    d(401, "Kricketot", ["Sc", "Vi"], "South Province (Area One-Two)"),
    d(402, "Kricketune", ["Sc", "Vi"], "Evolve Kricketot"),
    d(403, "Shinx", ["Sc", "Vi"], "South Province (Area Two-Three), East Province"),
    d(404, "Luxio", ["Sc", "Vi"], "Evolve Shinx"),
    d(405, "Luxray", ["Sc", "Vi"], "Evolve Luxio"),
    d(415, "Combee", ["Sc", "Vi"], "South Province, near flowers and trees"),
    d(416, "Vespiquen", ["Sc", "Vi"], "Evolve Combee (female only)"),
    d(417, "Pachirisu", ["Sc", "Vi"], "East Province, South Province (trees)"),
    d(418, "Buizel", ["Sc", "Vi"], "South Province, rivers and lakes"),
    d(419, "Floatzel", ["Sc", "Vi"], "Evolve Buizel"),
    d(422, "Shellos", ["Sc", "Vi"], "South Province coastal areas"),
    d(423, "Gastrodon", ["Sc", "Vi"], "Evolve Shellos"),
    d(424, "Ambipom", ["Sc", "Vi"], "Evolve Aipom (learn Double Hit)"),
    d(425, "Drifloon", ["Sc"], "South Province at night, near ruins"),
    d(426, "Drifblim", ["Sc"], "Evolve Drifloon"),
    d(429, "Mismagius", ["Vi"], "Evolve Misdreavus (Dusk Stone)"),
    d(430, "Honchkrow", ["Sc", "Vi"], "Evolve Murkrow (Dusk Stone)"),
    d(434, "Stunky", ["Sc"], "South Province (Area Two-Four)"),
    d(435, "Skuntank", ["Sc"], "Evolve Stunky"),
    d(436, "Bronzor", ["Sc", "Vi"], "East Province, ruins"),
    d(437, "Bronzong", ["Sc", "Vi"], "Evolve Bronzor"),
    d(438, "Bonsly", ["Sc", "Vi"], "Breed Sudowoodo"),
    d(440, "Happiny", ["Sc", "Vi"], "Breed Chansey/Blissey"),
    d(443, "Gible", ["Sc", "Vi"], "South Province (Area Six), caves"),
    d(444, "Gabite", ["Sc", "Vi"], "Evolve Gible"),
    d(445, "Garchomp", ["Sc", "Vi"], "Evolve Gabite"),
    d(446, "Munchlax", ["Sc", "Vi"], "Breed Snorlax"),
    d(447, "Riolu", ["Sc", "Vi"], "South Province (Area Four), East Province"),
    d(448, "Lucario", ["Sc", "Vi"], "Evolve Riolu (high friendship, daytime)"),
    d(449, "Hippopotas", ["Sc", "Vi"], "Asado Desert"),
    d(450, "Hippowdon", ["Sc", "Vi"], "Evolve Hippopotas"),
    d(453, "Croagunk", ["Sc", "Vi"], "South Province (Area Three), Tagtree Thicket"),
    d(454, "Toxicroak", ["Sc", "Vi"], "Evolve Croagunk"),
    d(459, "Snover", ["Sc", "Vi"], "Glaseado Mountain"),
    d(460, "Abomasnow", ["Sc", "Vi"], "Evolve Snover"),
    d(461, "Weavile", ["Sc", "Vi"], "Evolve Sneasel (Razor Claw at night)"),
    d(462, "Magnezone", ["Sc", "Vi"], "Evolve Magneton (Thunder Stone)"),
    d(464, "Rhyperior", ["Sc", "Vi"], "Trade evolve Rhydon (Protector)"),
    d(466, "Electivire", ["Sc", "Vi"], "Trade evolve Electabuzz (Electirizer)"),
    d(467, "Magmortar", ["Sc", "Vi"], "Trade evolve Magmar (Magmarizer)"),
    d(470, "Leafeon", ["Sc", "Vi"], "Evolve Eevee (Leaf Stone)"),
    d(471, "Glaceon", ["Sc", "Vi"], "Evolve Eevee (Ice Stone)"),
    d(475, "Gallade", ["Sc", "Vi"], "Evolve Kirlia (male, Dawn Stone)"),

    // ── Returning Gen 5 Pokemon ────────────────────────────────
    d(548, "Petilil", ["Sc", "Vi"], "South Province (Area Three-Five)"),
    d(549, "Lilligant", ["Sc", "Vi"], "Evolve Petilil (Sun Stone)"),
    d(550, "Basculin", ["Sc", "Vi"], "South Province rivers, Casseroya Lake"),
    d(551, "Sandile", ["Sc", "Vi"], "Asado Desert, South Province (Area Five)"),
    d(552, "Krokorok", ["Sc", "Vi"], "Evolve Sandile"),
    d(553, "Krookodile", ["Sc", "Vi"], "Evolve Krokorok"),
    d(570, "Zorua", ["Sc", "Vi"], "South Province (Area Two-Four), disguised"),
    d(571, "Zoroark", ["Sc", "Vi"], "Evolve Zorua"),
    d(574, "Gothita", ["Sc", "Vi"], "South Province (Area Two)"),
    d(575, "Gothorita", ["Sc", "Vi"], "Evolve Gothita"),
    d(576, "Gothitelle", ["Sc", "Vi"], "Evolve Gothorita"),
    d(585, "Deerling", ["Sc", "Vi"], "South Province, changes form by season"),
    d(586, "Sawsbuck", ["Sc", "Vi"], "Evolve Deerling"),
    d(590, "Foongus", ["Sc", "Vi"], "South Province (Area Three), Tagtree Thicket"),
    d(591, "Amoonguss", ["Sc", "Vi"], "Evolve Foongus"),
    d(594, "Alomomola", ["Sc", "Vi"], "Ocean (Surfing), coastal areas"),
    d(602, "Tynamo", ["Sc", "Vi"], "South Province caves, rare"),
    d(603, "Eelektrik", ["Sc", "Vi"], "Evolve Tynamo"),
    d(604, "Eelektross", ["Sc", "Vi"], "Evolve Eelektrik (Thunder Stone)"),
    d(610, "Axew", ["Sc", "Vi"], "South Province (Area Six), caves"),
    d(611, "Fraxure", ["Sc", "Vi"], "Evolve Axew"),
    d(612, "Haxorus", ["Sc", "Vi"], "Evolve Fraxure"),
    d(613, "Cubchoo", ["Sc", "Vi"], "Glaseado Mountain"),
    d(614, "Beartic", ["Sc", "Vi"], "Evolve Cubchoo"),
    d(615, "Cryogonal", ["Sc", "Vi"], "Glaseado Mountain"),
    d(624, "Pawniard", ["Sc", "Vi"], "South Province (Area Five), bamboo forests"),
    d(625, "Bisharp", ["Sc", "Vi"], "Evolve Pawniard"),
    d(627, "Rufflet", ["Sc", "Vi"], "South Province (Area Five), mountains"),
    d(628, "Braviary", ["Sc", "Vi"], "Evolve Rufflet"),
    d(633, "Deino", ["Sc"], "South Province (Area Six), caves"),
    d(634, "Zweilous", ["Sc"], "Evolve Deino"),
    d(635, "Hydreigon", ["Sc"], "Evolve Zweilous"),

    // ── Returning Gen 6 Pokemon ────────────────────────────────
    d(661, "Fletchling", ["Sc", "Vi"], "South Province (Area One-Two), many areas"),
    d(662, "Fletchinder", ["Sc", "Vi"], "Evolve Fletchling"),
    d(663, "Talonflame", ["Sc", "Vi"], "Evolve Fletchinder"),
    d(667, "Litleo", ["Sc", "Vi"], "South Province (Area Three-Five), East Province"),
    d(668, "Pyroar", ["Sc", "Vi"], "Evolve Litleo"),
    d(669, "Flabebe", ["Sc", "Vi"], "South Province (Area Four), meadows"),
    d(670, "Floette", ["Sc", "Vi"], "Evolve Flabebe"),
    d(671, "Florges", ["Sc", "Vi"], "Evolve Floette (Shiny Stone)"),
    d(672, "Skiddo", ["Sc", "Vi"], "South Province (Area Five), West Province"),
    d(673, "Gogoat", ["Sc", "Vi"], "Evolve Skiddo"),
    d(676, "Furfrou", ["Sc", "Vi"], "Mesagoza, Levincia"),
    d(690, "Skrelp", ["Sc", "Vi"], "East Province (Area Two) ocean"),
    d(691, "Dragalge", ["Sc", "Vi"], "Evolve Skrelp"),
    d(692, "Clauncher", ["Sc", "Vi"], "East Province (Area Two) ocean"),
    d(693, "Clawitzer", ["Sc", "Vi"], "Evolve Clauncher"),
    d(700, "Sylveon", ["Sc", "Vi"], "Evolve Eevee (high friendship + Fairy move)"),
    d(701, "Hawlucha", ["Sc", "Vi"], "South Province (Area Five), rocky cliffs"),
    d(702, "Dedenne", ["Sc", "Vi"], "South Province (Area Four), West Province"),
    d(704, "Goomy", ["Sc", "Vi"], "South Province (Area Five) rain, Casseroya Lake"),
    d(705, "Sliggoo", ["Sc", "Vi"], "Evolve Goomy"),
    d(706, "Goodra", ["Sc", "Vi"], "Evolve Sliggoo (level up in rain)"),
    d(707, "Klefki", ["Sc", "Vi"], "East Province, near ruins and buildings"),
    d(712, "Bergmite", ["Sc", "Vi"], "Glaseado Mountain"),
    d(713, "Avalugg", ["Sc", "Vi"], "Evolve Bergmite"),
    d(714, "Noibat", ["Sc", "Vi"], "South Province caves, Alfornada Cavern"),
    d(715, "Noivern", ["Sc", "Vi"], "Evolve Noibat"),

    // ── Returning Gen 7 Pokemon ────────────────────────────────
    d(734, "Yungoos", ["Sc", "Vi"], "South Province (Area One)"),
    d(735, "Gumshoos", ["Sc", "Vi"], "Evolve Yungoos (daytime)"),
    d(739, "Crabrawler", ["Sc", "Vi"], "South Province (Area Five), near berry trees"),
    d(740, "Crabominable", ["Sc", "Vi"], "Evolve Crabrawler (Ice Stone)"),
    d(741, "Oricorio", ["Sc", "Vi"], "South Province (varies by area), Casseroya Lake"),
    d(744, "Rockruff", ["Sc", "Vi"], "South Province (Area Three), East Province"),
    d(745, "Lycanroc", ["Sc", "Vi"], "Evolve Rockruff (varies by time/ability)"),
    d(749, "Mudbray", ["Sc", "Vi"], "South Province (Area Four-Five), East Province"),
    d(750, "Mudsdale", ["Sc", "Vi"], "Evolve Mudbray"),
    d(753, "Fomantis", ["Sc", "Vi"], "South Province (Area Three), forests"),
    d(754, "Lurantis", ["Sc", "Vi"], "Evolve Fomantis (daytime)"),
    d(757, "Salandit", ["Sc", "Vi"], "South Province (Area Three-Five), caves"),
    d(758, "Salazzle", ["Sc", "Vi"], "Evolve Salandit (female only)"),
    d(761, "Bounsweet", ["Sc", "Vi"], "South Province (Area Three-Five)"),
    d(762, "Steenee", ["Sc", "Vi"], "Evolve Bounsweet"),
    d(763, "Tsareena", ["Sc", "Vi"], "Evolve Steenee (learn Stomp)"),
    d(764, "Comfey", ["Sc", "Vi"], "South Province (Area Four-Five), meadows"),
    d(765, "Oranguru", ["Sc"], "South Province (Area Five), Casseroya Lake"),
    d(766, "Passimian", ["Vi"], "South Province (Area Five), Casseroya Lake"),
    d(769, "Sandygast", ["Sc", "Vi"], "South Province beaches"),
    d(770, "Palossand", ["Sc", "Vi"], "Evolve Sandygast"),
    d(775, "Komala", ["Sc", "Vi"], "South Province (Area Three), trees"),
    d(778, "Mimikyu", ["Sc", "Vi"], "South Province (Area Four) at night, Tagtree Thicket"),

    // ── Returning Gen 8 Pokemon ────────────────────────────────
    d(819, "Skwovet", ["Sc", "Vi"], "South Province (Area One-Two)"),
    d(820, "Greedent", ["Sc", "Vi"], "Evolve Skwovet"),
    d(823, "Corviknight", ["Sc", "Vi"], "Evolve Corvisquire"),
    d(821, "Rookidee", ["Sc", "Vi"], "South Province (Area One-Three), East Province"),
    d(822, "Corvisquire", ["Sc", "Vi"], "Evolve Rookidee"),
    d(833, "Chewtle", ["Sc", "Vi"], "South Province rivers and ponds"),
    d(834, "Drednaw", ["Sc", "Vi"], "Evolve Chewtle"),
    d(840, "Applin", ["Sc", "Vi"], "South Province (Area Five), Tagtree Thicket (trees)"),
    d(841, "Flapple", ["Sc", "Vi"], "Evolve Applin (Tart Apple)"),
    d(842, "Appletun", ["Sc", "Vi"], "Evolve Applin (Sweet Apple)"),
    d(843, "Silicobra", ["Sc", "Vi"], "Asado Desert, East Province"),
    d(844, "Sandaconda", ["Sc", "Vi"], "Evolve Silicobra"),
    d(848, "Toxel", ["Sc", "Vi"], "South Province (Area Two-Three)"),
    d(849, "Toxtricity", ["Sc", "Vi"], "Evolve Toxel (form depends on Nature)"),
    d(850, "Sizzlipede", ["Sc", "Vi"], "East Province (Area One-Three)"),
    d(851, "Centiskorch", ["Sc", "Vi"], "Evolve Sizzlipede"),
    d(854, "Sinistea", ["Sc", "Vi"], "Alfornada, South Province (Area Four) at night"),
    d(855, "Polteageist", ["Sc", "Vi"], "Evolve Sinistea (Cracked Pot or Chipped Pot)"),
    d(856, "Hatenna", ["Sc", "Vi"], "South Province (Area Two), forests"),
    d(857, "Hattrem", ["Sc", "Vi"], "Evolve Hatenna"),
    d(858, "Hatterene", ["Sc", "Vi"], "Evolve Hattrem"),
    d(859, "Impidimp", ["Sc", "Vi"], "South Province at night, Tagtree Thicket"),
    d(860, "Morgrem", ["Sc", "Vi"], "Evolve Impidimp"),
    d(861, "Grimmsnarl", ["Sc", "Vi"], "Evolve Morgrem"),
    d(870, "Falinks", ["Sc", "Vi"], "East Province (Area Two-Three)"),
    d(871, "Pincurchin", ["Sc", "Vi"], "East Province (Area Two) coast"),
    d(872, "Snom", ["Sc", "Vi"], "Glaseado Mountain"),
    d(873, "Frosmoth", ["Sc", "Vi"], "Evolve Snom (high friendship at night)"),
    d(874, "Stonjourner", ["Sc"], "Asado Desert, South Province (Area Five)"),
    d(875, "Eiscue", ["Vi"], "Glaseado Mountain, North Province"),
    d(878, "Cufant", ["Sc", "Vi"], "East Province (Area Three)"),
    d(879, "Copperajah", ["Sc", "Vi"], "Evolve Cufant"),
    d(884, "Duraludon", ["Sc", "Vi"], "Alfornada Cavern, caves"),
    d(885, "Dreepy", ["Vi"], "South Province (Area Six) at night, caves"),
    d(886, "Drakloak", ["Vi"], "Evolve Dreepy"),
    d(887, "Dragapult", ["Vi"], "Evolve Drakloak"),

    // ── Additional Returning Pokemon ───────────────────────────
    d(81, "Magnemite", ["Sc", "Vi"], "South Province near power lines, East Province"),
    d(82, "Magneton", ["Sc", "Vi"], "Evolve Magnemite"),
    d(111, "Rhyhorn", ["Sc", "Vi"], "Asado Desert, East Province"),
    d(112, "Rhydon", ["Sc", "Vi"], "Evolve Rhyhorn"),
    d(116, "Horsea", ["Sc", "Vi"], "East Province (Area Two) ocean"),
    d(117, "Seadra", ["Sc", "Vi"], "Evolve Horsea"),
    d(230, "Kingdra", ["Sc", "Vi"], "Trade evolve Seadra (Dragon Scale)"),
    d(125, "Electabuzz", ["Sc", "Vi"], "South Province near power areas"),
    d(126, "Magmar", ["Sc", "Vi"], "East Province (Area Three), volcanic areas"),
    d(239, "Elekid", ["Sc", "Vi"], "South Province (Area Two), breed Electabuzz"),
    d(240, "Magby", ["Sc", "Vi"], "Breed Magmar"),
    d(203, "Girafarig", ["Sc", "Vi"], "West Province (Area Two-Three)"),
    d(210, "Granbull", ["Sc", "Vi"], "Evolve Snubbull"),
    d(209, "Snubbull", ["Sc", "Vi"], "South Province (Area Five)"),

    // ── Gimmighoul & Gholdengo ─────────────────────────────────
    d(1000, "Gimmighoul", ["Sc", "Vi"], "Overworld (chest form on towers, roaming form on ground)"),

    // ── Paradox Pokemon -- Scarlet Exclusives ──────────────────
    d(984, "Great Tusk", ["Sc"], "Area Zero (post-game), Asado Desert Titan"),
    d(985, "Scream Tail", ["Sc"], "Area Zero"),
    d(986, "Brute Bonnet", ["Sc"], "Area Zero"),
    d(987, "Flutter Mane", ["Sc"], "Area Zero"),
    d(988, "Slither Wing", ["Sc"], "Area Zero"),
    d(989, "Sandy Shocks", ["Sc"], "Area Zero"),
    d(1005, "Roaring Moon", ["Sc"], "Area Zero (rare)"),
    d(1007, "Koraidon", ["Sc"], "Story gift (ride form), Area Zero Lv. 72 (battle form)"),

    // ── Paradox Pokemon -- Violet Exclusives ───────────────────
    d(990, "Iron Treads", ["Vi"], "Area Zero (post-game), Asado Desert Titan"),
    d(991, "Iron Bundle", ["Vi"], "Area Zero"),
    d(992, "Iron Hands", ["Vi"], "Area Zero"),
    d(993, "Iron Jugulis", ["Vi"], "Area Zero"),
    d(994, "Iron Moth", ["Vi"], "Area Zero"),
    d(995, "Iron Thorns", ["Vi"], "Area Zero"),
    d(1006, "Iron Valiant", ["Vi"], "Area Zero (rare)"),
    d(1008, "Miraidon", ["Vi"], "Story gift (ride form), Area Zero Lv. 72 (battle form)"),

    // ── Treasures of Ruin Legendaries ──────────────────────────
    d(1001, "Wo-Chien", ["Sc", "Vi"], "Casseroya Lake shrine (unseal with 8 purple stakes)"),
    d(1002, "Chien-Pao", ["Sc", "Vi"], "Alfornada shrine (unseal with 8 blue stakes)"),
    d(1003, "Ting-Lu", ["Sc", "Vi"], "Socarrat Trail shrine (unseal with 8 green stakes)"),
    d(1004, "Chi-Yu", ["Sc", "Vi"], "North Province shrine (unseal with 8 yellow stakes)"),

    // ── Additional Gen 9 Pokemon ───────────────────────────────
    d(996, "Frigibax", ["Sc", "Vi"], "Glaseado Mountain"),
    d(997, "Arctibax", ["Sc", "Vi"], "Evolve Frigibax"),

    // ── More Returning Pokemon ─────────────────────────────────
    d(147, "Dratini", ["Sc", "Vi"], "Casseroya Lake"),
    d(148, "Dragonair", ["Sc", "Vi"], "Evolve Dratini"),
    d(149, "Dragonite", ["Sc", "Vi"], "Evolve Dragonair"),
    d(23, "Ekans", ["Sc", "Vi"], "South Province (Area Two-Four)"),
    d(24, "Arbok", ["Sc", "Vi"], "Evolve Ekans"),
    d(74, "Geodude", ["Sc", "Vi"], "South Province (Area Three), caves"),
    d(75, "Graveler", ["Sc", "Vi"], "Evolve Geodude"),
    d(76, "Golem", ["Sc", "Vi"], "Trade evolve Graveler"),
    d(109, "Koffing", ["Sc", "Vi"], "South Province (Area Three), East Province"),
    d(110, "Weezing", ["Sc", "Vi"], "Evolve Koffing"),
    d(114, "Tangela", ["Sc", "Vi"], "South Province (Area Five), Tagtree Thicket"),
    d(465, "Tangrowth", ["Sc", "Vi"], "Evolve Tangela (learn Ancient Power)"),
    d(278, "Wingull", ["Sc", "Vi"], "Coastal areas throughout Paldea"),
    d(279, "Pelipper", ["Sc", "Vi"], "Evolve Wingull"),
    d(307, "Meditite", ["Sc", "Vi"], "South Province (Area Six), Alfornada"),
    d(308, "Medicham", ["Sc", "Vi"], "Evolve Meditite"),
    d(456, "Finneon", ["Sc", "Vi"], "Ocean (Surfing), coastal areas"),
    d(457, "Lumineon", ["Sc", "Vi"], "Evolve Finneon"),
    d(546, "Cottonee", ["Sc", "Vi"], "South Province (Area Three), meadows"),
    d(547, "Whimsicott", ["Sc", "Vi"], "Evolve Cottonee (Sun Stone)"),
    d(580, "Ducklett", ["Sc", "Vi"], "South Province rivers and lakes"),
    d(581, "Swanna", ["Sc", "Vi"], "Evolve Ducklett"),
    d(619, "Mienfoo", ["Sc", "Vi"], "South Province (Area Five), bamboo forests"),
    d(620, "Mienshao", ["Sc", "Vi"], "Evolve Mienfoo"),
    d(631, "Heatmor", ["Sc", "Vi"], "Asado Desert, East Province"),
    d(632, "Durant", ["Sc", "Vi"], "East Province (Area Two-Three)"),
    d(636, "Larvesta", ["Sc", "Vi"], "Asado Desert (rare)"),
    d(637, "Volcarona", ["Sc", "Vi"], "Evolve Larvesta"),
    d(759, "Stufful", ["Sc", "Vi"], "South Province (Area Three-Five)"),
    d(760, "Bewear", ["Sc", "Vi"], "Evolve Stufful"),
    d(191, "Sunkern", ["Sc", "Vi"], "South Province (Area One-Two)"),
    d(192, "Sunflora", ["Sc", "Vi"], "Evolve Sunkern (Sun Stone)"),
    d(195, "Quagsire", ["Sc", "Vi"], "Evolve Wooper (Johtonian), or South Province rivers"),
    d(220, "Swinub", ["Sc", "Vi"], "Glaseado Mountain"),
    d(221, "Piloswine", ["Sc", "Vi"], "Evolve Swinub"),
    d(473, "Mamoswine", ["Sc", "Vi"], "Evolve Piloswine (learn Ancient Power)"),
    d(235, "Smeargle", ["Sc", "Vi"], "South Province (Area Five) rare"),
    d(286, "Breloom", ["Sc", "Vi"], "Evolve Shroomish"),
    d(901, "Ursaluna", ["Sc", "Vi"], "Evolve Ursaring (Peat Block during full moon)"),

    // ── Additional Route Pokemon ───────────────────────────────
    d(72, "Tentacool", ["Sc", "Vi"], "Ocean (Surfing) throughout Paldea"),
    d(73, "Tentacruel", ["Sc", "Vi"], "Evolve Tentacool"),
    d(118, "Goldeen", ["Sc", "Vi"], "Rivers and ponds (Surfing)"),
    d(119, "Seaking", ["Sc", "Vi"], "Evolve Goldeen"),
    d(120, "Staryu", ["Sc", "Vi"], "East Province (Area Two) coast at night"),
    d(121, "Starmie", ["Sc", "Vi"], "Evolve Staryu (Water Stone)"),
    d(98, "Krabby", ["Sc", "Vi"], "South Province coastal areas"),
    d(99, "Kingler", ["Sc", "Vi"], "Evolve Krabby"),
    d(170, "Chinchou", ["Sc", "Vi"], "Ocean (Surfing)"),
    d(171, "Lanturn", ["Sc", "Vi"], "Evolve Chinchou"),
    d(222, "Corsola", ["Sc", "Vi"], "East Province (Area Two) ocean"),
    d(223, "Remoraid", ["Sc", "Vi"], "East Province ocean, rivers"),
    d(224, "Octillery", ["Sc", "Vi"], "Evolve Remoraid"),
    d(312, "Minun", ["Sc", "Vi"], "South Province (Area Two), East Province"),
    d(311, "Plusle", ["Sc", "Vi"], "South Province (Area Two), East Province"),
    d(313, "Volbeat", ["Sc", "Vi"], "South Province at night"),
    d(314, "Illumise", ["Sc", "Vi"], "South Province at night"),
    d(370, "Luvdisc", ["Sc", "Vi"], "Ocean (Surfing), West Province (Area Two)"),
    d(469, "Yanmega", ["Sc", "Vi"], "Evolve Yanma (learn Ancient Power)"),
    d(193, "Yanma", ["Sc", "Vi"], "South Province (Area Five), West Province"),
    d(468, "Togekiss", ["Sc", "Vi"], "Evolve Togetic (Shiny Stone)"),
    d(176, "Togetic", ["Sc", "Vi"], "Evolve Togepi (high friendship)"),
    d(175, "Togepi", ["Sc", "Vi"], "South Province (Area Two), breed Togetic"),
    d(479, "Rotom", ["Sc", "Vi"], "Porto Marinada auction, Levincia"),
  ],
};
