import type { GameDexEntry, GameDex } from "../game-dex";

const d = (
  pokemonId: number,
  name: string,
  versions: string[],
  method?: string
): GameDexEntry => ({ pokemonId, name, versions, method });

/* ══════════════════════════════════════════════════
 *  Sun & Moon — Alola Pokédex (~300 obtainable)
 * ══════════════════════════════════════════════════ */
export const SUN_MOON_DEX: GameDex = {
  slug: "sun-moon",
  versionTags: ["Su", "Mo"],
  pokemon: [
    // ── Starters & evolutions ───────────────────────
    d(722, "Rowlet", ["Su", "Mo"], "Starter from Prof. Kukui"),
    d(723, "Dartrix", ["Su", "Mo"], "Evolve Rowlet"),
    d(724, "Decidueye", ["Su", "Mo"], "Evolve Dartrix"),
    d(725, "Litten", ["Su", "Mo"], "Starter from Prof. Kukui"),
    d(726, "Torracat", ["Su", "Mo"], "Evolve Litten"),
    d(727, "Incineroar", ["Su", "Mo"], "Evolve Torracat"),
    d(728, "Popplio", ["Su", "Mo"], "Starter from Prof. Kukui"),
    d(729, "Brionne", ["Su", "Mo"], "Evolve Popplio"),
    d(730, "Primarina", ["Su", "Mo"], "Evolve Brionne"),

    // ── Early Route 1 Pokémon ───────────────────────
    d(731, "Pikipek", ["Su", "Mo"], "Routes 1, 4, 5, 6"),
    d(732, "Trumbeak", ["Su", "Mo"], "Routes 8, 11, evolve Pikipek"),
    d(733, "Toucannon", ["Su", "Mo"], "Poni Plains, evolve Trumbeak"),
    d(734, "Yungoos", ["Su"], "Routes 1, 2, 4, 6 (day)"),
    d(735, "Gumshoos", ["Su"], "Routes 10, 15, evolve Yungoos (day)"),
    d(19, "Rattata", ["Mo"], "Routes 1, 2, 4, 6 (night, Alolan form)"),
    d(20, "Raticate", ["Mo"], "Routes 10, 15, evolve Rattata (night, Alolan form)"),
    d(172, "Pichu", ["Su", "Mo"], "Route 1 (rare)"),
    d(25, "Pikachu", ["Su", "Mo"], "Evolve Pichu (friendship)"),
    d(26, "Raichu", ["Su", "Mo"], "Evolve Pikachu (Thunder Stone, Alolan form)"),
    d(165, "Ledyba", ["Su"], "Route 1 (day)"),
    d(166, "Ledian", ["Su"], "Evolve Ledyba"),
    d(167, "Spinarak", ["Mo"], "Route 1 (night)"),
    d(168, "Ariados", ["Mo"], "Evolve Spinarak"),
    d(10, "Caterpie", ["Su", "Mo"], "Route 1, Melemele Meadow"),
    d(11, "Metapod", ["Su", "Mo"], "Route 1, evolve Caterpie"),
    d(12, "Butterfree", ["Su", "Mo"], "Evolve Metapod"),
    d(736, "Grubbin", ["Su", "Mo"], "Routes 1, 4, 5, 6"),
    d(737, "Charjabug", ["Su", "Mo"], "Route 8, Blush Mountain, evolve Grubbin"),
    d(738, "Vikavolt", ["Su", "Mo"], "Evolve Charjabug (level up at Vast Poni Canyon)"),
    d(438, "Bonsly", ["Su", "Mo"], "Route 1 (SOS)"),
    d(185, "Sudowoodo", ["Su", "Mo"], "Evolve Bonsly (learn Mimic)"),

    // ── Melemele Island ─────────────────────────────
    d(63, "Abra", ["Su", "Mo"], "Route 2, Hau'oli City"),
    d(64, "Kadabra", ["Su", "Mo"], "Evolve Abra"),
    d(65, "Alakazam", ["Su", "Mo"], "Trade evolve Kadabra"),
    d(52, "Meowth", ["Su", "Mo"], "Route 2, Hau'oli City (Alolan form)"),
    d(53, "Persian", ["Mo"], "Evolve Meowth (friendship, Alolan form)"),
    d(81, "Magnemite", ["Su", "Mo"], "Route 1, Trainer's School"),
    d(82, "Magneton", ["Su", "Mo"], "Evolve Magnemite"),
    d(462, "Magnezone", ["Su", "Mo"], "Evolve Magneton (level up at Vast Poni Canyon)"),
    d(88, "Grimer", ["Su", "Mo"], "Route 1, Hau'oli City (Alolan form)"),
    d(89, "Muk", ["Su", "Mo"], "Evolve Grimer (Alolan form)"),
    d(58, "Growlithe", ["Su", "Mo"], "Route 2"),
    d(59, "Arcanine", ["Su", "Mo"], "Evolve Growlithe (Fire Stone)"),
    d(96, "Drowzee", ["Su", "Mo"], "Route 2"),
    d(97, "Hypno", ["Su", "Mo"], "Evolve Drowzee"),
    d(296, "Makuhita", ["Su", "Mo"], "Route 2"),
    d(297, "Hariyama", ["Su", "Mo"], "Poni Plains, evolve Makuhita"),
    d(235, "Smeargle", ["Su", "Mo"], "Route 2"),
    d(739, "Crabrawler", ["Su", "Mo"], "Berry trees (all islands)"),
    d(740, "Crabominable", ["Su", "Mo"], "Evolve Crabrawler (level up at Mount Lanakila)"),
    d(92, "Gastly", ["Su", "Mo"], "Route 1 (night), Hau'oli Cemetery"),
    d(93, "Haunter", ["Su", "Mo"], "Thrifty Megamart, evolve Gastly"),
    d(94, "Gengar", ["Su", "Mo"], "Trade evolve Haunter"),
    d(41, "Zubat", ["Su", "Mo"], "Verdant Cavern, various caves"),
    d(42, "Golbat", ["Su", "Mo"], "Various caves, evolve Zubat"),
    d(169, "Crobat", ["Su", "Mo"], "Evolve Golbat (friendship)"),
    d(50, "Diglett", ["Su", "Mo"], "Verdant Cavern, Diglett's Tunnel (Alolan form)"),
    d(51, "Dugtrio", ["Su", "Mo"], "Evolve Diglett (Alolan form)"),
    d(21, "Spearow", ["Su", "Mo"], "Route 3"),
    d(22, "Fearow", ["Su", "Mo"], "Route 10, Mount Hokulani, evolve Spearow"),
    d(56, "Mankey", ["Su", "Mo"], "Route 3"),
    d(57, "Primeape", ["Su", "Mo"], "Evolve Mankey"),
    d(225, "Delibird", ["Su", "Mo"], "Route 3 (rare)"),
    d(701, "Hawlucha", ["Su", "Mo"], "Route 3"),
    d(742, "Cutiefly", ["Su", "Mo"], "Routes 2, 3, Melemele Meadow"),
    d(743, "Ribombee", ["Su", "Mo"], "Poni Meadow, evolve Cutiefly"),
    d(741, "Oricorio", ["Su", "Mo"], "Melemele Meadow, various meadows (form depends on nectar)"),
    d(174, "Igglybuff", ["Su", "Mo"], "Route 4, 6 (SOS)"),
    d(39, "Jigglypuff", ["Su", "Mo"], "Route 6, evolve Igglybuff (friendship)"),
    d(40, "Wigglytuff", ["Su", "Mo"], "Evolve Jigglypuff (Moon Stone)"),
    d(128, "Tauros", ["Su", "Mo"], "Paniola Ranch"),
    d(241, "Miltank", ["Su", "Mo"], "Paniola Ranch"),
    d(283, "Surskit", ["Su", "Mo"], "Brooklet Hill"),
    d(284, "Masquerain", ["Su", "Mo"], "Evolve Surskit"),

    // ── Akala Island ────────────────────────────────
    d(506, "Lillipup", ["Su", "Mo"], "Routes 4, 6"),
    d(507, "Herdier", ["Su", "Mo"], "Route 5, evolve Lillipup"),
    d(508, "Stoutland", ["Su", "Mo"], "Poni Plains, evolve Herdier"),
    d(133, "Eevee", ["Su", "Mo"], "Route 4, 6 (rare)"),
    d(134, "Vaporeon", ["Su", "Mo"], "Evolve Eevee (Water Stone)"),
    d(135, "Jolteon", ["Su", "Mo"], "Evolve Eevee (Thunder Stone)"),
    d(136, "Flareon", ["Su", "Mo"], "Evolve Eevee (Fire Stone)"),
    d(196, "Espeon", ["Su", "Mo"], "Evolve Eevee (friendship, day)"),
    d(197, "Umbreon", ["Su", "Mo"], "Evolve Eevee (friendship, night)"),
    d(470, "Leafeon", ["Su", "Mo"], "Evolve Eevee (level up at Lush Jungle)"),
    d(471, "Glaceon", ["Su", "Mo"], "Evolve Eevee (level up at Mount Lanakila)"),
    d(700, "Sylveon", ["Su", "Mo"], "Evolve Eevee (Affection + Fairy move)"),
    d(749, "Mudbray", ["Su", "Mo"], "Routes 4, 6, 12, Paniola Ranch"),
    d(750, "Mudsdale", ["Su", "Mo"], "Poni Plains, evolve Mudbray"),
    d(174, "Igglybuff", ["Su", "Mo"], "Route 4, 6 (SOS)"),
    d(46, "Paras", ["Su", "Mo"], "Route 11, Lush Jungle"),
    d(47, "Parasect", ["Su", "Mo"], "Evolve Paras"),
    d(60, "Poliwag", ["Su", "Mo"], "Brooklet Hill, Malie Garden (fishing)"),
    d(61, "Poliwhirl", ["Su", "Mo"], "Malie Garden, evolve Poliwag"),
    d(62, "Poliwrath", ["Su", "Mo"], "Evolve Poliwhirl (Water Stone)"),
    d(186, "Politoed", ["Su", "Mo"], "Trade Poliwhirl with King's Rock"),
    d(746, "Wishiwashi", ["Su", "Mo"], "Brooklet Hill, various fishing spots"),
    d(118, "Goldeen", ["Su", "Mo"], "Brooklet Hill, various fishing spots"),
    d(119, "Seaking", ["Su", "Mo"], "Evolve Goldeen"),
    d(349, "Feebas", ["Su", "Mo"], "Brooklet Hill (fishing, rare)"),
    d(350, "Milotic", ["Su", "Mo"], "Evolve Feebas (trade with Prism Scale)"),
    d(751, "Dewpider", ["Su", "Mo"], "Brooklet Hill"),
    d(752, "Araquanid", ["Su", "Mo"], "Malie City Outer Cape, evolve Dewpider"),
    d(753, "Fomantis", ["Su", "Mo"], "Routes 5, 8, Lush Jungle"),
    d(754, "Lurantis", ["Su", "Mo"], "Evolve Fomantis (level up in day)"),
    d(755, "Morelull", ["Su", "Mo"], "Lush Jungle, Brooklet Hill"),
    d(756, "Shiinotic", ["Su", "Mo"], "Evolve Morelull"),
    d(46, "Paras", ["Su", "Mo"], "Lush Jungle"),
    d(761, "Bounsweet", ["Su", "Mo"], "Lush Jungle"),
    d(762, "Steenee", ["Su", "Mo"], "Evolve Bounsweet"),
    d(763, "Tsareena", ["Su", "Mo"], "Evolve Steenee (learn Stomp)"),
    d(764, "Comfey", ["Su", "Mo"], "Lush Jungle, Poni Plains (rare)"),
    d(766, "Passimian", ["Su"], "Lush Jungle"),
    d(765, "Oranguru", ["Mo"], "Lush Jungle"),
    d(104, "Cubone", ["Su", "Mo"], "Wela Volcano Park"),
    d(105, "Marowak", ["Su", "Mo"], "Evolve Cubone (night, Alolan form Fire/Ghost)"),
    d(115, "Kangaskhan", ["Su", "Mo"], "Wela Volcano Park"),
    d(240, "Magby", ["Su", "Mo"], "Wela Volcano Park"),
    d(126, "Magmar", ["Su", "Mo"], "Evolve Magby"),
    d(467, "Magmortar", ["Su", "Mo"], "Trade Magmar with Magmarizer"),
    d(636, "Larvesta", ["Su", "Mo"], "Wela Volcano Park (rare)"),
    d(637, "Volcarona", ["Su", "Mo"], "Evolve Larvesta"),
    d(757, "Salandit", ["Su", "Mo"], "Wela Volcano Park, Route 8"),
    d(758, "Salazzle", ["Su", "Mo"], "Evolve female Salandit"),
    d(662, "Fletchinder", ["Su", "Mo"], "Wela Volcano Park, Route 8"),
    d(661, "Fletchling", ["Su", "Mo"], "Route 8 (SOS call)"),
    d(663, "Talonflame", ["Su", "Mo"], "Evolve Fletchinder"),
    d(759, "Stufful", ["Su", "Mo"], "Route 8, Akala Outskirts"),
    d(760, "Bewear", ["Su", "Mo"], "Poni Gauntlet, evolve Stufful"),
    d(246, "Larvitar", ["Su", "Mo"], "Diglett's Tunnel (SOS)"),
    d(247, "Pupitar", ["Su", "Mo"], "Evolve Larvitar"),
    d(248, "Tyranitar", ["Su", "Mo"], "Evolve Pupitar"),
    d(72, "Tentacool", ["Su", "Mo"], "Various surfing routes"),
    d(73, "Tentacruel", ["Su", "Mo"], "Evolve Tentacool"),
    d(456, "Finneon", ["Su", "Mo"], "Various fishing routes"),
    d(457, "Lumineon", ["Su", "Mo"], "Evolve Finneon"),
    d(278, "Wingull", ["Su", "Mo"], "Various surfing routes"),
    d(279, "Pelipper", ["Su", "Mo"], "Evolve Wingull"),
    d(120, "Staryu", ["Su", "Mo"], "Route 7, Hano Beach (fishing)"),
    d(121, "Starmie", ["Su", "Mo"], "Evolve Staryu (Water Stone)"),
    d(771, "Pyukumuku", ["Su", "Mo"], "Route 7, Hano Beach"),
    d(129, "Magikarp", ["Su", "Mo"], "Various fishing routes"),
    d(130, "Gyarados", ["Su", "Mo"], "Evolve Magikarp"),
    d(746, "Wishiwashi", ["Su", "Mo"], "Various fishing routes"),
    d(594, "Alomomola", ["Su", "Mo"], "Routes 14, 15 (surfing SOS)"),
    d(370, "Luvdisc", ["Su", "Mo"], "Route 9 (fishing)"),
    d(222, "Corsola", ["Su", "Mo"], "Route 9, Melemele Sea (fishing)"),
    d(747, "Mareanie", ["Su", "Mo"], "Route 9 (SOS from Corsola)"),
    d(748, "Toxapex", ["Su", "Mo"], "Evolve Mareanie"),
    d(90, "Shellder", ["Su", "Mo"], "Route 9, Kala'e Bay (fishing)"),
    d(91, "Cloyster", ["Su", "Mo"], "Evolve Shellder (Water Stone)"),
    d(86, "Seel", ["Su", "Mo"], "Route 15 (surfing, rare)"),
    d(87, "Dewgong", ["Su", "Mo"], "Evolve Seel"),
    d(147, "Dratini", ["Su", "Mo"], "Poni Gauntlet, Poni Meadow (fishing)"),
    d(148, "Dragonair", ["Su", "Mo"], "Poni Gauntlet (fishing, rare), evolve Dratini"),
    d(149, "Dragonite", ["Su", "Mo"], "Evolve Dragonair"),
    d(131, "Lapras", ["Su", "Mo"], "Poni Wilds (surfing)"),
    d(320, "Wailmer", ["Su", "Mo"], "Route 15, Seafolk Village (surfing)"),
    d(321, "Wailord", ["Su", "Mo"], "Evolve Wailmer"),
    d(319, "Sharpedo", ["Su", "Mo"], "Route 15, Poni Breaker Coast (surfing)"),
    d(318, "Carvanha", ["Su", "Mo"], "Route 15 (fishing, SOS)"),
    d(369, "Relicanth", ["Su", "Mo"], "Poni Breaker Coast (fishing, rare)"),
    d(690, "Skrelp", ["Su", "Mo"], "Route 15 (fishing, SOS)"),
    d(691, "Dragalge", ["Su", "Mo"], "Evolve Skrelp"),
    d(692, "Clauncher", ["Su", "Mo"], "Route 15 (fishing, SOS)"),
    d(693, "Clawitzer", ["Su", "Mo"], "Evolve Clauncher"),

    // ── Ula'ula Island ──────────────────────────────
    d(54, "Psyduck", ["Su", "Mo"], "Malie Garden, Brooklet Hill (surfing)"),
    d(55, "Golduck", ["Su", "Mo"], "Evolve Psyduck"),
    d(239, "Elekid", ["Su"], "Route 12"),
    d(125, "Electabuzz", ["Su"], "Evolve Elekid"),
    d(466, "Electivire", ["Su"], "Trade Electabuzz with Electirizer"),
    d(240, "Magby", ["Mo"], "Route 12"),
    d(74, "Geodude", ["Su", "Mo"], "Route 12, various caves (Alolan form)"),
    d(75, "Graveler", ["Su", "Mo"], "Evolve Geodude (Alolan form)"),
    d(76, "Golem", ["Su", "Mo"], "Trade evolve Graveler (Alolan form)"),
    d(324, "Torkoal", ["Su", "Mo"], "Route 12"),
    d(227, "Skarmory", ["Su", "Mo"], "Route 10, Mount Hokulani"),
    d(674, "Pancham", ["Su", "Mo"], "Route 10, 11"),
    d(675, "Pangoro", ["Su", "Mo"], "Evolve Pancham (with Dark-type in party)"),
    d(774, "Minior", ["Su", "Mo"], "Mount Hokulani"),
    d(374, "Beldum", ["Su", "Mo"], "Mount Hokulani (rare)"),
    d(375, "Metang", ["Su", "Mo"], "Evolve Beldum"),
    d(376, "Metagross", ["Su", "Mo"], "Evolve Metang"),
    d(775, "Komala", ["Su", "Mo"], "Route 11"),
    d(776, "Turtonator", ["Su"], "Blush Mountain"),
    d(780, "Drampa", ["Mo"], "Mount Lanakila, Lush Jungle (SOS)"),
    d(777, "Togedemaru", ["Su", "Mo"], "Blush Mountain"),
    d(239, "Elekid", ["Su", "Mo"], "Blush Mountain (SOS)"),
    d(702, "Dedenne", ["Su", "Mo"], "Blush Mountain"),
    d(737, "Charjabug", ["Su", "Mo"], "Blush Mountain, evolve Grubbin"),
    d(551, "Sandile", ["Su", "Mo"], "Haina Desert"),
    d(552, "Krokorok", ["Su", "Mo"], "Evolve Sandile"),
    d(553, "Krookodile", ["Su", "Mo"], "Evolve Krokorok"),
    d(328, "Trapinch", ["Su", "Mo"], "Haina Desert"),
    d(329, "Vibrava", ["Su", "Mo"], "Evolve Trapinch"),
    d(330, "Flygon", ["Su", "Mo"], "Evolve Vibrava"),
    d(443, "Gible", ["Su", "Mo"], "Haina Desert (SOS)"),
    d(444, "Gabite", ["Su", "Mo"], "Evolve Gible"),
    d(445, "Garchomp", ["Su", "Mo"], "Evolve Gabite"),
    d(769, "Sandygast", ["Su", "Mo"], "Route 14, Hano Beach"),
    d(770, "Palossand", ["Su", "Mo"], "Evolve Sandygast"),
    d(779, "Bruxish", ["Su", "Mo"], "Route 13, 14, 15 (surfing/fishing)"),
    d(778, "Mimikyu", ["Su", "Mo"], "Thrifty Megamart (Abandoned)"),
    d(200, "Misdreavus", ["Su", "Mo"], "Thrifty Megamart, Hau'oli Cemetery"),
    d(429, "Mismagius", ["Su", "Mo"], "Evolve Misdreavus (Dusk Stone)"),
    d(302, "Sableye", ["Su", "Mo"], "Vast Poni Canyon (SOS)"),
    d(353, "Shuppet", ["Su", "Mo"], "Thrifty Megamart"),
    d(354, "Banette", ["Su", "Mo"], "Evolve Shuppet"),
    d(592, "Frillish", ["Su", "Mo"], "Route 14 (surfing)"),
    d(593, "Jellicent", ["Su", "Mo"], "Evolve Frillish"),
    d(708, "Phantump", ["Su", "Mo"], "Memorial Hill"),
    d(709, "Trevenant", ["Su", "Mo"], "Trade evolve Phantump"),
    d(422, "Shellos", ["Su", "Mo"], "Route 14, 15 (surfing)"),
    d(423, "Gastrodon", ["Su", "Mo"], "Evolve Shellos"),
    d(198, "Murkrow", ["Su", "Mo"], "Route 10 (night)"),
    d(430, "Honchkrow", ["Su", "Mo"], "Evolve Murkrow (Dusk Stone)"),
    d(447, "Riolu", ["Su", "Mo"], "Poni Grove"),
    d(448, "Lucario", ["Su", "Mo"], "Evolve Riolu (friendship, day)"),
    d(359, "Absol", ["Su", "Mo"], "Mount Lanakila, Tapu Village"),
    d(361, "Snorunt", ["Su", "Mo"], "Mount Lanakila, Tapu Village"),
    d(362, "Glalie", ["Su", "Mo"], "Evolve Snorunt"),
    d(478, "Froslass", ["Su", "Mo"], "Evolve female Snorunt (Dawn Stone)"),
    d(215, "Sneasel", ["Su", "Mo"], "Mount Lanakila"),
    d(461, "Weavile", ["Su", "Mo"], "Evolve Sneasel (Razor Claw, night)"),
    d(582, "Vanillite", ["Su", "Mo"], "Mount Lanakila, Tapu Village"),
    d(583, "Vanillish", ["Su", "Mo"], "Evolve Vanillite"),
    d(584, "Vanilluxe", ["Su", "Mo"], "Evolve Vanillish"),
    d(37, "Vulpix", ["Su", "Mo"], "Tapu Village, Mount Lanakila (Alolan form)"),
    d(38, "Ninetales", ["Su", "Mo"], "Evolve Vulpix (Ice Stone, Alolan form)"),
    d(27, "Sandshrew", ["Su", "Mo"], "Tapu Village, Mount Lanakila (Alolan form)"),
    d(28, "Sandslash", ["Su", "Mo"], "Evolve Sandshrew (Ice Stone, Alolan form)"),
    d(209, "Snubbull", ["Su", "Mo"], "Route 14, Poni Gauntlet"),
    d(210, "Granbull", ["Su", "Mo"], "Poni Gauntlet, evolve Snubbull"),
    d(768, "Golisopod", ["Su", "Mo"], "Evolve Wimpod"),
    d(767, "Wimpod", ["Su", "Mo"], "Route 8"),
    d(170, "Chinchou", ["Su", "Mo"], "Route 8, 14 (fishing)"),
    d(171, "Lanturn", ["Su", "Mo"], "Evolve Chinchou"),

    // ── Poni Island ─────────────────────────────────
    d(102, "Exeggcute", ["Su", "Mo"], "Exeggutor Island"),
    d(103, "Exeggutor", ["Su", "Mo"], "Evolve Exeggcute (Leaf Stone, Alolan form)"),
    d(782, "Jangmo-o", ["Su", "Mo"], "Vast Poni Canyon"),
    d(783, "Hakamo-o", ["Su", "Mo"], "Vast Poni Canyon, evolve Jangmo-o"),
    d(784, "Kommo-o", ["Su", "Mo"], "Vast Poni Canyon (SOS), evolve Hakamo-o"),
    d(703, "Carbink", ["Su", "Mo"], "Vast Poni Canyon"),
    d(525, "Boldore", ["Su", "Mo"], "Vast Poni Canyon"),
    d(524, "Roggenrola", ["Su", "Mo"], "Vast Poni Canyon (SOS)"),
    d(526, "Gigalith", ["Su", "Mo"], "Trade evolve Boldore"),
    d(67, "Machoke", ["Su", "Mo"], "Vast Poni Canyon"),
    d(66, "Machop", ["Su", "Mo"], "Vast Poni Canyon (SOS)"),
    d(68, "Machamp", ["Su", "Mo"], "Trade evolve Machoke"),
    d(744, "Rockruff", ["Su", "Mo"], "Route 1, Vast Poni Canyon, Ten Carat Hill"),
    d(745, "Lycanroc", ["Su", "Mo"], "Vast Poni Canyon, evolve Rockruff (Midday in Sun, Midnight in Moon)"),
    d(327, "Spinda", ["Su", "Mo"], "Route 1 (SOS from Bonsly)"),
    d(132, "Ditto", ["Su", "Mo"], "Mount Hokulani, Konikoni City (SOS)"),
    d(113, "Chansey", ["Su", "Mo"], "Poni Plains (SOS)"),
    d(242, "Blissey", ["Su", "Mo"], "Evolve Chansey (friendship)"),
    d(137, "Porygon", ["Su", "Mo"], "Gift from Aether House"),
    d(233, "Porygon2", ["Su", "Mo"], "Trade Porygon with Up-Grade"),
    d(474, "Porygon-Z", ["Su", "Mo"], "Trade Porygon2 with Dubious Disc"),
    d(143, "Snorlax", ["Su", "Mo"], "Route 1 (SOS from Munchlax)"),
    d(446, "Munchlax", ["Su", "Mo"], "Route 1 (SOS)"),
    d(127, "Pinsir", ["Su", "Mo"], "Poni Plains"),
    d(108, "Lickitung", ["Su", "Mo"], "Route 6 (SOS)"),
    d(463, "Lickilicky", ["Su", "Mo"], "Evolve Lickitung (learn Rollout)"),
    d(190, "Aipom", ["Su", "Mo"], "Route 2, Poni Plains (SOS)"),
    d(424, "Ambipom", ["Su", "Mo"], "Evolve Aipom (learn Double Hit)"),

    // ── Fossil Pokémon ──────────────────────────────
    d(408, "Cranidos", ["Su", "Mo"], "Revive Skull Fossil (Olivia's shop)"),
    d(409, "Rampardos", ["Su", "Mo"], "Evolve Cranidos"),
    d(564, "Tirtouga", ["Su", "Mo"], "Revive Cover Fossil (Olivia's shop)"),
    d(565, "Carracosta", ["Su", "Mo"], "Evolve Tirtouga"),
    d(142, "Aerodactyl", ["Su", "Mo"], "Revive Old Amber (Olivia's shop)"),
    d(138, "Omanyte", ["Su", "Mo"], "Revive Helix Fossil (Olivia's shop)"),
    d(139, "Omastar", ["Su", "Mo"], "Evolve Omanyte"),
    d(140, "Kabuto", ["Su", "Mo"], "Revive Dome Fossil (Olivia's shop)"),
    d(141, "Kabutops", ["Su", "Mo"], "Evolve Kabuto"),
    d(345, "Lileep", ["Su", "Mo"], "Revive Root Fossil (Olivia's shop)"),
    d(346, "Cradily", ["Su", "Mo"], "Evolve Lileep"),
    d(347, "Anorith", ["Su", "Mo"], "Revive Claw Fossil (Olivia's shop)"),
    d(348, "Armaldo", ["Su", "Mo"], "Evolve Anorith"),
    d(410, "Shieldon", ["Su", "Mo"], "Revive Armor Fossil (Olivia's shop)"),
    d(411, "Bastiodon", ["Su", "Mo"], "Evolve Shieldon"),

    // ── Gift & Special Pokémon ──────────────────────
    d(772, "Type: Null", ["Su", "Mo"], "Gift from Gladion (post-game)"),
    d(773, "Silvally", ["Su", "Mo"], "Evolve Type: Null (friendship)"),
    d(137, "Porygon", ["Su", "Mo"], "Gift from Aether House"),

    // ── Version Exclusive Pokémon ───────────────────
    // Sun exclusives
    d(546, "Cottonee", ["Su"], "Malie Garden, Poni Meadow"),
    d(547, "Whimsicott", ["Su"], "Evolve Cottonee (Sun Stone)"),
    d(627, "Rufflet", ["Su"], "Route 3, Poni Plains"),
    d(628, "Braviary", ["Su"], "Evolve Rufflet"),
    d(766, "Passimian", ["Su"], "Lush Jungle"),
    d(776, "Turtonator", ["Su"], "Blush Mountain"),
    // Moon exclusives
    d(548, "Petilil", ["Mo"], "Malie Garden, Poni Meadow"),
    d(549, "Lilligant", ["Mo"], "Evolve Petilil (Sun Stone)"),
    d(629, "Vullaby", ["Mo"], "Route 3, Poni Plains"),
    d(630, "Mandibuzz", ["Mo"], "Evolve Vullaby"),
    d(765, "Oranguru", ["Mo"], "Lush Jungle"),
    d(780, "Drampa", ["Mo"], "Mount Lanakila"),

    // ── Miscellaneous catches ───────────────────────
    d(79, "Slowpoke", ["Su", "Mo"], "Route 15, Kala'e Bay"),
    d(80, "Slowbro", ["Su", "Mo"], "Evolve Slowpoke"),
    d(199, "Slowking", ["Su", "Mo"], "Trade Slowpoke with King's Rock"),
    d(550, "Basculin", ["Su", "Mo"], "Malie Garden (fishing), Brooklet Hill"),
    d(341, "Corphish", ["Su", "Mo"], "Vast Poni Canyon (fishing)"),
    d(342, "Crawdaunt", ["Su", "Mo"], "Evolve Corphish"),
    d(445, "Garchomp", ["Su", "Mo"], "Evolve Gabite"),
    d(570, "Zorua", ["Su", "Mo"], "Trainer's School (gift in some events)"),
    d(571, "Zoroark", ["Su", "Mo"], "Evolve Zorua"),
    d(35, "Clefairy", ["Su", "Mo"], "Mount Hokulani (SOS)"),
    d(36, "Clefable", ["Su", "Mo"], "Evolve Clefairy (Moon Stone)"),
    d(173, "Cleffa", ["Su", "Mo"], "Mount Hokulani (SOS)"),
    d(440, "Happiny", ["Su", "Mo"], "Route 1, Poni Plains (SOS)"),
    d(539, "Sawk", ["Su", "Mo"], "Route 11 (SOS from Machop)"),
    d(538, "Throh", ["Su", "Mo"], "Route 11 (SOS from Machop)"),
    d(559, "Scraggy", ["Su", "Mo"], "Route 16, Route 17"),
    d(560, "Scrafty", ["Su", "Mo"], "Evolve Scraggy"),
    d(114, "Tangela", ["Su", "Mo"], "Poni Plains"),
    d(465, "Tangrowth", ["Su", "Mo"], "Evolve Tangela (learn Ancient Power)"),
    d(704, "Goomy", ["Su", "Mo"], "Lush Jungle (rain, SOS)"),
    d(705, "Sliggoo", ["Su", "Mo"], "Evolve Goomy"),
    d(706, "Goodra", ["Su", "Mo"], "Evolve Sliggoo (level up in rain)"),
    d(174, "Igglybuff", ["Su", "Mo"], "Route 4 (SOS)"),
    d(108, "Lickitung", ["Su", "Mo"], "Route 6 (SOS)"),
    d(299, "Nosepass", ["Su", "Mo"], "Akala Outskirts"),
    d(476, "Probopass", ["Su", "Mo"], "Evolve Nosepass (level up at Vast Poni Canyon)"),
    d(624, "Pawniard", ["Su", "Mo"], "Route 17"),
    d(625, "Bisharp", ["Su", "Mo"], "Evolve Pawniard"),
    d(587, "Emolga", ["Su", "Mo"], "Poni Plains"),
    d(239, "Elekid", ["Su"], "Route 12"),
    d(552, "Krokorok", ["Su", "Mo"], "Haina Desert (SOS)"),
    d(781, "Dhelmise", ["Su", "Mo"], "Seafolk Village (fishing, rare)"),
    d(585, "Deerling", ["Su", "Mo"], "Route 16 (SOS)"),
    d(586, "Sawsbuck", ["Su", "Mo"], "Evolve Deerling"),

    // ── Legendary Pokémon ───────────────────────────
    d(785, "Tapu Koko", ["Su", "Mo"], "Ruins of Conflict (Lv. 60, post-game)"),
    d(786, "Tapu Lele", ["Su", "Mo"], "Ruins of Life (Lv. 60, post-game)"),
    d(787, "Tapu Bulu", ["Su", "Mo"], "Ruins of Abundance (Lv. 60, post-game)"),
    d(788, "Tapu Fini", ["Su", "Mo"], "Ruins of Hope (Lv. 60, post-game)"),
    d(789, "Cosmog", ["Su", "Mo"], "Gift at alternate world Altar (post-game)"),
    d(790, "Cosmoem", ["Su", "Mo"], "Evolve Cosmog"),
    d(791, "Solgaleo", ["Su"], "Altar of the Sunne (Lv. 55)"),
    d(792, "Lunala", ["Mo"], "Altar of the Moone (Lv. 55)"),
    d(800, "Necrozma", ["Su", "Mo"], "Ten Carat Hill (Lv. 75, post-game)"),
    d(718, "Zygarde", ["Su", "Mo"], "Assemble from Cells/Cores at Route 16"),

    // ── Ultra Beasts ────────────────────────────────
    d(793, "Nihilego", ["Su", "Mo"], "Diglett's Tunnel / Wela Volcano Park (post-game, Lv. 55)"),
    d(794, "Buzzwole", ["Su"], "Melemele Meadow (post-game, Lv. 65)"),
    d(795, "Pheromosa", ["Mo"], "Verdant Cavern (post-game, Lv. 60)"),
    d(796, "Xurkitree", ["Su", "Mo"], "Lush Jungle / Memorial Hill (post-game, Lv. 65)"),
    d(797, "Celesteela", ["Mo"], "Haina Desert (post-game, Lv. 65)"),
    d(798, "Kartana", ["Su"], "Malie Garden / Route 17 (post-game, Lv. 60)"),
    d(799, "Guzzlord", ["Su", "Mo"], "Resolution Cave (post-game, Lv. 70)"),
  ],
};
