import type { GameDex, GameDexEntry } from "../game-dex";

const d = (
  pokemonId: number,
  name: string,
  versions: string[],
  method?: string
): GameDexEntry => ({ pokemonId, name, versions, method });

/* ==============================================================
 *  Pokemon Sword & Shield -- Galar Pokedex (~400 Pokemon)
 *  Versions: Sw = Sword, Sh = Shield
 *  Includes Galarian forms, new Gen 8 Pokemon, and returning
 *  favorites. Version exclusives are marked accordingly.
 * ============================================================== */
export const SWORD_SHIELD_DEX: GameDex = {
  slug: "sword-shield",
  versionTags: ["Sw", "Sh"],
  pokemon: [
    // ── Starters & Evolutions ──────────────────────────
    d(810, "Grookey", ["Sw", "Sh"], "Starter from Leon"),
    d(811, "Thwackey", ["Sw", "Sh"], "Evolve Grookey"),
    d(812, "Rillaboom", ["Sw", "Sh"], "Evolve Thwackey"),
    d(813, "Scorbunny", ["Sw", "Sh"], "Starter from Leon"),
    d(814, "Raboot", ["Sw", "Sh"], "Evolve Scorbunny"),
    d(815, "Cinderace", ["Sw", "Sh"], "Evolve Raboot"),
    d(816, "Sobble", ["Sw", "Sh"], "Starter from Leon"),
    d(817, "Drizzile", ["Sw", "Sh"], "Evolve Sobble"),
    d(818, "Inteleon", ["Sw", "Sh"], "Evolve Drizzile"),

    // ── Early Routes ───────────────────────────────────
    d(819, "Skwovet", ["Sw", "Sh"], "Route 1, Route 2"),
    d(820, "Greedent", ["Sw", "Sh"], "Route 1 (overworld), evolve Skwovet"),
    d(821, "Rookidee", ["Sw", "Sh"], "Route 1, Route 2, Wild Area"),
    d(822, "Corvisquire", ["Sw", "Sh"], "Route 3, Wild Area, evolve Rookidee"),
    d(823, "Corviknight", ["Sw", "Sh"], "Route 7, Wild Area, evolve Corvisquire"),
    d(824, "Blipbug", ["Sw", "Sh"], "Route 1, Route 2"),
    d(825, "Dottler", ["Sw", "Sh"], "Route 5, Wild Area, evolve Blipbug"),
    d(826, "Orbeetle", ["Sw", "Sh"], "Wild Area, evolve Dottler"),
    d(827, "Nickit", ["Sw", "Sh"], "Route 1, Route 2"),
    d(828, "Thievul", ["Sw", "Sh"], "Route 7, Wild Area, evolve Nickit"),
    d(829, "Gossifleur", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(830, "Eldegoss", ["Sw", "Sh"], "Route 5, Wild Area, evolve Gossifleur"),
    d(831, "Wooloo", ["Sw", "Sh"], "Route 1, Route 3"),
    d(832, "Dubwool", ["Sw", "Sh"], "Route 7, evolve Wooloo"),
    d(833, "Chewtle", ["Sw", "Sh"], "Route 2, Wild Area"),
    d(834, "Drednaw", ["Sw", "Sh"], "Route 6, Wild Area, evolve Chewtle"),
    d(835, "Yamper", ["Sw", "Sh"], "Route 2, Route 4"),
    d(836, "Boltund", ["Sw", "Sh"], "Route 7, Wild Area, evolve Yamper"),

    // ── Rolycoly line ──────────────────────────────────
    d(837, "Rolycoly", ["Sw", "Sh"], "Route 3, Galar Mine"),
    d(838, "Carkol", ["Sw", "Sh"], "Galar Mine No. 2, evolve Rolycoly"),
    d(839, "Coalossal", ["Sw", "Sh"], "Wild Area, evolve Carkol"),

    // ── Applin line (version split) ────────────────────
    d(840, "Applin", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(841, "Flapple", ["Sw"], "Evolve Applin (Tart Apple - Sword)"),
    d(842, "Appletun", ["Sh"], "Evolve Applin (Sweet Apple - Shield)"),

    // ── Silicobra line ─────────────────────────────────
    d(843, "Silicobra", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(844, "Sandaconda", ["Sw", "Sh"], "Wild Area, evolve Silicobra"),

    // ── Cramorant ──────────────────────────────────────
    d(845, "Cramorant", ["Sw", "Sh"], "Route 9, Wild Area"),

    // ── Arrokuda line ──────────────────────────────────
    d(846, "Arrokuda", ["Sw", "Sh"], "Route 2, Route 9 (Fishing)"),
    d(847, "Barraskewda", ["Sw", "Sh"], "Route 9 (Fishing), evolve Arrokuda"),

    // ── Toxel line ─────────────────────────────────────
    d(848, "Toxel", ["Sw", "Sh"], "Route 5 (Gift), Route 7, Wild Area"),
    d(849, "Toxtricity", ["Sw", "Sh"], "Evolve Toxel (form depends on nature)"),

    // ── Sizzlipede line ────────────────────────────────
    d(850, "Sizzlipede", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(851, "Centiskorch", ["Sw", "Sh"], "Wild Area, evolve Sizzlipede"),

    // ── Clobbopus line ─────────────────────────────────
    d(852, "Clobbopus", ["Sw", "Sh"], "Route 9, Wild Area"),
    d(853, "Grapploct", ["Sw", "Sh"], "Wild Area, evolve Clobbopus"),

    // ── Sinistea line ──────────────────────────────────
    d(854, "Sinistea", ["Sw", "Sh"], "Glimwood Tangle, Wild Area"),
    d(855, "Polteageist", ["Sw", "Sh"], "Evolve Sinistea (Cracked/Chipped Pot)"),

    // ── Hatenna line ───────────────────────────────────
    d(856, "Hatenna", ["Sw", "Sh"], "Route 5, Glimwood Tangle"),
    d(857, "Hattrem", ["Sw", "Sh"], "Glimwood Tangle, evolve Hatenna"),
    d(858, "Hatterene", ["Sw", "Sh"], "Wild Area, evolve Hattrem"),

    // ── Impidimp line ──────────────────────────────────
    d(859, "Impidimp", ["Sw", "Sh"], "Glimwood Tangle, Wild Area"),
    d(860, "Morgrem", ["Sw", "Sh"], "Glimwood Tangle, evolve Impidimp"),
    d(861, "Grimmsnarl", ["Sw", "Sh"], "Wild Area, evolve Morgrem"),

    // ── Galarian Obstagoon line ────────────────────────
    d(263, "Zigzagoon", ["Sw", "Sh"], "Route 2, Route 3, Wild Area (Galarian form)"),
    d(264, "Linoone", ["Sw", "Sh"], "Route 7, Wild Area, evolve Zigzagoon (Galarian form)"),
    d(862, "Obstagoon", ["Sw", "Sh"], "Wild Area, evolve Galarian Linoone (night, Lv35+)"),

    // ── Galarian Corsola / Cursola (Shield) ────────────
    d(222, "Corsola", ["Sh"], "Route 8, Wild Area (Galarian form - Shield)"),
    d(864, "Cursola", ["Sh"], "Evolve Galarian Corsola (Shield)"),

    // ── Sirfetch'd (Sword) ─────────────────────────────
    d(83, "Farfetch'd", ["Sw"], "Route 5, Wild Area (Galarian form - Sword)"),
    d(865, "Sirfetch'd", ["Sw"], "Evolve Galarian Farfetch'd (3 crits in one battle - Sword)"),

    // ── Mr. Rime line ──────────────────────────────────
    d(122, "Mr. Mime", ["Sw", "Sh"], "Route 10, Wild Area (Galarian form)"),
    d(439, "Mime Jr.", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(866, "Mr. Rime", ["Sw", "Sh"], "Evolve Galarian Mr. Mime (Lv42+)"),

    // ── Runerigus ──────────────────────────────────────
    d(562, "Yamask", ["Sw", "Sh"], "Route 6 (Galarian form)"),
    d(867, "Runerigus", ["Sw", "Sh"], "Evolve Galarian Yamask (take 49+ damage, walk under stone arch)"),

    // ── Milcery / Alcremie ─────────────────────────────
    d(868, "Milcery", ["Sw", "Sh"], "Route 4, Wild Area"),
    d(869, "Alcremie", ["Sw", "Sh"], "Evolve Milcery (spin with Sweet item)"),

    // ── Falinks ────────────────────────────────────────
    d(870, "Falinks", ["Sw", "Sh"], "Route 8, Wild Area"),

    // ── Pincurchin ─────────────────────────────────────
    d(871, "Pincurchin", ["Sw", "Sh"], "Route 9, Wild Area"),

    // ── Snom / Frosmoth ────────────────────────────────
    d(872, "Snom", ["Sw", "Sh"], "Route 8, Route 10, Wild Area"),
    d(873, "Frosmoth", ["Sw", "Sh"], "Evolve Snom (high friendship, night)"),

    // ── Stonjourner (Sword) ────────────────────────────
    d(874, "Stonjourner", ["Sw"], "Route 10, Wild Area (Sword)"),

    // ── Eiscue (Shield) ────────────────────────────────
    d(875, "Eiscue", ["Sh"], "Route 10, Wild Area (Shield)"),

    // ── Indeedee ───────────────────────────────────────
    d(876, "Indeedee", ["Sw", "Sh"], "Glimwood Tangle, Wild Area (Male-Sw, Female-Sh)"),

    // ── Morpeko ────────────────────────────────────────
    d(877, "Morpeko", ["Sw", "Sh"], "Route 7, Route 9, Wild Area"),

    // ── Cufant / Copperajah ────────────────────────────
    d(878, "Cufant", ["Sw", "Sh"], "Route 8, Wild Area"),
    d(879, "Copperajah", ["Sw", "Sh"], "Wild Area, evolve Cufant"),

    // ── Fossil Pokemon ─────────────────────────────────
    d(880, "Dracozolt", ["Sw", "Sh"], "Fossil restoration (Fossilized Bird + Drake)"),
    d(881, "Arctozolt", ["Sw", "Sh"], "Fossil restoration (Fossilized Bird + Dino)"),
    d(882, "Dracovish", ["Sw", "Sh"], "Fossil restoration (Fossilized Fish + Drake)"),
    d(883, "Arctovish", ["Sw", "Sh"], "Fossil restoration (Fossilized Fish + Dino)"),

    // ── Duraludon ──────────────────────────────────────
    d(884, "Duraludon", ["Sw", "Sh"], "Route 10, Wild Area"),

    // ── Dreepy line ────────────────────────────────────
    d(885, "Dreepy", ["Sw", "Sh"], "Lake of Outrage, Wild Area (rare)"),
    d(886, "Drakloak", ["Sw", "Sh"], "Lake of Outrage, evolve Dreepy"),
    d(887, "Dragapult", ["Sw", "Sh"], "Evolve Drakloak"),

    // ── Legendaries ────────────────────────────────────
    d(888, "Zacian", ["Sw"], "Post-game Energy Plant (Sword, Lv70)"),
    d(889, "Zamazenta", ["Sh"], "Post-game Energy Plant (Shield, Lv70)"),
    d(890, "Eternatus", ["Sw", "Sh"], "Energy Plant story battle (Lv60, guaranteed catch)"),

    // ── Mythicals ──────────────────────────────────────
    d(891, "Kubfu", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(892, "Urshifu", ["Sw", "Sh"], "Evolve Kubfu (Tower of Darkness/Waters)"),
    d(893, "Zarude", ["Sw", "Sh"], "Event distribution"),

    // ── Type: Null & Silvally ──────────────────────────
    d(772, "Type: Null", ["Sw", "Sh"], "Gift in Battle Tower (post-game)"),
    d(773, "Silvally", ["Sw", "Sh"], "Evolve Type: Null (high friendship)"),

    // ── Returning Pokemon: Kanto ───────────────────────
    d(1, "Bulbasaur", ["Sw", "Sh"], "Isle of Armor DLC / Max Raid"),
    d(2, "Ivysaur", ["Sw", "Sh"], "Evolve Bulbasaur"),
    d(3, "Venusaur", ["Sw", "Sh"], "Evolve Ivysaur"),
    d(4, "Charmander", ["Sw", "Sh"], "Gift from Leon (post-game)"),
    d(5, "Charmeleon", ["Sw", "Sh"], "Evolve Charmander"),
    d(6, "Charizard", ["Sw", "Sh"], "Evolve Charmeleon"),
    d(7, "Squirtle", ["Sw", "Sh"], "Isle of Armor DLC / Max Raid"),
    d(8, "Wartortle", ["Sw", "Sh"], "Evolve Squirtle"),
    d(9, "Blastoise", ["Sw", "Sh"], "Evolve Wartortle"),
    d(10, "Caterpie", ["Sw", "Sh"], "Route 1, Wild Area"),
    d(11, "Metapod", ["Sw", "Sh"], "Wild Area, evolve Caterpie"),
    d(12, "Butterfree", ["Sw", "Sh"], "Wild Area, evolve Metapod"),
    d(25, "Pikachu", ["Sw", "Sh"], "Route 4, Wild Area"),
    d(26, "Raichu", ["Sw", "Sh"], "Evolve Pikachu (Thunder Stone)"),
    d(35, "Clefairy", ["Sw", "Sh"], "Motostoke Riverbank, Wild Area"),
    d(36, "Clefable", ["Sw", "Sh"], "Evolve Clefairy (Moon Stone)"),
    d(37, "Vulpix", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(38, "Ninetales", ["Sw", "Sh"], "Evolve Vulpix (Fire Stone)"),
    d(43, "Oddish", ["Sw", "Sh"], "Wild Area (Dappled Grove)"),
    d(44, "Gloom", ["Sw", "Sh"], "Wild Area, evolve Oddish"),
    d(45, "Vileplume", ["Sw", "Sh"], "Evolve Gloom (Leaf Stone)"),
    d(50, "Diglett", ["Sw", "Sh"], "Wild Area (Galar Mine, Rolling Fields)"),
    d(51, "Dugtrio", ["Sw", "Sh"], "Wild Area, evolve Diglett"),
    d(52, "Meowth", ["Sw", "Sh"], "Route 4, Wild Area (Galarian form)"),
    d(53, "Persian", ["Sw", "Sh"], "Evolve Kantonian Meowth (friendship)"),
    d(58, "Growlithe", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(59, "Arcanine", ["Sw", "Sh"], "Evolve Growlithe (Fire Stone)"),
    d(66, "Machop", ["Sw", "Sh"], "Wild Area (Rolling Fields, Dappled Grove)"),
    d(67, "Machoke", ["Sw", "Sh"], "Wild Area, evolve Machop"),
    d(68, "Machamp", ["Sw", "Sh"], "Trade evolve Machoke"),
    d(72, "Tentacool", ["Sw", "Sh"], "Route 9 (Surfing)"),
    d(73, "Tentacruel", ["Sw", "Sh"], "Route 9 (Surfing), evolve Tentacool"),
    d(77, "Ponyta", ["Sh"], "Glimwood Tangle (Galarian form - Shield)"),
    d(78, "Rapidash", ["Sh"], "Evolve Galarian Ponyta (Shield)"),
    d(79, "Slowpoke", ["Sw", "Sh"], "Wedgehurst Station (Galarian form)"),
    d(80, "Slowbro", ["Sw", "Sh"], "Evolve Galarian Slowpoke (Isle of Armor)"),
    d(90, "Shellder", ["Sw", "Sh"], "Route 2 (Fishing), Wild Area"),
    d(91, "Cloyster", ["Sw", "Sh"], "Evolve Shellder (Water Stone)"),
    d(92, "Gastly", ["Sw", "Sh"], "Watchtower Ruins, Wild Area"),
    d(93, "Haunter", ["Sw", "Sh"], "Wild Area, evolve Gastly"),
    d(94, "Gengar", ["Sw", "Sh"], "Trade evolve Haunter"),
    d(95, "Onix", ["Sw", "Sh"], "Wild Area (Rolling Fields)"),
    d(98, "Krabby", ["Sw", "Sh"], "Route 9, Wild Area (Fishing)"),
    d(99, "Kingler", ["Sw", "Sh"], "Wild Area, evolve Krabby"),
    d(102, "Exeggcute", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(103, "Exeggutor", ["Sw", "Sh"], "Evolve Exeggcute"),
    d(104, "Cubone", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(105, "Marowak", ["Sw", "Sh"], "Evolve Cubone"),
    d(106, "Hitmonlee", ["Sw", "Sh"], "Evolve Tyrogue (Atk > Def)"),
    d(107, "Hitmonchan", ["Sw", "Sh"], "Evolve Tyrogue (Def > Atk)"),
    d(108, "Lickitung", ["Sw", "Sh"], "Wild Area (Lake of Outrage)"),
    d(109, "Koffing", ["Sw", "Sh"], "Wild Area (Dusty Bowl, Motostoke Riverbank)"),
    d(110, "Weezing", ["Sw", "Sh"], "Wild Area, evolve Koffing (Galarian form in Galar)"),
    d(111, "Rhyhorn", ["Sw", "Sh"], "Wild Area (Rolling Fields, Giant's Cap)"),
    d(112, "Rhydon", ["Sw", "Sh"], "Wild Area, evolve Rhyhorn"),
    d(113, "Chansey", ["Sw", "Sh"], "Wild Area (Lake of Outrage)"),
    d(114, "Tangela", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(118, "Goldeen", ["Sw", "Sh"], "Route 2 (Fishing), Wild Area"),
    d(119, "Seaking", ["Sw", "Sh"], "Wild Area (Fishing), evolve Goldeen"),
    d(120, "Staryu", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(121, "Starmie", ["Sw", "Sh"], "Evolve Staryu"),
    d(123, "Scyther", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(124, "Jynx", ["Sw", "Sh"], "Wild Area (overworld, snowstorm)"),
    d(125, "Electabuzz", ["Sw", "Sh"], "Wild Area (North Lake Miloch, thunderstorm)"),
    d(126, "Magmar", ["Sw", "Sh"], "Wild Area (Motostoke Riverbank, sunny)"),
    d(129, "Magikarp", ["Sw", "Sh"], "Route 2, Wild Area (Fishing)"),
    d(130, "Gyarados", ["Sw", "Sh"], "Wild Area, evolve Magikarp"),
    d(131, "Lapras", ["Sw", "Sh"], "Route 2, Route 9, Wild Area"),
    d(132, "Ditto", ["Sw", "Sh"], "Lake of Outrage, Wild Area"),
    d(133, "Eevee", ["Sw", "Sh"], "Route 4, Wild Area"),
    d(134, "Vaporeon", ["Sw", "Sh"], "Evolve Eevee (Water Stone)"),
    d(135, "Jolteon", ["Sw", "Sh"], "Evolve Eevee (Thunder Stone)"),
    d(136, "Flareon", ["Sw", "Sh"], "Evolve Eevee (Fire Stone)"),
    d(143, "Snorlax", ["Sw", "Sh"], "Motostoke Riverbank, Wild Area"),
    d(150, "Mewtwo", ["Sw", "Sh"], "Max Raid event only"),

    // ── Returning Pokemon: Johto ───────────────────────
    d(163, "Hoothoot", ["Sw", "Sh"], "Wild Area (overworld, night)"),
    d(164, "Noctowl", ["Sw", "Sh"], "Wild Area, evolve Hoothoot"),
    d(170, "Chinchou", ["Sw", "Sh"], "Route 9 (Fishing)"),
    d(171, "Lanturn", ["Sw", "Sh"], "Route 9 (Surfing), evolve Chinchou"),
    d(172, "Pichu", ["Sw", "Sh"], "Route 4, Wild Area"),
    d(173, "Cleffa", ["Sw", "Sh"], "Wild Area (Motostoke Riverbank)"),
    d(175, "Togepi", ["Sw", "Sh"], "Wild Area (Bridge Field, fog)"),
    d(176, "Togetic", ["Sw", "Sh"], "Wild Area (Stony Wilderness), evolve Togepi"),
    d(177, "Natu", ["Sw", "Sh"], "Wild Area (Watchtower Ruins)"),
    d(178, "Xatu", ["Sw", "Sh"], "Wild Area, evolve Natu"),
    d(182, "Bellossom", ["Sw", "Sh"], "Evolve Gloom (Sun Stone)"),
    d(185, "Sudowoodo", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(194, "Wooper", ["Sw", "Sh"], "Wild Area (overworld, rain)"),
    d(195, "Quagsire", ["Sw", "Sh"], "Wild Area, evolve Wooper"),
    d(196, "Espeon", ["Sw", "Sh"], "Evolve Eevee (high friendship, day)"),
    d(197, "Umbreon", ["Sw", "Sh"], "Evolve Eevee (high friendship, night)"),
    d(202, "Wobbuffet", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(206, "Dunsparce", ["Sw", "Sh"], "Wild Area (overworld, sandstorm)"),
    d(208, "Steelix", ["Sw", "Sh"], "Wild Area, evolve Onix (trade with Metal Coat)"),
    d(211, "Qwilfish", ["Sw", "Sh"], "Route 9, Wild Area (Fishing)"),
    d(213, "Shuckle", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(215, "Sneasel", ["Sw", "Sh"], "Route 8, Wild Area"),
    d(220, "Swinub", ["Sw", "Sh"], "Wild Area (Hammerlocke Hills)"),
    d(221, "Piloswine", ["Sw", "Sh"], "Wild Area, evolve Swinub"),
    d(224, "Octillery", ["Sw", "Sh"], "Route 9, evolve Remoraid"),
    d(225, "Delibird", ["Sw", "Sh"], "Route 10, Wild Area"),
    d(226, "Mantine", ["Sw", "Sh"], "Route 9, Wild Area"),
    d(227, "Skarmory", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(236, "Tyrogue", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(237, "Hitmontop", ["Sw", "Sh"], "Evolve Tyrogue (Atk = Def)"),
    d(238, "Smoochum", ["Sw", "Sh"], "Wild Area (overworld, snowstorm)"),
    d(239, "Elekid", ["Sw", "Sh"], "Wild Area (thunderstorm)"),
    d(240, "Magby", ["Sw", "Sh"], "Wild Area (sunny)"),
    d(241, "Miltank", ["Sw", "Sh"], "Wild Area (East Lake Axewell)"),
    d(242, "Blissey", ["Sw", "Sh"], "Evolve Chansey (high friendship)"),
    d(246, "Larvitar", ["Sh"], "Wild Area (Lake of Outrage - Shield)"),
    d(247, "Pupitar", ["Sh"], "Wild Area, evolve Larvitar (Shield)"),
    d(248, "Tyranitar", ["Sh"], "Wild Area, evolve Pupitar (Shield)"),

    // ── Returning Pokemon: Hoenn ───────────────────────
    d(252, "Treecko", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(255, "Torchic", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(258, "Mudkip", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(270, "Lotad", ["Sh"], "Wild Area (Dappled Grove - Shield)"),
    d(271, "Lombre", ["Sh"], "Wild Area, evolve Lotad (Shield)"),
    d(272, "Ludicolo", ["Sh"], "Evolve Lombre (Water Stone - Shield)"),
    d(273, "Seedot", ["Sw"], "Wild Area (Rolling Fields - Sword)"),
    d(274, "Nuzleaf", ["Sw"], "Wild Area, evolve Seedot (Sword)"),
    d(275, "Shiftry", ["Sw"], "Evolve Nuzleaf (Leaf Stone - Sword)"),
    d(278, "Wingull", ["Sw", "Sh"], "Route 9, Wild Area"),
    d(279, "Pelipper", ["Sw", "Sh"], "Route 9, Wild Area, evolve Wingull"),
    d(280, "Ralts", ["Sw", "Sh"], "Route 4, Wild Area (fog)"),
    d(281, "Kirlia", ["Sw", "Sh"], "Wild Area, evolve Ralts"),
    d(282, "Gardevoir", ["Sw", "Sh"], "Evolve Kirlia (female or male)"),
    d(290, "Nincada", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(291, "Ninjask", ["Sw", "Sh"], "Evolve Nincada"),
    d(292, "Shedinja", ["Sw", "Sh"], "Evolve Nincada (empty party slot + spare Poke Ball)"),
    d(302, "Sableye", ["Sh"], "Wild Area (Dusty Bowl - Shield)"),
    d(303, "Mawile", ["Sw"], "Wild Area (Dusty Bowl - Sword)"),
    d(309, "Electrike", ["Sw", "Sh"], "Route 4, Wild Area"),
    d(310, "Manectric", ["Sw", "Sh"], "Wild Area, evolve Electrike"),
    d(315, "Roselia", ["Sw", "Sh"], "Wild Area (Dappled Grove)"),
    d(318, "Carvanha", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(319, "Sharpedo", ["Sw", "Sh"], "Evolve Carvanha"),
    d(320, "Wailmer", ["Sw", "Sh"], "Route 9 (Surfing)"),
    d(321, "Wailord", ["Sw", "Sh"], "Route 9 (Surfing), evolve Wailmer"),
    d(324, "Torkoal", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(328, "Trapinch", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(329, "Vibrava", ["Sw", "Sh"], "Wild Area, evolve Trapinch"),
    d(330, "Flygon", ["Sw", "Sh"], "Wild Area, evolve Vibrava"),
    d(337, "Lunatone", ["Sh"], "Route 8, Wild Area (Shield)"),
    d(338, "Solrock", ["Sw"], "Route 8, Wild Area (Sword)"),
    d(339, "Barboach", ["Sw", "Sh"], "Wild Area (Fishing)"),
    d(340, "Whiscash", ["Sw", "Sh"], "Wild Area (Fishing), evolve Barboach"),
    d(341, "Corphish", ["Sw", "Sh"], "Wild Area (Fishing)"),
    d(342, "Crawdaunt", ["Sw", "Sh"], "Wild Area, evolve Corphish"),
    d(343, "Baltoy", ["Sw", "Sh"], "Wild Area (Dusty Bowl)"),
    d(344, "Claydol", ["Sw", "Sh"], "Wild Area, evolve Baltoy"),
    d(349, "Feebas", ["Sw", "Sh"], "Route 2 (Fishing, 1% encounter)"),
    d(350, "Milotic", ["Sw", "Sh"], "Wild Area, evolve Feebas (trade with Prism Scale)"),
    d(355, "Duskull", ["Sw", "Sh"], "Watchtower Ruins, Wild Area"),
    d(356, "Dusclops", ["Sw", "Sh"], "Wild Area, evolve Duskull"),
    d(360, "Wynaut", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(361, "Snorunt", ["Sw", "Sh"], "Route 8, Wild Area"),
    d(362, "Glalie", ["Sw", "Sh"], "Evolve Snorunt"),

    // ── Returning Pokemon: Sinnoh ──────────────────────
    d(403, "Shinx", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(406, "Budew", ["Sw", "Sh"], "Wild Area (Dappled Grove)"),
    d(407, "Roserade", ["Sw", "Sh"], "Evolve Roselia (Shiny Stone)"),
    d(415, "Combee", ["Sw", "Sh"], "Wild Area (Rolling Fields)"),
    d(416, "Vespiquen", ["Sw", "Sh"], "Wild Area, evolve Combee (female only)"),
    d(420, "Cherubi", ["Sw", "Sh"], "Wild Area (shaking Berry trees)"),
    d(421, "Cherrim", ["Sw", "Sh"], "Evolve Cherubi"),
    d(422, "Shellos", ["Sw", "Sh"], "Wild Area (East/West Sea forms by area)"),
    d(423, "Gastrodon", ["Sw", "Sh"], "Wild Area, evolve Shellos"),
    d(425, "Drifloon", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(426, "Drifblim", ["Sw", "Sh"], "Wild Area, evolve Drifloon"),
    d(434, "Stunky", ["Sw", "Sh"], "Wild Area (Dusty Bowl)"),
    d(435, "Skuntank", ["Sw", "Sh"], "Wild Area, evolve Stunky"),
    d(436, "Bronzor", ["Sw", "Sh"], "Wild Area (Giant's Cap)"),
    d(437, "Bronzong", ["Sw", "Sh"], "Wild Area, evolve Bronzor"),
    d(438, "Bonsly", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(446, "Munchlax", ["Sw", "Sh"], "Wild Area (Motostoke Riverbank, overworld)"),
    d(447, "Riolu", ["Sw", "Sh"], "Wild Area (Giant's Cap, snowstorm)"),
    d(448, "Lucario", ["Sw", "Sh"], "Wild Area, evolve Riolu (high friendship, day)"),
    d(449, "Hippopotas", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(450, "Hippowdon", ["Sw", "Sh"], "Wild Area, evolve Hippopotas"),
    d(451, "Skorupi", ["Sw", "Sh"], "Wild Area (Dusty Bowl)"),
    d(452, "Drapion", ["Sw", "Sh"], "Wild Area, evolve Skorupi"),
    d(453, "Croagunk", ["Sh"], "Wild Area (overworld - Shield)"),
    d(454, "Toxicroak", ["Sh"], "Wild Area, evolve Croagunk (Shield)"),
    d(458, "Mantyke", ["Sw", "Sh"], "Route 9 (Surfing)"),
    d(459, "Snover", ["Sw", "Sh"], "Route 10, Wild Area"),
    d(460, "Abomasnow", ["Sw", "Sh"], "Wild Area, evolve Snover"),
    d(461, "Weavile", ["Sw", "Sh"], "Wild Area, evolve Sneasel (night + Razor Claw)"),
    d(462, "Magnezone", ["Sw", "Sh"], "Evolve Magneton (Thunder Stone in Galar)"),
    d(463, "Lickilicky", ["Sw", "Sh"], "Evolve Lickitung (learn Rollout)"),
    d(464, "Rhyperior", ["Sw", "Sh"], "Evolve Rhydon (trade with Protector)"),
    d(466, "Electivire", ["Sw", "Sh"], "Evolve Electabuzz (trade with Electirizer)"),
    d(467, "Magmortar", ["Sw", "Sh"], "Evolve Magmar (trade with Magmarizer)"),
    d(468, "Togekiss", ["Sw", "Sh"], "Evolve Togetic (Shiny Stone)"),
    d(470, "Leafeon", ["Sw", "Sh"], "Evolve Eevee (Leaf Stone)"),
    d(471, "Glaceon", ["Sw", "Sh"], "Evolve Eevee (Ice Stone)"),
    d(473, "Mamoswine", ["Sw", "Sh"], "Evolve Piloswine (learn Ancient Power)"),
    d(475, "Gallade", ["Sw", "Sh"], "Evolve Kirlia (male, Dawn Stone)"),
    d(477, "Dusknoir", ["Sw", "Sh"], "Evolve Dusclops (trade with Reaper Cloth)"),
    d(478, "Froslass", ["Sw", "Sh"], "Evolve Snorunt (female, Dawn Stone)"),
    d(479, "Rotom", ["Sw", "Sh"], "Wild Area (Lake of Outrage, thunderstorm)"),

    // ── Returning Pokemon: Unova ───────────────────────
    d(509, "Purrloin", ["Sw", "Sh"], "Route 2, Wild Area"),
    d(510, "Liepard", ["Sw", "Sh"], "Wild Area, evolve Purrloin"),
    d(517, "Munna", ["Sw", "Sh"], "Wild Area (Motostoke Riverbank)"),
    d(518, "Musharna", ["Sw", "Sh"], "Wild Area, evolve Munna (Moon Stone)"),
    d(519, "Pidove", ["Sw", "Sh"], "Route 1, Wild Area"),
    d(520, "Tranquill", ["Sw", "Sh"], "Wild Area, evolve Pidove"),
    d(521, "Unfezant", ["Sw", "Sh"], "Wild Area, evolve Tranquill"),
    d(524, "Roggenrola", ["Sw", "Sh"], "Galar Mine, Wild Area"),
    d(525, "Boldore", ["Sw", "Sh"], "Wild Area, evolve Roggenrola"),
    d(526, "Gigalith", ["Sw", "Sh"], "Trade evolve Boldore"),
    d(527, "Woobat", ["Sw", "Sh"], "Galar Mine, Wild Area"),
    d(528, "Swoobat", ["Sw", "Sh"], "Wild Area, evolve Woobat (high friendship)"),
    d(529, "Drilbur", ["Sw", "Sh"], "Galar Mine, Wild Area"),
    d(530, "Excadrill", ["Sw", "Sh"], "Wild Area, evolve Drilbur"),
    d(532, "Timburr", ["Sw", "Sh"], "Galar Mine, Wild Area"),
    d(533, "Gurdurr", ["Sw", "Sh"], "Wild Area, evolve Timburr"),
    d(534, "Conkeldurr", ["Sw", "Sh"], "Trade evolve Gurdurr"),
    d(535, "Tympole", ["Sw", "Sh"], "Wild Area (overworld, rain)"),
    d(536, "Palpitoad", ["Sw", "Sh"], "Wild Area, evolve Tympole"),
    d(537, "Seismitoad", ["Sw", "Sh"], "Wild Area, evolve Palpitoad"),
    d(538, "Throh", ["Sh"], "Wild Area (overworld - Shield)"),
    d(539, "Sawk", ["Sw"], "Wild Area (overworld - Sword)"),
    d(546, "Cottonee", ["Sw", "Sh"], "Wild Area (Stony Wilderness)"),
    d(547, "Whimsicott", ["Sw", "Sh"], "Evolve Cottonee (Sun Stone)"),
    d(550, "Basculin", ["Sw", "Sh"], "Wild Area (Fishing, red/blue stripe by game)"),
    d(554, "Darumaka", ["Sw", "Sh"], "Route 8, Route 10 (Galarian form)"),
    d(555, "Darmanitan", ["Sw", "Sh"], "Evolve Galarian Darumaka (Ice Stone)"),
    d(556, "Maractus", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(557, "Dwebble", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(558, "Crustle", ["Sw", "Sh"], "Wild Area, evolve Dwebble"),
    d(559, "Scraggy", ["Sw"], "Route 6, Wild Area (Sword)"),
    d(560, "Scrafty", ["Sw"], "Wild Area, evolve Scraggy (Sword)"),
    d(561, "Sigilyph", ["Sw", "Sh"], "Wild Area (Dusty Bowl)"),
    d(568, "Trubbish", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(569, "Garbodor", ["Sw", "Sh"], "Wild Area, evolve Trubbish"),
    d(572, "Minccino", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(573, "Cinccino", ["Sw", "Sh"], "Evolve Minccino (Shiny Stone)"),
    d(574, "Gothita", ["Sw"], "Wild Area (overworld - Sword)"),
    d(575, "Gothorita", ["Sw"], "Wild Area, evolve Gothita (Sword)"),
    d(576, "Gothitelle", ["Sw"], "Wild Area, evolve Gothorita (Sword)"),
    d(577, "Solosis", ["Sh"], "Wild Area (overworld - Shield)"),
    d(578, "Duosion", ["Sh"], "Wild Area, evolve Solosis (Shield)"),
    d(579, "Reuniclus", ["Sh"], "Wild Area, evolve Duosion (Shield)"),
    d(582, "Vanillite", ["Sw", "Sh"], "Route 8, Wild Area"),
    d(583, "Vanillish", ["Sw", "Sh"], "Wild Area, evolve Vanillite"),
    d(584, "Vanilluxe", ["Sw", "Sh"], "Wild Area, evolve Vanillish"),
    d(588, "Karrablast", ["Sw", "Sh"], "Route 7, Wild Area"),
    d(589, "Escavalier", ["Sw", "Sh"], "Trade evolve Karrablast (for Shelmet)"),
    d(592, "Frillish", ["Sw", "Sh"], "Route 9 (Surfing)"),
    d(593, "Jellicent", ["Sw", "Sh"], "Route 9, evolve Frillish"),
    d(595, "Joltik", ["Sw", "Sh"], "Wild Area (Stony Wilderness)"),
    d(596, "Galvantula", ["Sw", "Sh"], "Wild Area, evolve Joltik"),
    d(597, "Ferroseed", ["Sw", "Sh"], "Wild Area (Stony Wilderness)"),
    d(598, "Ferrothorn", ["Sw", "Sh"], "Wild Area, evolve Ferroseed"),
    d(599, "Klink", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(600, "Klang", ["Sw", "Sh"], "Wild Area, evolve Klink"),
    d(601, "Klinklang", ["Sw", "Sh"], "Wild Area, evolve Klang"),
    d(607, "Litwick", ["Sw", "Sh"], "Wild Area (overworld, fog)"),
    d(608, "Lampent", ["Sw", "Sh"], "Wild Area, evolve Litwick"),
    d(609, "Chandelure", ["Sw", "Sh"], "Evolve Lampent (Dusk Stone)"),
    d(610, "Axew", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(611, "Fraxure", ["Sw", "Sh"], "Wild Area, evolve Axew"),
    d(612, "Haxorus", ["Sw", "Sh"], "Wild Area, evolve Fraxure"),
    d(613, "Cubchoo", ["Sw", "Sh"], "Route 10, Wild Area"),
    d(614, "Beartic", ["Sw", "Sh"], "Wild Area, evolve Cubchoo"),
    d(616, "Shelmet", ["Sw", "Sh"], "Route 7, Wild Area"),
    d(617, "Accelgor", ["Sw", "Sh"], "Trade evolve Shelmet (for Karrablast)"),
    d(618, "Stunfisk", ["Sw", "Sh"], "Galar Mine No. 2, Wild Area (Galarian form)"),
    d(622, "Golett", ["Sw", "Sh"], "Wild Area (Watchtower Ruins)"),
    d(623, "Golurk", ["Sw", "Sh"], "Wild Area, evolve Golett"),
    d(624, "Pawniard", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(625, "Bisharp", ["Sw", "Sh"], "Wild Area, evolve Pawniard"),
    d(627, "Rufflet", ["Sw"], "Route 8, Wild Area (Sword)"),
    d(628, "Braviary", ["Sw"], "Wild Area, evolve Rufflet (Sword)"),
    d(629, "Vullaby", ["Sh"], "Route 8, Wild Area (Shield)"),
    d(630, "Mandibuzz", ["Sh"], "Wild Area, evolve Vullaby (Shield)"),
    d(631, "Heatmor", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(632, "Durant", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(633, "Deino", ["Sw"], "Wild Area (Lake of Outrage - Sword)"),
    d(634, "Zweilous", ["Sw"], "Wild Area, evolve Deino (Sword)"),
    d(635, "Hydreigon", ["Sw"], "Wild Area, evolve Zweilous (Sword)"),

    // ── Returning Pokemon: Kalos ───────────────────────
    d(659, "Bunnelby", ["Sw", "Sh"], "Route 1, Wild Area"),
    d(660, "Diggersby", ["Sw", "Sh"], "Wild Area, evolve Bunnelby"),
    d(674, "Pancham", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(675, "Pangoro", ["Sw", "Sh"], "Wild Area, evolve Pancham (Dark-type in party)"),
    d(679, "Honedge", ["Sw", "Sh"], "Wild Area (Hammerlocke Hills)"),
    d(680, "Doublade", ["Sw", "Sh"], "Wild Area, evolve Honedge"),
    d(681, "Aegislash", ["Sw", "Sh"], "Evolve Doublade (Dusk Stone)"),
    d(682, "Spritzee", ["Sh"], "Route 5, Glimwood Tangle (Shield)"),
    d(683, "Aromatisse", ["Sh"], "Evolve Spritzee (trade with Sachet - Shield)"),
    d(684, "Swirlix", ["Sw"], "Route 5, Wild Area (Sword)"),
    d(685, "Slurpuff", ["Sw"], "Evolve Swirlix (trade with Whipped Dream - Sword)"),
    d(686, "Inkay", ["Sw", "Sh"], "Route 7, Wild Area"),
    d(687, "Malamar", ["Sw", "Sh"], "Wild Area, evolve Inkay (hold console upside down at Lv30+)"),
    d(688, "Binacle", ["Sw", "Sh"], "Route 7, Wild Area"),
    d(689, "Barbaracle", ["Sw", "Sh"], "Wild Area, evolve Binacle"),
    d(694, "Helioptile", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(695, "Heliolisk", ["Sw", "Sh"], "Evolve Helioptile (Sun Stone)"),
    d(700, "Sylveon", ["Sw", "Sh"], "Evolve Eevee (high friendship + Fairy move)"),
    d(701, "Hawlucha", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(704, "Goomy", ["Sh"], "Wild Area (Lake of Outrage - Shield)"),
    d(705, "Sliggoo", ["Sh"], "Wild Area, evolve Goomy (Shield)"),
    d(706, "Goodra", ["Sh"], "Wild Area, evolve Sliggoo (Lv50+ in rain - Shield)"),
    d(708, "Phantump", ["Sw", "Sh"], "Glimwood Tangle, Wild Area"),
    d(709, "Trevenant", ["Sw", "Sh"], "Wild Area, trade evolve Phantump"),
    d(710, "Pumpkaboo", ["Sw", "Sh"], "Route 4, Wild Area"),
    d(711, "Gourgeist", ["Sw", "Sh"], "Trade evolve Pumpkaboo"),
    d(712, "Bergmite", ["Sw", "Sh"], "Route 10, Wild Area"),
    d(713, "Avalugg", ["Sw", "Sh"], "Wild Area, evolve Bergmite"),
    d(714, "Noibat", ["Sw", "Sh"], "Galar Mine No. 2, Wild Area"),
    d(715, "Noivern", ["Sw", "Sh"], "Wild Area, evolve Noibat"),

    // ── Returning Pokemon: Alola ───────────────────────
    d(742, "Cutiefly", ["Sw", "Sh"], "Wild Area (Rolling Fields)"),
    d(743, "Ribombee", ["Sw", "Sh"], "Wild Area, evolve Cutiefly"),
    d(746, "Wishiwashi", ["Sw", "Sh"], "Route 9 (Fishing)"),
    d(747, "Mareanie", ["Sw", "Sh"], "Route 9, Wild Area"),
    d(748, "Toxapex", ["Sw", "Sh"], "Route 9, evolve Mareanie"),
    d(749, "Mudbray", ["Sw", "Sh"], "Route 3, Wild Area"),
    d(750, "Mudsdale", ["Sw", "Sh"], "Wild Area, evolve Mudbray"),
    d(751, "Dewpider", ["Sw", "Sh"], "Wild Area (overworld, rain)"),
    d(752, "Araquanid", ["Sw", "Sh"], "Wild Area, evolve Dewpider"),
    d(755, "Morelull", ["Sw", "Sh"], "Glimwood Tangle, Wild Area"),
    d(756, "Shiinotic", ["Sw", "Sh"], "Glimwood Tangle, evolve Morelull"),
    d(757, "Salandit", ["Sw", "Sh"], "Route 6, Wild Area"),
    d(758, "Salazzle", ["Sw", "Sh"], "Wild Area, evolve Salandit (female only)"),
    d(759, "Stufful", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(760, "Bewear", ["Sw", "Sh"], "Wild Area, evolve Stufful"),
    d(761, "Bounsweet", ["Sw", "Sh"], "Wild Area (Stony Wilderness)"),
    d(762, "Steenee", ["Sw", "Sh"], "Wild Area, evolve Bounsweet"),
    d(763, "Tsareena", ["Sw", "Sh"], "Evolve Steenee (learn Stomp)"),
    d(765, "Oranguru", ["Sh"], "Glimwood Tangle, Wild Area (Shield)"),
    d(766, "Passimian", ["Sw"], "Wild Area (overworld - Sword)"),
    d(767, "Wimpod", ["Sw", "Sh"], "Route 7, Wild Area"),
    d(768, "Golisopod", ["Sw", "Sh"], "Wild Area, evolve Wimpod"),
    d(769, "Sandygast", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(770, "Palossand", ["Sw", "Sh"], "Evolve Sandygast"),
    d(776, "Turtonator", ["Sw"], "Wild Area (Lake of Outrage - Sword)"),
    d(777, "Togedemaru", ["Sw", "Sh"], "Route 8, Wild Area"),
    d(778, "Mimikyu", ["Sw", "Sh"], "Wild Area (Giant's Mirror, fog)"),
    d(780, "Drampa", ["Sh"], "Wild Area (Lake of Outrage - Shield)"),
    d(781, "Dhelmise", ["Sw", "Sh"], "Route 9 (Fishing, rare)"),
    d(782, "Jangmo-o", ["Sw"], "Wild Area (Lake of Outrage - Sword)"),
    d(783, "Hakamo-o", ["Sw"], "Wild Area, evolve Jangmo-o (Sword)"),
    d(784, "Kommo-o", ["Sw"], "Wild Area, evolve Hakamo-o (Sword)"),

    // ── Galarian Meowth / Perrserker ───────────────────
    d(863, "Perrserker", ["Sw", "Sh"], "Route 7, evolve Galarian Meowth"),

    // ── Additional Wild Area Pokemon ───────────────────
    d(81, "Magnemite", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(82, "Magneton", ["Sw", "Sh"], "Wild Area, evolve Magnemite"),
    d(137, "Porygon", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(138, "Omanyte", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(140, "Kabuto", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(142, "Aerodactyl", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(183, "Marill", ["Sw", "Sh"], "Wild Area (overworld, rain)"),
    d(184, "Azumarill", ["Sw", "Sh"], "Wild Area, evolve Marill"),
    d(186, "Politoed", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(199, "Slowking", ["Sw", "Sh"], "Crown Tundra DLC (Galarian form)"),
    d(212, "Scizor", ["Sw", "Sh"], "Evolve Scyther (trade with Metal Coat)"),
    d(214, "Heracross", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(222, "Corsola", ["Sh"], "Route 8, Wild Area (Galarian form - Shield)"),
    d(223, "Remoraid", ["Sw", "Sh"], "Route 9 (Fishing)"),
    d(233, "Porygon2", ["Sw", "Sh"], "Evolve Porygon (trade with Upgrade)"),
    d(298, "Azurill", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(304, "Aron", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(305, "Lairon", ["Sw", "Sh"], "Evolve Aron"),
    d(306, "Aggron", ["Sw", "Sh"], "Evolve Lairon"),
    d(314, "Illumise", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(313, "Volbeat", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(334, "Altaria", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(345, "Lileep", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(347, "Anorith", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(359, "Absol", ["Sw", "Sh"], "Crown Tundra DLC"),
    d(363, "Spheal", ["Sw", "Sh"], "Crown Tundra DLC"),
    d(364, "Sealeo", ["Sw", "Sh"], "Evolve Spheal"),
    d(365, "Walrein", ["Sw", "Sh"], "Evolve Sealeo"),
    d(369, "Relicanth", ["Sw", "Sh"], "Crown Tundra DLC"),
    d(374, "Beldum", ["Sw", "Sh"], "Crown Tundra DLC"),
    d(375, "Metang", ["Sw", "Sh"], "Evolve Beldum"),
    d(376, "Metagross", ["Sw", "Sh"], "Evolve Metang"),
    d(427, "Buneary", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(428, "Lopunny", ["Sw", "Sh"], "Evolve Buneary"),
    d(440, "Happiny", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(443, "Gible", ["Sw", "Sh"], "Crown Tundra DLC"),
    d(444, "Gabite", ["Sw", "Sh"], "Evolve Gible"),
    d(445, "Garchomp", ["Sw", "Sh"], "Evolve Gabite"),
    d(474, "Porygon-Z", ["Sw", "Sh"], "Evolve Porygon2 (trade with Dubious Disc)"),
    d(633, "Deino", ["Sw"], "Wild Area (Lake of Outrage - Sword)"),
    d(636, "Larvesta", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(637, "Volcarona", ["Sw", "Sh"], "Evolve Larvesta"),
    d(661, "Fletchling", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(662, "Fletchinder", ["Sw", "Sh"], "Evolve Fletchling"),
    d(663, "Talonflame", ["Sw", "Sh"], "Evolve Fletchinder"),
    d(677, "Espurr", ["Sw", "Sh"], "Wild Area (overworld)"),
    d(678, "Meowstic", ["Sw", "Sh"], "Wild Area, evolve Espurr"),
    d(690, "Skrelp", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(691, "Dragalge", ["Sw", "Sh"], "Evolve Skrelp"),
    d(692, "Clauncher", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(693, "Clawitzer", ["Sw", "Sh"], "Evolve Clauncher"),
    d(702, "Dedenne", ["Sw", "Sh"], "Crown Tundra DLC"),
    d(744, "Rockruff", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(745, "Lycanroc", ["Sw", "Sh"], "Evolve Rockruff"),

    // ── Route 4 Pokemon ────────────────────────────────
    d(840, "Applin", ["Sw", "Sh"], "Route 5, Wild Area"),
    d(302, "Sableye", ["Sh"], "Wild Area (Dusty Bowl - Shield)"),

    // ── Route 10 / Late-game routes ────────────────────
    d(459, "Snover", ["Sw", "Sh"], "Route 10, Wild Area"),
    d(225, "Delibird", ["Sw", "Sh"], "Route 10, Wild Area"),
    d(712, "Bergmite", ["Sw", "Sh"], "Route 10, Wild Area"),

    // ── Additional Misc Pokemon ────────────────────────
    d(194, "Wooper", ["Sw", "Sh"], "Wild Area (overworld, rain)"),
    d(316, "Gulpin", ["Sw", "Sh"], "Isle of Armor DLC"),
    d(317, "Swalot", ["Sw", "Sh"], "Evolve Gulpin"),
    d(458, "Mantyke", ["Sw", "Sh"], "Route 9 (Surfing)"),
    d(479, "Rotom", ["Sw", "Sh"], "Wild Area (Lake of Outrage, thunderstorm)"),
    d(587, "Emolga", ["Sw", "Sh"], "Wild Area (overworld, thunderstorm)"),
    d(845, "Cramorant", ["Sw", "Sh"], "Route 9, Wild Area"),
  ],
};
