import type { GameDex, GameDexEntry } from "../game-dex";

const d = (
  pokemonId: number,
  name: string,
  versions: string[],
  method?: string
): GameDexEntry => ({ pokemonId, name, versions, method });

/* ══════════════════════════════════════════════════
 *  Pokemon X & Y — Kalos Pokedex
 *  Central / Coastal / Mountain sub-dexes combined
 * ══════════════════════════════════════════════════ */
export const X_Y_DEX: GameDex = {
  slug: "x-y",
  versionTags: ["X", "Y"],
  pokemon: [
    // ── Kalos Starters ────────────────────────────
    d(650, "Chespin", ["X", "Y"], "Starter from friends in Aquacorde Town"),
    d(651, "Quilladin", ["X", "Y"], "Evolve Chespin"),
    d(652, "Chesnaught", ["X", "Y"], "Evolve Quilladin"),
    d(653, "Fennekin", ["X", "Y"], "Starter from friends in Aquacorde Town"),
    d(654, "Braixen", ["X", "Y"], "Evolve Fennekin"),
    d(655, "Delphox", ["X", "Y"], "Evolve Braixen"),
    d(656, "Froakie", ["X", "Y"], "Starter from friends in Aquacorde Town"),
    d(657, "Frogadier", ["X", "Y"], "Evolve Froakie"),
    d(658, "Greninja", ["X", "Y"], "Evolve Frogadier"),

    // ── Kanto Starters (gift from Sycamore) ──────
    d(1, "Bulbasaur", ["X", "Y"], "Gift from Prof. Sycamore in Lumiose City"),
    d(2, "Ivysaur", ["X", "Y"], "Evolve Bulbasaur"),
    d(3, "Venusaur", ["X", "Y"], "Evolve Ivysaur"),
    d(4, "Charmander", ["X", "Y"], "Gift from Prof. Sycamore in Lumiose City"),
    d(5, "Charmeleon", ["X", "Y"], "Evolve Charmander"),
    d(6, "Charizard", ["X", "Y"], "Evolve Charmeleon"),
    d(7, "Squirtle", ["X", "Y"], "Gift from Prof. Sycamore in Lumiose City"),
    d(8, "Wartortle", ["X", "Y"], "Evolve Squirtle"),
    d(9, "Blastoise", ["X", "Y"], "Evolve Wartortle"),

    // ── Early routes (Route 2, Santalune Forest, Route 3) ──
    d(10, "Caterpie", ["X", "Y"], "Route 2, Santalune Forest"),
    d(11, "Metapod", ["X", "Y"], "Santalune Forest, evolve Caterpie"),
    d(12, "Butterfree", ["X", "Y"], "Evolve Metapod"),
    d(13, "Weedle", ["X", "Y"], "Route 2, Santalune Forest"),
    d(14, "Kakuna", ["X", "Y"], "Santalune Forest, evolve Weedle"),
    d(15, "Beedrill", ["X", "Y"], "Evolve Kakuna"),
    d(16, "Pidgey", ["X", "Y"], "Routes 2, 3"),
    d(17, "Pidgeotto", ["X", "Y"], "Evolve Pidgey"),
    d(18, "Pidgeot", ["X", "Y"], "Evolve Pidgeotto"),
    d(25, "Pikachu", ["X", "Y"], "Santalune Forest, Route 3"),
    d(26, "Raichu", ["X", "Y"], "Evolve Pikachu (Thunder Stone)"),
    d(172, "Pichu", ["X", "Y"], "Breed Pikachu"),

    // ── New Gen 6 early Pokemon ──────────────────
    d(659, "Bunnelby", ["X", "Y"], "Route 2, Route 3"),
    d(660, "Diggersby", ["X", "Y"], "Evolve Bunnelby"),
    d(661, "Fletchling", ["X", "Y"], "Routes 2, 3, Santalune Forest"),
    d(662, "Fletchinder", ["X", "Y"], "Evolve Fletchling"),
    d(663, "Talonflame", ["X", "Y"], "Evolve Fletchinder"),
    d(664, "Scatterbug", ["X", "Y"], "Santalune Forest, Route 2"),
    d(665, "Spewpa", ["X", "Y"], "Evolve Scatterbug"),
    d(666, "Vivillon", ["X", "Y"], "Evolve Spewpa"),
    d(667, "Litleo", ["X", "Y"], "Route 5, Route 22"),
    d(668, "Pyroar", ["X", "Y"], "Evolve Litleo"),

    // ── Route 3, Route 4 area ────────────────────
    d(263, "Zigzagoon", ["X", "Y"], "Route 2"),
    d(264, "Linoone", ["X", "Y"], "Evolve Zigzagoon"),
    d(399, "Bidoof", ["X", "Y"], "Route 3"),
    d(400, "Bibarel", ["X", "Y"], "Evolve Bidoof"),
    d(412, "Burmy", ["X", "Y"], "Route 3"),
    d(413, "Wormadam", ["X", "Y"], "Evolve female Burmy"),
    d(414, "Mothim", ["X", "Y"], "Evolve male Burmy"),
    d(165, "Ledyba", ["X", "Y"], "Route 4"),
    d(166, "Ledian", ["X", "Y"], "Evolve Ledyba"),
    d(415, "Combee", ["X", "Y"], "Route 4"),
    d(416, "Vespiquen", ["X", "Y"], "Evolve female Combee"),
    d(280, "Ralts", ["X", "Y"], "Route 4"),
    d(281, "Kirlia", ["X", "Y"], "Evolve Ralts"),
    d(282, "Gardevoir", ["X", "Y"], "Evolve Kirlia"),
    d(475, "Gallade", ["X", "Y"], "Evolve male Kirlia (Dawn Stone)"),
    d(300, "Skitty", ["X", "Y"], "Route 4"),
    d(301, "Delcatty", ["X", "Y"], "Evolve Skitty (Moon Stone)"),
    d(406, "Budew", ["X", "Y"], "Route 4"),
    d(315, "Roselia", ["X", "Y"], "Route 7"),
    d(407, "Roserade", ["X", "Y"], "Evolve Roselia (Shiny Stone)"),

    // ── Route 4 flowers ──────────────────────────
    d(669, "Flabebe", ["X", "Y"], "Route 4"),
    d(670, "Floette", ["X", "Y"], "Evolve Flabebe"),
    d(671, "Florges", ["X", "Y"], "Evolve Floette (Shiny Stone)"),

    // ── Route 5, Route 7, Camphrier area ─────────
    d(672, "Skiddo", ["X", "Y"], "Route 5"),
    d(673, "Gogoat", ["X", "Y"], "Evolve Skiddo"),
    d(674, "Pancham", ["X", "Y"], "Route 5"),
    d(675, "Pangoro", ["X", "Y"], "Evolve Pancham (Dark type in party)"),
    d(676, "Furfrou", ["X", "Y"], "Route 5"),
    d(84, "Doduo", ["X", "Y"], "Route 5"),
    d(85, "Dodrio", ["X", "Y"], "Evolve Doduo"),
    d(63, "Abra", ["X", "Y"], "Route 5"),
    d(64, "Kadabra", ["X", "Y"], "Evolve Abra"),
    d(65, "Alakazam", ["X", "Y"], "Trade evolve Kadabra"),
    d(316, "Gulpin", ["X", "Y"], "Route 5"),
    d(317, "Swalot", ["X", "Y"], "Evolve Gulpin"),
    d(235, "Smeargle", ["X", "Y"], "Route 7"),
    d(313, "Volbeat", ["X"], "Route 7"),
    d(314, "Illumise", ["Y"], "Route 7"),
    d(453, "Croagunk", ["X", "Y"], "Route 7"),
    d(454, "Toxicroak", ["X", "Y"], "Evolve Croagunk"),
    d(580, "Ducklett", ["X", "Y"], "Route 7"),
    d(581, "Swanna", ["X", "Y"], "Evolve Ducklett"),
    d(511, "Pansage", ["X", "Y"], "Santalune Forest"),
    d(512, "Simisage", ["X", "Y"], "Evolve Pansage (Leaf Stone)"),
    d(513, "Pansear", ["X", "Y"], "Santalune Forest"),
    d(514, "Simisear", ["X", "Y"], "Evolve Pansear (Fire Stone)"),
    d(515, "Panpour", ["X", "Y"], "Santalune Forest"),
    d(516, "Simipour", ["X", "Y"], "Evolve Panpour (Water Stone)"),

    // ── Connecting Cave, Route 8 ─────────────────
    d(41, "Zubat", ["X", "Y"], "Connecting Cave, caves"),
    d(42, "Golbat", ["X", "Y"], "Caves, evolve Zubat"),
    d(169, "Crobat", ["X", "Y"], "Evolve Golbat (friendship)"),
    d(293, "Whismur", ["X", "Y"], "Connecting Cave"),
    d(294, "Loudred", ["X", "Y"], "Evolve Whismur"),
    d(295, "Exploud", ["X", "Y"], "Evolve Loudred"),
    d(610, "Axew", ["X", "Y"], "Connecting Cave"),
    d(611, "Fraxure", ["X", "Y"], "Evolve Axew"),
    d(612, "Haxorus", ["X", "Y"], "Evolve Fraxure"),
    d(686, "Inkay", ["X", "Y"], "Route 8, Azure Bay"),
    d(687, "Malamar", ["X", "Y"], "Evolve Inkay (hold 3DS upside down)"),
    d(619, "Mienfoo", ["X", "Y"], "Route 8"),
    d(620, "Mienshao", ["X", "Y"], "Evolve Mienfoo"),
    d(359, "Absol", ["X", "Y"], "Route 8"),
    d(325, "Spoink", ["X", "Y"], "Route 8"),
    d(326, "Grumpig", ["X", "Y"], "Evolve Spoink"),

    // ── Fossils (Glittering Cave) ────────────────
    d(696, "Tyrunt", ["X", "Y"], "Revive Jaw Fossil"),
    d(697, "Tyrantrum", ["X", "Y"], "Evolve Tyrunt"),
    d(698, "Amaura", ["X", "Y"], "Revive Sail Fossil"),
    d(699, "Aurorus", ["X", "Y"], "Evolve Amaura"),

    // ── Glittering Cave encounters ───────────────
    d(104, "Cubone", ["X", "Y"], "Glittering Cave"),
    d(105, "Marowak", ["X", "Y"], "Evolve Cubone"),
    d(111, "Rhyhorn", ["X", "Y"], "Glittering Cave"),
    d(112, "Rhydon", ["X", "Y"], "Evolve Rhyhorn"),
    d(464, "Rhyperior", ["X", "Y"], "Trade evolve Rhydon (Protector)"),
    d(66, "Machop", ["X", "Y"], "Glittering Cave"),
    d(67, "Machoke", ["X", "Y"], "Evolve Machop"),
    d(68, "Machamp", ["X", "Y"], "Trade evolve Machoke"),
    d(95, "Onix", ["X", "Y"], "Glittering Cave"),
    d(208, "Steelix", ["X", "Y"], "Evolve Onix (trade with Metal Coat)"),
    d(337, "Lunatone", ["X", "Y"], "Glittering Cave"),
    d(338, "Solrock", ["X", "Y"], "Glittering Cave"),
    d(115, "Kangaskhan", ["X", "Y"], "Glittering Cave (rare)"),

    // ── Route 10 (Menhir Trail) ──────────────────
    d(677, "Espurr", ["X", "Y"], "Route 10"),
    d(678, "Meowstic", ["X", "Y"], "Evolve Espurr"),
    d(133, "Eevee", ["X", "Y"], "Route 10"),
    d(134, "Vaporeon", ["X", "Y"], "Evolve Eevee (Water Stone)"),
    d(135, "Jolteon", ["X", "Y"], "Evolve Eevee (Thunder Stone)"),
    d(136, "Flareon", ["X", "Y"], "Evolve Eevee (Fire Stone)"),
    d(196, "Espeon", ["X", "Y"], "Evolve Eevee (friendship, day)"),
    d(197, "Umbreon", ["X", "Y"], "Evolve Eevee (friendship, night)"),
    d(470, "Leafeon", ["X", "Y"], "Evolve Eevee (Moss Rock)"),
    d(471, "Glaceon", ["X", "Y"], "Evolve Eevee (Ice Rock)"),
    d(700, "Sylveon", ["X", "Y"], "Evolve Eevee (Affection + Fairy move)"),
    d(701, "Hawlucha", ["X", "Y"], "Route 10"),
    d(622, "Golett", ["X", "Y"], "Route 10"),
    d(623, "Golurk", ["X", "Y"], "Evolve Golett"),
    d(561, "Sigilyph", ["X", "Y"], "Route 10"),
    d(209, "Snubbull", ["X", "Y"], "Route 10"),
    d(210, "Granbull", ["X", "Y"], "Evolve Snubbull"),
    d(587, "Emolga", ["X", "Y"], "Route 10"),

    // ── Version exclusives Route 10 ──────────────
    d(228, "Houndour", ["X"], "Route 10"),
    d(229, "Houndoom", ["X"], "Evolve Houndour"),
    d(309, "Electrike", ["Y"], "Route 10"),
    d(310, "Manectric", ["Y"], "Evolve Electrike"),

    // ── Route 11, Reflection Cave ────────────────
    d(30, "Nidorina", ["X", "Y"], "Route 11"),
    d(31, "Nidoqueen", ["X", "Y"], "Evolve Nidorina (Moon Stone)"),
    d(33, "Nidorino", ["X", "Y"], "Route 11"),
    d(34, "Nidoking", ["X", "Y"], "Evolve Nidorino (Moon Stone)"),
    d(29, "Nidoran♀", ["X", "Y"], "Route 11"),
    d(32, "Nidoran♂", ["X", "Y"], "Route 11"),
    d(702, "Dedenne", ["X", "Y"], "Route 11"),
    d(297, "Hariyama", ["X", "Y"], "Route 11"),
    d(296, "Makuhita", ["X", "Y"], "Route 11"),
    d(397, "Staravia", ["X", "Y"], "Route 11"),
    d(396, "Starly", ["X", "Y"], "Route 3"),
    d(398, "Staraptor", ["X", "Y"], "Evolve Staravia"),
    d(433, "Chingling", ["X", "Y"], "Route 11, Reflection Cave"),
    d(358, "Chimecho", ["X", "Y"], "Evolve Chingling (friendship, night)"),
    d(538, "Throh", ["X"], "Route 11"),
    d(539, "Sawk", ["Y"], "Route 11"),
    d(703, "Carbink", ["X", "Y"], "Reflection Cave"),
    d(302, "Sableye", ["Y"], "Reflection Cave"),
    d(122, "Mr. Mime", ["X", "Y"], "Reflection Cave"),
    d(439, "Mime Jr.", ["X", "Y"], "Reflection Cave"),
    d(202, "Wobbuffet", ["X", "Y"], "Reflection Cave"),
    d(360, "Wynaut", ["X", "Y"], "Breed Wobbuffet"),
    d(524, "Roggenrola", ["X", "Y"], "Reflection Cave"),
    d(525, "Boldore", ["X", "Y"], "Evolve Roggenrola"),
    d(526, "Gigalith", ["X", "Y"], "Trade evolve Boldore"),
    d(577, "Solosis", ["X"], "Reflection Cave"),
    d(578, "Duosion", ["X"], "Evolve Solosis"),
    d(579, "Reuniclus", ["X"], "Evolve Duosion"),
    d(574, "Gothita", ["Y"], "Reflection Cave"),
    d(575, "Gothorita", ["Y"], "Evolve Gothita"),
    d(576, "Gothitelle", ["Y"], "Evolve Gothorita"),

    // ── Shalour City gifts ───────────────────────
    d(447, "Riolu", ["X", "Y"], "Breed Lucario"),
    d(448, "Lucario", ["X", "Y"], "Gift from Korrina at Tower of Mastery"),

    // ── Route 12 (Coastal) ───────────────────────
    d(128, "Tauros", ["X", "Y"], "Route 12"),
    d(241, "Miltank", ["X", "Y"], "Route 12"),
    d(179, "Mareep", ["X", "Y"], "Route 12"),
    d(180, "Flaaffy", ["X", "Y"], "Evolve Mareep"),
    d(181, "Ampharos", ["X", "Y"], "Evolve Flaaffy"),
    d(417, "Pachirisu", ["X", "Y"], "Route 12"),
    d(441, "Chatot", ["X", "Y"], "Route 12, Azure Bay"),
    d(694, "Helioptile", ["X", "Y"], "Route 12"),
    d(695, "Heliolisk", ["X", "Y"], "Evolve Helioptile (Sun Stone)"),
    d(79, "Slowpoke", ["X", "Y"], "Route 12"),
    d(80, "Slowbro", ["X", "Y"], "Evolve Slowpoke"),
    d(199, "Slowking", ["X", "Y"], "Trade evolve Slowpoke (King's Rock)"),

    // ── Azure Bay ────────────────────────────────
    d(131, "Lapras", ["X", "Y"], "Azure Bay (Surfing, rare)"),
    d(72, "Tentacool", ["X", "Y"], "Surfing (many routes)"),
    d(73, "Tentacruel", ["X", "Y"], "Surfing, evolve Tentacool"),
    d(458, "Mantyke", ["X", "Y"], "Azure Bay (Surfing)"),
    d(226, "Mantine", ["X", "Y"], "Evolve Mantyke (Remoraid in party)"),
    d(370, "Luvdisc", ["X", "Y"], "Azure Bay, Route 12 (Fishing)"),
    d(223, "Remoraid", ["X", "Y"], "Fishing (various)"),
    d(224, "Octillery", ["X", "Y"], "Evolve Remoraid"),

    // ── Route 13 (Badlands) ──────────────────────
    d(328, "Trapinch", ["X", "Y"], "Route 13"),
    d(329, "Vibrava", ["X", "Y"], "Evolve Trapinch"),
    d(330, "Flygon", ["X", "Y"], "Evolve Vibrava"),
    d(443, "Gible", ["X", "Y"], "Route 13 (rare)"),
    d(444, "Gabite", ["X", "Y"], "Evolve Gible"),
    d(445, "Garchomp", ["X", "Y"], "Evolve Gabite"),
    d(51, "Dugtrio", ["X", "Y"], "Route 13"),
    d(50, "Diglett", ["X", "Y"], "Route 13"),
    d(75, "Graveler", ["X", "Y"], "Route 13, caves"),
    d(74, "Geodude", ["X", "Y"], "Caves, Route 18"),
    d(76, "Golem", ["X", "Y"], "Trade evolve Graveler"),
    d(218, "Slugma", ["X", "Y"], "Route 13"),
    d(219, "Magcargo", ["X", "Y"], "Evolve Slugma"),

    // ── Route 14 (Swamp) ─────────────────────────
    d(704, "Goomy", ["X", "Y"], "Route 14 (rare)"),
    d(705, "Sliggoo", ["X", "Y"], "Evolve Goomy, Route 19"),
    d(706, "Goodra", ["X", "Y"], "Evolve Sliggoo (rain)"),
    d(93, "Haunter", ["X", "Y"], "Route 14, Route 19, Victory Road"),
    d(92, "Gastly", ["X", "Y"], "Caves"),
    d(94, "Gengar", ["X", "Y"], "Trade evolve Haunter"),
    d(195, "Quagsire", ["X", "Y"], "Route 14, Route 19"),
    d(194, "Wooper", ["X", "Y"], "Route 14"),
    d(588, "Karrablast", ["X", "Y"], "Route 14"),
    d(589, "Escavalier", ["X", "Y"], "Trade evolve Karrablast (with Shelmet)"),
    d(616, "Shelmet", ["X", "Y"], "Route 14"),
    d(617, "Accelgor", ["X", "Y"], "Trade evolve Shelmet (with Karrablast)"),
    d(618, "Stunfisk", ["X", "Y"], "Route 14"),
    d(451, "Skorupi", ["X", "Y"], "Route 14"),
    d(452, "Drapion", ["X", "Y"], "Evolve Skorupi"),
    d(69, "Bellsprout", ["X", "Y"], "Route 14"),
    d(70, "Weepinbell", ["X", "Y"], "Route 14, Route 19"),
    d(71, "Victreebel", ["X", "Y"], "Evolve Weepinbell (Leaf Stone)"),

    // ── Route 15, Route 16 ───────────────────────
    d(707, "Klefki", ["X", "Y"], "Route 15, Route 16, Lost Hotel"),
    d(198, "Murkrow", ["X", "Y"], "Route 15"),
    d(430, "Honchkrow", ["X", "Y"], "Evolve Murkrow (Dusk Stone)"),
    d(590, "Foongus", ["X", "Y"], "Route 15, Route 16"),
    d(591, "Amoonguss", ["X", "Y"], "Evolve Foongus"),
    d(624, "Pawniard", ["X", "Y"], "Route 15"),
    d(625, "Bisharp", ["X", "Y"], "Evolve Pawniard"),
    d(262, "Mightyena", ["X", "Y"], "Route 15"),
    d(261, "Poochyena", ["X", "Y"], "Route 15"),
    d(510, "Liepard", ["X", "Y"], "Route 15"),
    d(509, "Purrloin", ["X", "Y"], "Route 15"),
    d(708, "Phantump", ["X", "Y"], "Route 16"),
    d(709, "Trevenant", ["X", "Y"], "Trade evolve Phantump"),
    d(710, "Pumpkaboo", ["X", "Y"], "Route 16"),
    d(711, "Gourgeist", ["X", "Y"], "Trade evolve Pumpkaboo"),
    d(419, "Floatzel", ["X", "Y"], "Route 16, Route 21"),
    d(418, "Buizel", ["X", "Y"], "Route 16"),

    // ── Frost Cavern ─────────────────────────────
    d(712, "Bergmite", ["X", "Y"], "Frost Cavern"),
    d(713, "Avalugg", ["X", "Y"], "Evolve Bergmite"),
    d(238, "Smoochum", ["X", "Y"], "Frost Cavern"),
    d(124, "Jynx", ["X", "Y"], "Frost Cavern"),
    d(614, "Beartic", ["X", "Y"], "Frost Cavern"),
    d(613, "Cubchoo", ["X", "Y"], "Frost Cavern"),
    d(221, "Piloswine", ["X", "Y"], "Frost Cavern"),
    d(220, "Swinub", ["X", "Y"], "Frost Cavern"),
    d(473, "Mamoswine", ["X", "Y"], "Evolve Piloswine (learn Ancient Power)"),
    d(615, "Cryogonal", ["X", "Y"], "Frost Cavern"),
    d(582, "Vanillite", ["X", "Y"], "Frost Cavern"),
    d(583, "Vanillish", ["X", "Y"], "Evolve Vanillite"),
    d(584, "Vanilluxe", ["X", "Y"], "Evolve Vanillish"),

    // ── Route 17 (Snow) ──────────────────────────
    d(459, "Snover", ["X", "Y"], "Route 17"),
    d(460, "Abomasnow", ["X", "Y"], "Route 17, Frost Cavern"),
    d(225, "Delibird", ["X", "Y"], "Route 17"),
    d(215, "Sneasel", ["X", "Y"], "Route 17"),
    d(461, "Weavile", ["X", "Y"], "Evolve Sneasel (Razor Claw, night)"),

    // ── Route 18, Terminus Cave ──────────────────
    d(631, "Heatmor", ["X", "Y"], "Route 18"),
    d(632, "Durant", ["X", "Y"], "Route 18, Terminus Cave"),
    d(305, "Lairon", ["X", "Y"], "Route 18, Terminus Cave"),
    d(304, "Aron", ["X", "Y"], "Terminus Cave"),
    d(306, "Aggron", ["X", "Y"], "Evolve Lairon"),
    d(324, "Torkoal", ["X", "Y"], "Route 18"),
    d(533, "Gurdurr", ["X", "Y"], "Route 18, Victory Road"),
    d(532, "Timburr", ["X", "Y"], "Route 18"),
    d(534, "Conkeldurr", ["X", "Y"], "Trade evolve Gurdurr"),
    d(714, "Noibat", ["X", "Y"], "Terminus Cave, Victory Road"),
    d(715, "Noivern", ["X", "Y"], "Evolve Noibat"),
    d(168, "Ariados", ["X", "Y"], "Terminus Cave"),
    d(167, "Spinarak", ["X", "Y"], "Terminus Cave"),
    d(28, "Sandslash", ["X", "Y"], "Terminus Cave"),
    d(27, "Sandshrew", ["X", "Y"], "Terminus Cave"),

    // ── Route 19 ─────────────────────────────────
    d(621, "Druddigon", ["X", "Y"], "Route 19, Victory Road"),
    d(207, "Gligar", ["X", "Y"], "Route 19"),
    d(472, "Gliscor", ["X", "Y"], "Evolve Gligar (Razor Fang, night)"),

    // ── Route 21, Victory Road ───────────────────
    d(123, "Scyther", ["X", "Y"], "Route 21"),
    d(212, "Scizor", ["X", "Y"], "Trade evolve Scyther (Metal Coat)"),
    d(217, "Ursaring", ["X", "Y"], "Route 21"),
    d(216, "Teddiursa", ["X", "Y"], "Route 21"),
    d(327, "Spinda", ["X", "Y"], "Route 21"),
    d(334, "Altaria", ["X", "Y"], "Route 21, Victory Road"),
    d(333, "Swablu", ["X", "Y"], "Route 21"),
    d(108, "Lickitung", ["X", "Y"], "Victory Road"),
    d(463, "Lickilicky", ["X", "Y"], "Evolve Lickitung (learn Rollout)"),
    d(634, "Zweilous", ["X", "Y"], "Victory Road (rare)"),
    d(633, "Deino", ["X", "Y"], "Victory Road"),
    d(635, "Hydreigon", ["X", "Y"], "Evolve Zweilous"),

    // ── Fishing (various) ────────────────────────
    d(129, "Magikarp", ["X", "Y"], "Fishing (Old Rod, everywhere)"),
    d(130, "Gyarados", ["X", "Y"], "Evolve Magikarp"),
    d(118, "Goldeen", ["X", "Y"], "Fishing (various routes)"),
    d(119, "Seaking", ["X", "Y"], "Fishing, evolve Goldeen"),
    d(341, "Corphish", ["X", "Y"], "Fishing (Route 3)"),
    d(342, "Crawdaunt", ["X", "Y"], "Evolve Corphish"),
    d(60, "Poliwag", ["X", "Y"], "Fishing (Route 15, Route 16)"),
    d(61, "Poliwhirl", ["X", "Y"], "Evolve Poliwag"),
    d(62, "Poliwrath", ["X", "Y"], "Evolve Poliwhirl (Water Stone)"),
    d(186, "Politoed", ["X", "Y"], "Trade evolve Poliwhirl (King's Rock)"),
    d(688, "Binacle", ["X", "Y"], "Route 8 (Fishing), Ambrette Town"),
    d(689, "Barbaracle", ["X", "Y"], "Evolve Binacle"),

    // ── Version exclusive water types ────────────
    d(692, "Clauncher", ["X"], "Route 8 (Fishing)"),
    d(693, "Clawitzer", ["X"], "Evolve Clauncher"),
    d(690, "Skrelp", ["Y"], "Route 8 (Fishing)"),
    d(691, "Dragalge", ["Y"], "Evolve Skrelp"),

    // ── Version exclusive Fairy/Fairy ────────────
    d(684, "Swirlix", ["X"], "Route 7"),
    d(685, "Slurpuff", ["X"], "Trade evolve Swirlix (Whipped Dream)"),
    d(682, "Spritzee", ["Y"], "Route 7"),
    d(683, "Aromatisse", ["Y"], "Trade evolve Spritzee (Sachet)"),

    // ── Honedge line (Route 6) ───────────────────
    d(679, "Honedge", ["X", "Y"], "Route 6"),
    d(680, "Doublade", ["X", "Y"], "Evolve Honedge"),
    d(681, "Aegislash", ["X", "Y"], "Evolve Doublade (Dusk Stone)"),

    // ── Pokemon Village / Late routes ────────────
    d(132, "Ditto", ["X", "Y"], "Pokemon Village"),
    d(571, "Zoroark", ["X", "Y"], "Pokemon Village"),
    d(570, "Zorua", ["X", "Y"], "Breed Zoroark"),
    d(354, "Banette", ["X", "Y"], "Pokemon Village"),
    d(353, "Shuppet", ["X", "Y"], "Pokemon Village"),
    d(39, "Jigglypuff", ["X", "Y"], "Pokemon Village, Route 20"),
    d(40, "Wigglytuff", ["X", "Y"], "Evolve Jigglypuff (Moon Stone)"),
    d(271, "Lombre", ["X", "Y"], "Pokemon Village"),
    d(270, "Lotad", ["X", "Y"], "Pokemon Village"),
    d(272, "Ludicolo", ["X", "Y"], "Evolve Lombre (Water Stone)"),

    // ── Route 22 ─────────────────────────────────
    d(559, "Scraggy", ["X", "Y"], "Route 22"),
    d(560, "Scrafty", ["X", "Y"], "Evolve Scraggy"),
    d(37, "Vulpix", ["X", "Y"], "Friend Safari"),
    d(38, "Ninetales", ["X", "Y"], "Evolve Vulpix (Fire Stone)"),
    d(58, "Growlithe", ["X", "Y"], "Route 10"),
    d(59, "Arcanine", ["X", "Y"], "Evolve Growlithe (Fire Stone)"),

    // ── Gym leader teams / notable species ───────
    d(283, "Surskit", ["X", "Y"], "Route 3 (Surfing)"),
    d(284, "Masquerain", ["X", "Y"], "Evolve Surskit"),
    d(303, "Mawile", ["X"], "Glittering Cave"),
    d(189, "Jumpluff", ["X", "Y"], "Route 7"),
    d(188, "Skiploom", ["X", "Y"], "Route 7"),
    d(187, "Hoppip", ["X", "Y"], "Route 7"),
    d(82, "Magneton", ["X", "Y"], "Evolve Magnemite"),
    d(81, "Magnemite", ["X", "Y"], "Lost Hotel"),
    d(462, "Magnezone", ["X", "Y"], "Evolve Magneton (level up in special area)"),
    d(184, "Azumarill", ["X", "Y"], "Route 22"),
    d(183, "Marill", ["X", "Y"], "Route 3 (Surfing)"),

    // ── Route 20 (Winding Woods) ─────────────────
    d(285, "Shroomish", ["X", "Y"], "Route 20"),
    d(286, "Breloom", ["X", "Y"], "Evolve Shroomish"),
    d(357, "Tropius", ["X", "Y"], "Route 20"),
    d(114, "Tangela", ["X", "Y"], "Route 20"),
    d(465, "Tangrowth", ["X", "Y"], "Evolve Tangela (learn Ancient Power)"),

    // ── Surf / Water encounters ──────────────────
    d(90, "Shellder", ["X", "Y"], "Route 12 (Fishing)"),
    d(91, "Cloyster", ["X", "Y"], "Evolve Shellder (Water Stone)"),
    d(116, "Horsea", ["X", "Y"], "Route 12 (Fishing)"),
    d(117, "Seadra", ["X", "Y"], "Evolve Horsea"),
    d(230, "Kingdra", ["X", "Y"], "Trade evolve Seadra (Dragon Scale)"),
    d(120, "Staryu", ["X", "Y"], "Route 12 (Fishing)"),
    d(121, "Starmie", ["X", "Y"], "Evolve Staryu (Water Stone)"),

    // ── Santalune Gym line ───────────────────────
    d(36, "Clefable", ["X", "Y"], "Evolve Clefairy (Moon Stone)"),
    d(35, "Clefairy", ["X", "Y"], "Friend Safari"),
    d(173, "Cleffa", ["X", "Y"], "Breed Clefairy"),

    // ── Miscellaneous obtainable ─────────────────
    d(143, "Snorlax", ["X", "Y"], "Route 7 (sleeping, use Poke Flute)"),
    d(446, "Munchlax", ["X", "Y"], "Breed Snorlax (Full Incense)"),
    d(142, "Aerodactyl", ["X", "Y"], "Glittering Cave (Old Amber)"),
    d(308, "Medicham", ["X", "Y"], "Victory Road"),
    d(307, "Meditite", ["X", "Y"], "Victory Road"),
    d(476, "Probopass", ["X", "Y"], "Evolve Nosepass (level up in special area)"),
    d(299, "Nosepass", ["X", "Y"], "Route 10"),
    d(103, "Exeggutor", ["X", "Y"], "Evolve Exeggcute (Leaf Stone)"),
    d(102, "Exeggcute", ["X", "Y"], "Route 12"),
    d(609, "Chandelure", ["X", "Y"], "Evolve Lampent (Dusk Stone)"),
    d(608, "Lampent", ["X", "Y"], "Evolve Litwick"),
    d(607, "Litwick", ["X", "Y"], "Lost Hotel"),

    // ── Legendaries ──────────────────────────────
    d(716, "Xerneas", ["X"], "Team Flare HQ, Geosenge Town (mandatory catch, Lv. 50)"),
    d(717, "Yveltal", ["Y"], "Team Flare HQ, Geosenge Town (mandatory catch, Lv. 50)"),
    d(718, "Zygarde", ["X", "Y"], "Terminus Cave deepest chamber (post-game, Lv. 70)"),
    d(150, "Mewtwo", ["X", "Y"], "Unknown Dungeon, Pokemon Village (post-game, Lv. 70)"),
    d(144, "Articuno", ["X", "Y"], "Roaming then Sea Spirit's Den (post-game, Lv. 70, if Chespin starter)"),
    d(145, "Zapdos", ["X", "Y"], "Roaming then Sea Spirit's Den (post-game, Lv. 70, if Froakie starter)"),
    d(146, "Moltres", ["X", "Y"], "Roaming then Sea Spirit's Den (post-game, Lv. 70, if Fennekin starter)"),
  ],
};
